### ISSUE TITLE
failed to make facebook mysql-5.6

### ISSUE THREAD

**Issue by zhaiwx1987** [facebook/mysql-5.6#1]
Hi:
I am trying to cmake . && make but unfortunately failed to make it. 

error message:
/u01/project/mysql-5.6/sql/item_func.h:31: error: ‘std::isfinite’ has not been declared

Look forward to your reply;

thanks.

**Comment by zhaiwx1987** [comment]
I finally succeed to run facebook-mysql. 

First , I upgraded gcc from 4.5 to 4.7 to support c++11
second, I updated libstdc++ to the latest version

**Comment by steaphan-fb-com** [comment]
Yes, we do not test with older build environments.  We have only tested this with gcc-4.6 and gcc-4.7, both with only relatively up-to-date base libraries.
