### ISSUE TITLE
Allow to enable both InnoDB and RocksDB storage engines or not?

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#101]
There are ongoing discussions whether to allow to enable both InnoDB and RocksDB storage engines or not. Currently we do not allow but some people complain about the decision because it makes harder to use.
### Allowing to enable both InnoDB and RocksDB engines:

o Testing MyRocks is easier -- just executing  "ALTER TABLE innodb_table ENGINE=RocksDB"
x It is necessary to write additional test cases for supporting mixed engines
x Hard to make it really work in production, for example:
- online logical backup (mysqldump --single-transaction) supports only one of the engines at one time
- online physical backup (xtrabackup, myrockshotbackup) supports only one of the engines at one time
- when updating mixed engines within the same transaction, it's not atomic.
- crash safe replication does not work. Replication state is maintained in mysql.slave_gtid_info system table, which must be either InnoDB or RocksDB, not both.
### Restricting to enable either InnoDB or RocksDB (current implementation):

o All of the potential production issues describing the above can be automatically prevented
o It is not necessary to write test cases for supporting mixed engines
x Explicit configuration (--default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB) is needed to enable MyRocks.
x Testing MyRocks for existing InnoDB deployment is more complex. "ALTER TABLE innodb_table ENGINE=RocksDB" is not supported. Creating another MySQL instance with MyRocks, then dump and reload is needed.

I'm thinking of two workarounds to mitigate the issue.
1. Hybrid implementation -- restricting by default but allowing mixed engines by one my.cnf parameter (i.e. rocksdb_allow_mixed_engines) but clarify it's for experimental purposes only. Not writing any test case supporting mixed engines.
2. Continue to restrict engine but provide a tool to dump and reload easily.

**Comment by mdcallag** [comment]
I am not aware of a large number of tests for mixed engines in MySQL today. All we need is a few to confirm that basic things work.

The goal is to not to make mixed engines run in production with backups and crash safety. The goal is to make it easy to try MyRocks when currently using InnoDB.

**Comment by RoelVdP** [comment]
From a stress/crash testing perspective, pquery will work fine with multiple engines.

**Comment by mdcallag** [comment]
see https://github.com/facebook/mysql-5.6/issues/106

**Comment by RoelVdP** [comment]
The generator we added to pquery also supports good multi-engine stress testing.
