### ISSUE TITLE
Make BIT, ENUM, SET covering for MyRocks

### ISSUE THREAD

**Issue by lth** [facebook/mysql-5.6#1025]
These data types are not covering in MyRocks, meaning that secondary keys containing these fields cannot do index-only scans, and primary keys containing these fields waste extra space.

Fix this by making these fields covering.

**Comment by yizhang82** [comment]
This is addressed in https://github.com/facebook/mysql-5.6/commit/1b31d40a85497a706e79fe10d0533e46bad00207 for fb-mysql-8.0.17
