### ISSUE TITLE
insert_id and affected_rows modified in all cases

### ISSUE THREAD

**Issue by noony** [facebook/mysql-5.6#103]
mysql_ping seems to modify affected rows and insert_id after every command.

Difference seems to be in here (I'm not sure): 

https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.24.97/sql-common/client.c#L660
vs
https://github.com/webscalesql/webscalesql-5.6/blob/webscalesql-5.6.26/sql-common/client.c#L5370

Related to https://github.com/facebook/hhvm/issues/6531(code example in issue)

**Comment by jkedgar** [comment]
I am not able to reproduce this on 5.6.27.75.  It looks like it might have been fixed during the rebase from 5.6.24.97 to 5.6.27.75.  Can this be closed now?

**Comment by jtolmer** [comment]
In the rebase, I dropped https://github.com/facebook/mysql-5.6/commit/48aa658ab42c8b1aff71d4b426e7d2fc59b2d205 because we weren't using the feature.
