### ISSUE TITLE
Don't hardwire location for libz

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#104]
Discussion was at: https://www.facebook.com/groups/mysqlonrocksdb/permalink/1017202325010623/

Following the build steps linked from https://github.com/…/mysq…/wiki/Getting-Started-with-MyRocks
What needs this? What did we break that hardwires libz to /usr/lib/libz.so?

> sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/libz.so
> From cmake output for fbmysql build
> -- Library webscalesqlclient depends on OSLIBS -lpthread;/usr/lib/libz.so;m;rt;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;dl
> -- Library mysqlserver depends on OSLIBS -lpthread;/usr/lib/libz.so;m;rt;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;dl;crypt;aio;snappy;lz4;bz2
> Using same cmake command line for upstream mysql build and results are better
> -- Library mysqlclient depends on OSLIBS -lpthread;/usr/lib/x86_64-linux-gnu/libz.so;m;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;dl
> -- Library mysqlserver depends on OSLIBS -lpthread;/usr/lib/x86_64-linux-gnu/libz.so;m;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;dl;crypt;aio

**Comment by mdcallag** [comment]
This comes from old change by us to cmake/zlib.cmake

commit cfb9829f6ee6be422b7f4d3a455de0b23328a20b
Author: Steaphan Greene steaphan@fb.com
Date:   Mon Jul 22 12:25:37 2013 -0700

```
Enable linking with system libraries

Summary:
WebScaleSQL Feature: Basic Build Fixes

This gets mysqld, mysql, xtrabackup, libmysqlclient, etc...
all to link correctly with openssl, zlib, etc....

This lets us switch from the embedded versions cleanly.

Test Plan:
Built both debug and release, both with and without the build system
changes to use system openssl libs (and others).

Both types of builds work with this diff (embedded and system).

Reviewers: flamingcow, pivanof, jeremycole, andrew-ford, inaam-rana

Reviewed By: pivanof

CC: jtolmer, MarkCallaghan

Differential Revision: https://reviews.facebook.net/D15645
```

**Comment by mdcallag** [comment]
FB changed cmake/zlib.cmake a few years back, that breaks open source builds for me

commit cfb9829f6ee6be422b7f4d3a455de0b23328a20b
Author: Steaphan Greene steaphan@fb.com
Date:   Mon Jul 22 12:25:37 2013 -0700

```
Enable linking with system libraries

Summary:
WebScaleSQL Feature: Basic Build Fixes

This gets mysqld, mysql, xtrabackup, libmysqlclient, etc...
all to link correctly with openssl, zlib, etc....

This lets us switch from the embedded versions cleanly.

Test Plan:
Built both debug and release, both with and without the build system
changes to use system openssl libs (and others).

Both types of builds work with this diff (embedded and system).

Reviewers: flamingcow, pivanof, jeremycole, andrew-ford, inaam-rana

Reviewed By: pivanof

CC: jtolmer, MarkCallaghan

Differential Revision: https://reviews.facebook.net/D15645
```

**Comment by yoshinorim** [comment]
I think building with -DWITH_ZLIB=bundled fixes the issue, as Mark suggests. It's now documented in the wiki.

**Comment by mdcallag** [comment]
I want to allow people to use the system library. Will use 197 as the base bug and keep this closed as a duplicate of https://github.com/facebook/mysql-5.6/issues/197

**Comment by mdcallag** [comment]
And this won't be fixed by the fix for 197. The workload is WITH_ZLIB=bundled

**Comment by gunnarku** [comment]
Goal here is to make sure that `WITH_ZLIB` will behave similarly to `WITH_SNAPPY`, _i.e._, enable a user to specify what version of `libz` to use.

**Comment by gunnarku** [comment]
Fixed by https://github.com/facebook/mysql-5.6/commit/01b9be5f8d9d6c46212e6cce647e1c64e5445610.
