### ISSUE TITLE
write and bulk_load were all blocked when set allow_blocking_flush=true.

### ISSUE THREAD

**Issue by TenderWang** [facebook/mysql-5.6#1043]
Now  allow_blocking_flush was set FALSE . I  set session rocksdb_bulk_load =1 in pt-online-schema-change codes to speed up the process of DDL. 

When I use pt-osc to ddl , at the same time , another session do dml operations on the table. After running a while ,pt-osc report error like this "External file requires flush" . 

So I  change allow_blocking_flush  of IngestExternalFileOptions into True, but two sessions are all blocked .

**Comment by LoveTommy** [comment]
WriteThread::Writer w;

**Comment by TenderWang** [comment]
in DBImpl::IngestExternalFiles function, "Stop writes to the DB by entering both write threads."
When (status.ok() && at_least_one_cf_need_flush) was true, in FlushMemtabl path ,WriteThread::Writer nonmem_w enters but not leader so it waits. But DBImpl::IngestExternalFiles waits until FlushMemtable finish. so bulk_load was blocked .

**Comment by TenderWang** [comment]
The version is 5.13.0

**Comment by lth** [comment]
The bulk load feature is not designed to support concurrent writes to the same key range while bulk load is happening.

**Comment by TenderWang** [comment]
thank you @lth

**Comment by TenderWang** [comment]
what impacts on bulk load when concurrent writes? @lth
