### ISSUE TITLE
Compile error "/home/work/workspace/mysql-5.6/mysys/my_compress.c:542: undefined reference to `LZ4F_resetDecompressionContext'"

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/mysql-5.6#1114]
My os is centos 7.7.1908 and I have installed lz4 by `yum install -y lz4-devel`. The install directory is as follows:
```
work@ost:~/workspace/mysql-5.6/bld $ ls /usr/lib64/liblz*
/usr/lib64/liblz4.so  /usr/lib64/liblz4.so.1  /usr/lib64/liblz4.so.1.7.5  /usr/lib64/liblzma.so.5  /usr/lib64/liblzma.so.5.2.2

work@ost:~/workspace/mysql-5.6/bld $ ls /usr/include/lz4*
/usr/include/lz4frame.h  /usr/include/lz4.h  /usr/include/lz4hc.h
```
Anybody help?

**Comment by lth** [comment]
Your lz4 version is too old. You can try applying this patch to see if it works (https://github.com/hermanlee/mysql-5.6/commit/8fd1e1dc40ffca01ec5bd1143e1fc6e57810f847)

**Comment by GOGOYAO** [comment]
> Your lz4 version is too old. You can try applying this patch to see if it works ([hermanlee@8fd1e1d](https://github.com/hermanlee/mysql-5.6/commit/8fd1e1dc40ffca01ec5bd1143e1fc6e57810f847))

Thank you. It works
