### ISSUE TITLE
Multi-threaded RQG tests yields mismatched table results in replication stack

### ISSUE THREAD

**Issue by mariadb-DanielLee** [facebook/mysql-5.6#114]
Source Date: 11/30/2015
Test Environment: Replication, 1 master and 1 slave.  Both instances on the same VM
VM Memory: 8 GB

When running the tests in Random Query Generator using two or more threads (concurrency tests, tested with up to 5 threads), the table content from both master and slave are not matching, in terms of both row counts and contents.  I tested with various numbers of queries, from 1000000 down to 1000 and still got mismatched results.  Starting with a fresh database for each test did not help to get better results.

I ran the same tests using a single thread and got matching results.

Ramdom Query Generator command I used:

myrocks@rocksdb:~/mariadb-patches$ perl gentest.pl    --dsn=dbi:mysql:host=localhost:port=3306:user=root:database=test:mysql_socket=/tmp/repMaster.sock    --gendata=conf/examples/example.zz    --grammar=conf/examples/example.yy --threads=2 --queries=1000

**Comment by santoshbanda** [comment]
what kind of binlog format are you using? MyRocks doesn't have gap locking which implies SBR creates data inconsistencies. FYI, yoshinori has a diff https://reviews.facebook.net/D51231 to block unsafe usage

**Comment by mariadb-DanielLee** [comment]
ok.  I forgot to change binlog-format to ROW, after getting the new source code.  

I did use binlog-format=ROW last week and got mismatching checksums, but it turned out that there was an issue with checksum itself.  The issue was reported in issue #110.  Now I am doing diffs on table content instead.

I will set binlog-format to ROW, run the tests again, then post an update.

Thanks.

**Comment by mariadb-DanielLee** [comment]
My bad, setting binlog-format to ROW fixed the problem.  I updated my default .cnf template file to include the parameter.

Thanks.
