### ISSUE TITLE
Use fail safe RocksDB options

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#115]
In RocksDB, this is now supported by calling the utility function CheckOptionsCompatibility with the input set of options and a target dbpath:

// Returns Status::OK if the input DBOptions and ColumnFamilyDescriptors
// are compatible with the latest options stored in the specified DB path.
//
// If the return status is non-ok, it means the specified RocksDB instance
// might not be correctly opened with the input set of options. Currently,
// changing one of the following options will fail the compatibility check:
//
// \* comparator
// \* prefix_extractor
// \* table_factory
// \* merge_operator
Status CheckOptionsCompatibility(
const std::string& dbpath, Env\* env, const DBOptions& db_options,
const std::vector<ColumnFamilyDescriptor>& cf_descs);

https://github.com/…/incl…/rocksdb/utilities/options_util.h…

**Comment by yoshinorim** [comment]
Documents in RocksDB: https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File

**Comment by gunnarku** [comment]
Review is out at https://reviews.facebook.net/D54147.
