### ISSUE TITLE
How do you measure effectiveness of column family?

### ISSUE THREAD

**Issue by utdrmac** [facebook/mysql-5.6#1170]
Consider the following query:

    SELECT cast_info.* FROM cast_info INNER JOIN title on (cast_info.movie_id = title.id)
    WHERE cast_info.person_id = 1506619 AND title.kind_id = 1
    ORDER BY title.production_year DESC, title.id DESC

The explain plan for this query:

```
+----+-------------+-----------+------------+------+--------------------------+------------+---------+---------------------------+--------+----------+----------------------------------+
| id | select_type | table     | partitions | type | possible_keys            | key        | key_len | ref                       | rows   | filtered | Extra                            |
+----+-------------+-----------+------------+------+--------------------------+------------+---------+---------------------------+--------+----------+----------------------------------+
|  1 | SIMPLE      | title     | NULL       | ref  | PRIMARY,kind_id_prod_yr  | kind_id    | 4       | const                     | 594758 |   100.00 | Backward index scan; Using index |
|  1 | SIMPLE      | cast_info | NULL       | ref  | movie_id,movie_id_2      | movie_id_2 | 8       | imdb_rocks.title.id,const |      1 |   100.00 | NULL                             |
+----+-------------+-----------+------------+------+--------------------------+------------+---------+---------------------------+--------+----------+----------------------------------+
2 rows in set, 1 warning (0.00 sec)
```

Given the above, the theory is that a `rev:kind_id_prod_yr` column family on the `kind_id_prod_yr` index will provide a benefit since the ORDER BY is DESC.

In basic testing, this is only showing a minor improvement (profiling=1):

```
rev:         | executing                      | 2.879243 |
no_rev:  | executing                      | 3.005562 |
```

Based on these two results, I would not bother with the additional complexity of a new CF.

Is there a more appropriate way to judge that the rev:cf is indeed more efficient?

**Comment by yoshinorim** [comment]
Rev column family is effective if you have lots of use cases of scanning just the index (e.g. full index scan, covering index) and benefit is approximately 15%. For join queries, relative benefits are smaller because of point lookup costs are equally expensive.
