### ISSUE TITLE
Change "static rocksdb::DBOptions db_options" to not static

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#122]
By default, RocksDB initializes ThreadLocal, then initializes PosixEnv via static initializer.
Destructor terminates objects in reverse order, so terminating PosixEnv (calling pthread_mutex_lock), then ThreadLocal (calling pthread_mutex_destroy). This ordering doesn't cause problems.

MyRocks accidentally changed the initialization ordering. MyRocks has a static variable rocksdb::DBOptions and initializes it via static initializer function init_db_options(). ha_rocksdb.cc seems to be initialized earlier than any other rocksdb src files. rocksdb::DBOptions::DBOptions() calls PosixEnv(), so PosixEnv is initialized here. After that, RocksDB initializes ThreadLocal. So initialization ordering has changed to PosixEnv->ThreadLocal ordering. Destructor terminates in ~ThreadLocal->~PosixEnv order, so pthread_mutex_destroy() is called earlier than pthread_mutex_lock. This may cause assertion error in RocksDB at shutdown.

I tried not to use static db_options in ha_rocksdb.cc, then no more assertion error has happened.

**Comment by yoshinorim** [comment]
Also, it is necessary to expose the latest DB options from RocksDB to MyRocks.

**Comment by mdcallag** [comment]
Why must MyRocks fix this? I think that RocksDB should do the right thing on shutdown to avoid obscure & hard to debug SIGABORT

**Comment by yhchiang** [comment]
@yoshinorim: Thanks for the detailed explanation.  If that's the case, can you try the following patch which might enforce the construction order of PosixEnv and ThradLocalPtr::StaticMeta:
https://reviews.facebook.net/D51789

**Comment by yoshinorim** [comment]
MyRocks side fix: https://reviews.facebook.net/D51933
