### ISSUE TITLE
My open source builds are broken

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#1262]
The problem commit [is here](https://github.com/facebook/mysql-5.6/commit/2a347f6520235a6c278f505ea456bf18c5dba9a7) -- "MyRocks to support both dynamic and static plugins".

The cmake command line [is here](https://github.com/mdcallag/mytools/blob/master/bench/conf/nuc8i7.ub1804/cmk.fbmysql8). I have been using this command line for years. It doesn't set -DMYSQL_DYNAMIC_PLUGIN. It [fails here](https://gist.github.com/mdcallag/4e2fdd3d383d86978d9fdb4a4d70a694). I will try -DWITH_UNIT_TESTS=OFF.

This fails on Ubuntu 22.04 with gcc.

Before compiling I apply [this patch](https://gist.github.com/mdcallag/625df44eea073ec8d803860d4ab4b2d6) although I might only need the diff for get_rocksdb_files.sh from that patch.

**Comment by mdcallag** [comment]
Workaround is to add -DWITH_UNIT_TESTS=OFF to cmake command line.

Will try one more thing.

**Comment by mdcallag** [comment]
A suggestion from @yoshinorim also works and doesn't require me to add -DWITH_UNIT_TESTS
```
Add this line to storage/rocksdb/CMakeLists.txt
->   ../../sql/partitioning/partition_base.cc
   nosql_access.cc nosql_access.h
   sql_dd.cc sql_dd.h
   ${ROCKSDB_LIB_SOURCES}
```

**Comment by yoshinorim** [comment]
Fixed by https://github.com/facebook/mysql-5.6/commit/c75bf30d86a214a3a7106e5df0df47a130306c2f
