### ISSUE TITLE
Warning from compiling clone_os.cc

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#1270]
The joys of auto types, from git blame plugin/clone/src/clone_os.cc

```
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 308)     if (actual_size > length) {
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 309)       assert(block_pad_len > 0);
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 310)       assert(to_file.o_direct_uneven_file_size);
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 311)       const auto file_size = my_tell(to_file.file_desc, MYF(MY_WME));
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 312)       if (file_size < 0) {
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 313)         return ER_ERROR_ON_WRITE;
d46fb7f495a1 (Laurynas Biveinis    2023-02-02 09:24:09 -0800 314)       }
```

The warning is:
```
/home/mdcallag/git/fbmysql-56/plugin/clone/src/clone_os.cc: In function ‘int clone_os_copy_buf_to_file(uchar*, Ha_clone_file, uint, const char*)’:
/home/mdcallag/git/fbmysql-56/plugin/clone/src/clone_os.cc:312:21: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  312 |       if (file_size < 0) {
      |           ~~~~~~~~~~^~~
```

**Comment by mdcallag** [comment]
Another one, but an error rather than a warning
```
In file included from /home/mdcallag/git/fbmysql-56/storage/rocksdb/ha_rocksdb.cc:87:
/home/mdcallag/git/fbmysql-56/storage/rocksdb/./clone/common.h: In member function ‘constexpr bool myrocks::clone::locator::has_applier_status() const’:
/home/mdcallag/git/fbmysql-56/storage/rocksdb/./clone/common.h:282:35: error: call to non-‘constexpr’ function ‘bool std::vector<_Tp, _Alloc>::empty() const [with _Tp = myrocks::clone::locator::file_state; _Alloc = std::allocator<myrocks::clone::locator::file_state>]’
  282 |     return !m_applier_status.empty();
      |             ~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by laurynas-biveinis** [comment]
> /home/mdcallag/git/fbmysql-56/plugin/clone/src/clone_os.cc:312:21: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
>   312 |       if (file_size < 0) {
>       |           ~~~~~~~~~~^~~
> ```

Should read `file_size == MY_FILEPOS_ERROR`, will PR as soon as the trunk status is clear

**Comment by laurynas-biveinis** [comment]
> /home/mdcallag/git/fbmysql-56/storage/rocksdb/./clone/common.h: In member function ‘constexpr bool myrocks::clone::locator::has_applier_status() const’:
> /home/mdcallag/git/fbmysql-56/storage/rocksdb/./clone/common.h:282:35: error: call to non-‘constexpr’ function ‘bool std::vector<_Tp, _Alloc>::empty() const [with _Tp = myrocks::clone::locator::file_state; _Alloc = std::allocator<myrocks::clone::locator::file_state>]’
>   282 |     return !m_applier_status.empty();
>       |             ~~~~~~~~~~~~~~~~~~~~~~^~

Was already fixed last week in the clone PR, apparently an older version had been merged instead

**Comment by hermanlee** [comment]
I'm in the process of fixing this. A slightly older version of the PR was pushed, and the patch summaries were also missing. The fixed patch should be on its way via a forced update.

**Comment by laurynas-biveinis** [comment]
Should be fixed by https://github.com/facebook/mysql-5.6/commit/5728dd7dfcb5807542189836da3013b9e06515a5

**Comment by laurynas-biveinis** [comment]
This issue should be closed (I cannot do that)
