### ISSUE TITLE
Optimize MyRocksTablePropertiesCollector::AddUserKey()

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#128]
MyRocksTablePropertiesCollector::AddUserKey() increases data loading time a lot. Here are some numbers for loading our data with 12 client threads.

Default (load optimized my.cnf) settings: 49 minutes
Commenting out entire MyRocksTablePropertiesCollector::AddUserKey(): 37 minutes

So it is worth optimizing AddUserKey().

Here are some CPU stats. 
![perf_on_furious_compaction](https://cloud.githubusercontent.com/assets/253614/11969011/834ffcb4-a8c8-11e5-9124-dd316ec196ac.png)

Looks like RDBSE_KEYDEF::compare_keys() (comparing current key and previous key) is the most time consuming. "skip_max_length" is also called via compare_keys(). Let's figure out if it's possible to optimize compare_keys() more.

**Comment by hermanlee** [comment]
Talking to Yoshi about this, a simple fix could be to reduce the sampling rate from every key to every N keys.

**Comment by gunnarku** [comment]
Trying to replicate the findings so that I can demonstrate causality in case I will make any fixes. Current thinking is to sample a certain percentage of items, rather than every `N` keys.

**Comment by gunnarku** [comment]
Closed by https://github.com/facebook/mysql-5.6/commit/065bcc501481da60362fa0a1df8418b33dccce22
