### ISSUE TITLE
Server hang on DROP DATABASE

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#135]
<pre>
Testcase:
# --no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --skip-innodb-buffer-page --default-storage-engine=RocksDB
DROP DATABASE test;CREATE DATABASE test;USE test;
CREATE TABLE t1(c1 INT PRIMARY KEY);
LOCK TABLES t1 READ;
SET @@SESSION.AUTOCOMMIT=0;
SELECT c1 FROM t1;
START TRANSACTION WITH CONSISTENT SNAPSHOT,READ ONLY;
DROP DATABASE test;  # Hangs, CTRL+C does not work on first attempt.
</pre>

Issue does not reproduce on mysql-5.6.23 nor Percona-Server-5.6.25.

<pre>
mysql> SHOW PROCESSLIST;
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
| Id | User | Host      | db   | Command | Time | State                | Info               | Rows examined | Rows sent | Tid   |
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
|  1 | root | localhost | test | Query   |   23 | checking permissions | DROP DATABASE test |             0 |         0 | 12441 |
|  2 | root | localhost | test | Query   |    0 | cleaning up          | SHOW PROCESSLIST   |             0 |         0 | 21391 |
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
2 rows in set (0.00 sec)

After CTRL+C:

mysql> SHOW PROCESSLIST;
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
| Id | User | Host      | db   | Command | Time | State                | Info               | Rows examined | Rows sent | Tid   |
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
|  1 | root | localhost | test | Killed  |  242 | checking permissions | DROP DATABASE test |             0 |         0 | 12441 |
|  5 | root | localhost | test | Query   |    0 | cleaning up          | SHOW PROCESSLIST   |             0 |         0 | 21391 |
+----+------+-----------+------+---------+------+----------------------+--------------------+---------------+-----------+-------+
2 rows in set (0.00 sec)

+thread apply all bt (before CTRL+C)

Thread 7 (Thread 0x7fda07fff700 (LWP 11716)):
+bt
#0  0x00007fda0a5d17fa in do_sigwaitinfo (info=0x7fda07ffeab0, set=0x7fda07ffeb30) at ../sysdeps/unix/sysv/linux/sigwaitinfo.c:55
#1  __GI___sigwaitinfo (set=0x7fda07ffeb30, info=0x7fda07ffeab0) at ../sysdeps/unix/sysv/linux/sigwaitinfo.c:82
#2  0x0000000000e4532b in timer_notify_thread_func (arg=0x7fff529b68d0) at /git/FB-mysql-5.6/mysys/posix_timers.c:77
#3  0x00007fda0c63edc5 in start_thread (arg=0x7fda07fff700) at pthread_create.c:308
#4  0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 6 (Thread 0x7fda063ff700 (LWP 11725)):
+bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000e4159b in safe_cond_timedwait (cond=0x1fc7360 <stop_cond>, mp=0x1fc71e0 <stop_cond_mutex>, abstime=0x7fda063feb80, file=0x16b7320 "/git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h", line=1211) at /git/FB-mysql-5.6/mysys/thr_mutex.c:278
#2  0x0000000000e4e7a3 in inline_mysql_cond_timedwait (that=0x1fc7360 <stop_cond>, mutex=0x1fc71e0 <stop_cond_mutex>, abstime=0x7fda063feb80) at /git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h:1211
#3  0x0000000000e5fdad in background_thread () at /git/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:7060
#4  0x00007fda0c63edc5 in start_thread (arg=0x7fda063ff700) at pthread_create.c:308
#5  0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 5 (Thread 0x7fda05bfe700 (LWP 11726)):
+bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000e4159b in safe_cond_timedwait (cond=0x1fcfd40 <drop_index_interrupt_cond>, mp=0x1fcfcc0 <drop_index_interrupt_mutex>, abstime=0x7fda05bfdb60, file=0x16b7320 "/git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h", line=1211) at /git/FB-mysql-5.6/mysys/thr_mutex.c:278
#2  0x0000000000e4e7a3 in inline_mysql_cond_timedwait (that=0x1fcfd40 <drop_index_interrupt_cond>, mutex=0x1fcfcc0 <drop_index_interrupt_mutex>, abstime=0x7fda05bfdb60) at /git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h:1211
#3  0x0000000000e5caa8 in drop_index_thread () at /git/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:6115
#4  0x00007fda0c63edc5 in start_thread (arg=0x7fda05bfe700) at pthread_create.c:308
#5  0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 4 (Thread 0x7fda0cc8f700 (LWP 11728)):
+bt
#0  0x00007fda0c645e91 in do_sigwait (sig=0x7fda0cc8ebc8, set=<optimized out>) at ../sysdeps/unix/sysv/linux/sigwait.c:61
#1  __sigwait (set=0x7fda0cc8eb30, sig=0x7fda0cc8ebc8) at ../sysdeps/unix/sysv/linux/sigwait.c:99
#2  0x000000000099bc46 in signal_hand (arg=0x0) at /git/FB-mysql-5.6/sql/mysqld.cc:3800
#3  0x00007fda0c63edc5 in start_thread (arg=0x7fda0cc8f700) at pthread_create.c:308
#4  0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 3 (Thread 0x7fda0cc3e700 (LWP 12441)):
+bt
#0  0x0000000000a9fb1b in MDL_context::find_ticket (this=0x7fda081a90e8, mdl_request=0x7fda0cc39f50, result_duration=0x7fda0cc3a104) at /git/FB-mysql-5.6/sql/mdl.cc:1893
#1  0x0000000000aa194f in MDL_context::is_lock_owner (this=0x7fda081a90e8, mdl_namespace=MDL_key::GLOBAL, db=0x158a438 "", name=0x158a438 "", mdl_type=MDL_INTENTION_EXCLUSIVE) at /git/FB-mysql-5.6/sql/mdl.cc:2896
#2  0x0000000000ab989a in lock_db_routines (thd=0x7fda081a9000, db=0x7fda044600b0 "test") at /git/FB-mysql-5.6/sql/sp.cc:1546
#3  0x0000000000b2af11 in mysql_rm_db (thd=0x7fda081a9000, db=0x7fda044600b0 "test", if_exists=false, silent=false) at /git/FB-mysql-5.6/sql/sql_db.cc:1031
#4  0x0000000000b669e0 in mysql_execute_command (thd=0x7fda081a9000, statement_start_time=0x7fda0cc3c938, post_parse=0x7fda0cc3d9a0) at /git/FB-mysql-5.6/sql/sql_parse.cc:4484
#5  0x0000000000b6e118 in mysql_parse (thd=0x7fda081a9000, rawbuf=0x7fda04460010 "DROP DATABASE test", length=18, parser_state=0x7fda0cc3d2f0, last_timer=0x7fda0cc3d9a0, async_commit=0x7fda0cc3d99f "") at /git/FB-mysql-5.6/sql/sql_parse.cc:7385
#6  0x0000000000b5f7fb in dispatch_command (command=COM_QUERY, thd=0x7fda081a9000, packet=0x7fda08350001 "DROP DATABASE test", packet_length=18) at /git/FB-mysql-5.6/sql/sql_parse.cc:1595
#7  0x0000000000b5e0bf in do_command (thd=0x7fda081a9000) at /git/FB-mysql-5.6/sql/sql_parse.cc:1071
#8  0x0000000000b24d6c in do_handle_one_connection (thd_arg=0x7fda081a9000) at /git/FB-mysql-5.6/sql/sql_connect.cc:1071
#9  0x0000000000b2466b in handle_one_connection (arg=0x7fda081a9000) at /git/FB-mysql-5.6/sql/sql_connect.cc:929
#10 0x00007fda0c63edc5 in start_thread (arg=0x7fda0cc3e700) at pthread_create.c:308
#11 0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 2 (Thread 0x7fda0cbed700 (LWP 21391)):
+bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000e413ce in safe_cond_wait (cond=0x1f877e0 <COND_thread_cache>, mp=0x1f85e00 <LOCK_thread_count>, file=0x14c5a28 "/git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h", line=1174) at /git/FB-mysql-5.6/mysys/thr_mutex.c:240
#2  0x0000000000995d74 in inline_mysql_cond_wait (that=0x1f877e0 <COND_thread_cache>, mutex=0x1f85e00 <LOCK_thread_count>) at /git/FB-mysql-5.6/include/mysql/psi/mysql_thread.h:1174
#3  0x000000000099a278 in block_until_new_connection () at /git/FB-mysql-5.6/sql/mysqld.cc:2899
#4  0x000000000099a4e4 in one_thread_per_connection_end (thd=0x7fda06584000, block_pthread=true) at /git/FB-mysql-5.6/sql/mysqld.cc:2987
#5  0x0000000000b24e1c in do_handle_one_connection (thd_arg=0x7fda06584000) at /git/FB-mysql-5.6/sql/sql_connect.cc:1088
#6  0x0000000000b2466b in handle_one_connection (arg=0x7fda06584000) at /git/FB-mysql-5.6/sql/sql_connect.cc:929
#7  0x00007fda0c63edc5 in start_thread (arg=0x7fda0cbed700) at pthread_create.c:308
#8  0x00007fda0a69121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7fda0cc92a80 (LWP 11697)):
+bt
#0  0x00007fda0a686bcd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000009a0b8c in handle_connections_sockets (admin=false) at /git/FB-mysql-5.6/sql/mysqld.cc:7137
#2  0x000000000099f1ff in handle_connections_sockets_all () at /git/FB-mysql-5.6/sql/mysqld.cc:5931
#3  0x000000000099fde9 in mysqld_main (argc=15, argv=0x7fda0805bcc0) at /git/FB-mysql-5.6/sql/mysqld.cc:6541
#4  0x0000000000995af0 in main (argc=15, argv=0x7fff529b6e68) at /git/FB-mysql-5.6/sql/main.cc:25
(gdb)
</pre>

**Comment by yoshinorim** [comment]
Thanks for the report! Verified in MyRocks, not in InnoDB.

**Comment by hermanlee** [comment]
I'll take a look at this one.

**Comment by hermanlee** [comment]
https://reviews.facebook.net/D52569
