### ISSUE TITLE
avg_row_length is reported as zero

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#138]
mysql> show table status like 'linktable'\G
**************************\* 1. row ***************************
           Name: linktable
         Engine: ROCKSDB
        Version: 10
     Row_format: Dynamic
           Rows: 7490883164
 Avg_row_length: 0
    Data_length: 142134708142
Max_data_length: 0
   Index_length: 167742645324
      Data_free: 0
 Auto_increment: NULL
    Create_time: NULL
    Update_time: NULL
     Check_time: NULL
      Collation: latin1_bin
       Checksum: NULL
 Create_options:
        Comment:
1 row in set (0.00 sec)

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D52851
