### ISSUE TITLE
handle_fatal_signal (sig=11) in Item_ref::used_tables when using --allow-document-type=1 and SELECT

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#139]
<pre>
+bt
#0  0x00007f8856f99741 in __pthread_kill (threadid=<optimized out>, signo=11) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:61
#1  0x0000000000e36e66 in my_write_core (sig=11) at /git/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000ab022c in handle_fatal_signal (sig=11) at /git/FB-mysql-5.6/sql/signal_handler.cc:239
#3  signal handler called
#4  0x00000000009ec7a1 in Item_ref::used_tables (this=0x7f884e85c890) at /git/FB-mysql-5.6/sql/item.h:3457
#5  0x0000000000af94df in setup_fields (thd=0x7f8852da9000, ref_pointer_array=..., fields=..., mark_used_columns=MARK_COLUMNS_READ, sum_func_list=0x7f884e85c698, allow_sum_func=true) at /git/FB-mysql-5.6/sql/sql_base.cc:8477
#6  0x0000000000b89910 in JOIN::prepare (this=0x7f884e85c450, tables_init=0x7f884e845518, wild_num=0, conds_init=0x0, og_num=0, order_init=0x0, group_init=0x0, having_init=0x0, select_lex_arg=0x7f884e844990, unit_arg=0x7f884e844ca0) at /git/FB-mysql-5.6/sql/sql_resolver.cc:168
#7  0x0000000000cd3b62 in subselect_single_select_engine::prepare (this=0x7f884e845ca8) at /git/FB-mysql-5.6/sql/item_subselect.cc:2640
#8  0x0000000000cccaad in Item_subselect::fix_fields (this=0x7f884e845b68, thd=0x7f8852da9000, ref=0x7f884e85c358) at /git/FB-mysql-5.6/sql/item_subselect.cc:381
#9  0x0000000000b89c39 in JOIN::prepare (this=0x7f884e85c010, tables_init=0x7f884e844270, wild_num=0, conds_init=0x0, og_num=1, order_init=0x0, group_init=0x7f884e844948, having_init=0x7f884e845b68, select_lex_arg=0x7f8852dac9d0, unit_arg=0x7f8852dac378) at /git/FB-mysql-5.6/sql/sql_resolver.cc:206
#10 0x0000000000b9137d in mysql_prepare_select (thd=0x7f8852da9000, tables=0x7f884e844270, wild_num=0, fields=..., conds=0x0, og_num=1, order=0x0, group=0x7f884e844948, having=0x7f884e845b68, select_options=2147748608, result=0x7f884e845da0, unit=0x7f8852dac378, select_lex=0x7f8852dac9d0, free_join=0x7f88575917e7) at /git/FB-mysql-5.6/sql/sql_select.cc:1087
#11 0x0000000000b91638 in mysql_select (thd=0x7f8852da9000, tables=0x7f884e844270, wild_num=0, fields=..., conds=0x0, order=0x7f8852dacb98, group=0x7f8852dacad0, having=0x7f884e845b68, select_options=2147748608, result=0x7f884e845da0, unit=0x7f8852dac378, select_lex=0x7f8852dac9d0) at /git/FB-mysql-5.6/sql/sql_select.cc:1210
#12 0x0000000000b8f865 in handle_select (thd=0x7f8852da9000, result=0x7f884e845da0, setup_tables_done_option=0) at /git/FB-mysql-5.6/sql/sql_select.cc:126
#13 0x0000000000b65da2 in execute_sqlcom_select (thd=0x7f8852da9000, all_tables=0x7f884e844270, last_timer=0x7f88575939a0) at /git/FB-mysql-5.6/sql/sql_parse.cc:5853
#14 0x0000000000b5e7d6 in mysql_execute_command (thd=0x7f8852da9000, statement_start_time=0x7f8857592938, post_parse=0x7f88575939a0) at /git/FB-mysql-5.6/sql/sql_parse.cc:3239
#15 0x0000000000b692ee in mysql_parse (thd=0x7f8852da9000, rawbuf=0x7f884e844010 "SELECT 1 FROM t1 AS t1_outer GROUP BY a HAVING (SELECT t1_outer.b FROM t1  AS t1_inner LIMIT 1)", length=95, parser_state=0x7f88575932f0, last_timer=0x7f88575939a0, async_commit=0x7f885759399f "") at /git/FB-mysql-5.6/sql/sql_parse.cc:7379
#16 0x0000000000b5a9e3 in dispatch_command (command=COM_QUERY, thd=0x7f8852da9000, packet=0x7f885117e001 "SELECT 1 FROM t1 AS t1_outer GROUP BY a HAVING (SELECT t1_outer.b FROM t1  AS t1_inner LIMIT 1)", packet_length=95) at /git/FB-mysql-5.6/sql/sql_parse.cc:1595
#17 0x0000000000b592a7 in do_command (thd=0x7f8852da9000) at /git/FB-mysql-5.6/sql/sql_parse.cc:1071
#18 0x0000000000b1f130 in do_handle_one_connection (thd_arg=0x7f8852da9000) at /git/FB-mysql-5.6/sql/sql_connect.cc:1071
#19 0x0000000000b1ea2f in handle_one_connection (arg=0x7f8852da9000) at /git/FB-mysql-5.6/sql/sql_connect.cc:929
#20 0x00007f8856f94dc5 in start_thread (arg=0x7f8857594700) at pthread_create.c:308
#21 0x00007f8854fe721d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Testcase:
DROP DATABASE test;CREATE DATABASE test;USE test;
CREATE TABLE t1 (a INT NOT NULL PRIMARY KEY AUTO_INCREMENT, b INT);
SELECT 1 FROM t1 AS t1_outer GROUP BY a HAVING (SELECT t1_outer.b FROM t1  AS t1_inner LIMIT 1);

Options used (note the required --allow-document-type=1):
--no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --skip-innodb-buffer-page --default-storage-engine=RocksDB --allow-document-type=1"

Version: '5.6.27-debug'  socket: '/sda/FB-12.01.16-mysql-5.6.27-linux-x86_64/socket.sock'  port: 11125  MySQL Community Server (GPL)
01:32:03 UTC - mysqld got signal 11 ;
...
Query (7f0856841010): SELECT 1 FROM t1 AS t1_outer GROUP BY a HAVING (SELECT t1_outer.b FROM t1  AS t1_inner LIMIT 1)
</pre>

**Comment by yoshinorim** [comment]
Thanks! Verified in both InnoDB and MyRocks.

**Comment by tianx** [comment]
Thank you @RoelVdP for reporting the bug. Fixing it in https://reviews.facebook.net/D52941.

**Comment by RoelVdP** [comment]
@tianx Great! Will you also log bug with InnoDB details for upstream?

**Comment by tianx** [comment]
@RoelVdP This is an FB-specific feature (allow-document-type), not from upstream.

**Comment by RoelVdP** [comment]
@tianx Ah, I was looking at "Verified in both InnoDB and MyRocks." - this is InnoDB in fb-mysql branch then?

**Comment by tianx** [comment]
@RoelVdP yes that's correct. thanks!
