### ISSUE TITLE
Better error handling on concurrent locking reads (Internal error: NotFound)

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#144]
Daniel reported this. We're discussing with Jay about how to fix. So far we've discussed:

The problem is that in rnd_next_with_direction(), between the call to Next() or Prev() and the call to GetForUpdate() the row seems to be deleted.   -- exactly written as commented.

```
        /*
          Lock the row we've just read.

          Now we call GetForUpdate which will 1) Take a lock and 2) Will fail
          if the row was deleted since the snapshot was taken.
        */
```

Currently MyRocks returns "Internal error: NotFound". This should be more friendly.

I think RC should get to the next row, and RR should return a better error.

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D53205
