### ISSUE TITLE
Too much mutex contention from register_snapshot & register_snapshot_release

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#145]
InnoDB gets about 10% more QPS than MyRocks for simple SELECT statement workload at high concurrency. Mutex contention in the MyRocks handler is the problem.

Another problem might be that recordTick is the 4th largest CPU consumer for MyRocks. I will open another task for that.

Workload: 
- sysbench doing auto-commit point select -> SELECT id, k, c, pad from sbtest5 where id=...
- 40 concurrent client threads, server has 48 HW threads (24 CPU cores)
- 8 sysbench clients are run each with 5 connections
- sysbench and mysqld share the server

Things to notice:
- I get about 10% more QPS with InnoDB versus MyRocks
- vmstat user cpu is about 4 points higher for InnoDB
- vmstat context switch rate is ~15% higher for RocksDB. This can mean mutex contention.
- from flat CPU profile MyRocks has mutex_delay as #2. This can mean mutex contention.

From hierarchical profile MyRocks has mutex contention at register_snapshot & register_snapshot_release. There is a data structure protected by a global mutex.
- can we support concurrent access to the data structure?
- is register_snapshot needed for autocommit SELECT statements?

Code is https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/ha_rocksdb.cc#L1082

vmstat for InnoDB 5.6.26

procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
47  0      0 162865488 3093744 51129668    0    0     0    12 54530 795160 66 21 13  0  0
47  0      0 162829840 3093744 51127416    0    0     0   148 53312 766692 67 21 11  0  0
46  0      0 162858848 3093744 51129764    0    0     0  8252 56485 731467 69 22  9  0  0
57  0      0 162836672 3093744 51129752    0    0     0     0 54394 752797 69 21 10  0  0
43  0      0 162845472 3093744 51129756    0    0     0     0 52700 764614 68 21 11  0  0

vmstat for MyRocks

procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
40  0      0 193814128 3292916 52000332    0    0    12     8 89295 830200 65 21 14  0  0
49  0      0 193807344 3292916 52000348    0    0     0     4 85975 897199 64 21 15  0  0
41  0      0 193785920 3292916 52000348    0    0     0     0 86782 827127 65 21 14  0  0
45  0      0 193781040 3292916 52000404    0    0     0    36 88300 879137 65 21 14  0  0
46  0      0 193776848 3292916 52000396    0    0     0   204 91215 847365 64 21 14  0  0

sysbench throughput sample for InnoDB 5.6.26

[1453357967] min: 0.07  avg: 0.1288  max: 6.5342  percentile: 0.0001  throughput: 38484.20  requests: 384842  interval_secs: 10 sum_secs: 50  threads: 5
[1453357977] min: 0.07  avg: 0.1308  max: 6.5342  percentile: 0.0001  throughput: 37902.40  requests: 379024  interval_secs: 10 sum_secs: 50  threads: 5
[1453357987] min: 0.07  avg: 0.1303  max: 10.7621  percentile: 0.0001  throughput: 38032.70  requests: 380327  interval_secs: 10 sum_secs: 50  threads: 5
[1453357997] min: 0.07  avg: 0.1270  max: 10.7621  percentile: 0.0001  throughput: 39007.60  requests: 390076  interval_secs: 10 sum_secs: 50  threads: 5

sysbench throughput sample for Myrocks

[1453357973] min: 0.07  avg: 0.1427  max: 8.5941  percentile: 0.0001  throughput: 34762.20  requests: 347622  interval_secs: 10 sum_secs: 50  threads: 5
[1453357983] min: 0.07  avg: 0.1408  max: 8.8463  percentile: 0.0001  throughput: 35235.00  requests: 352350  interval_secs: 10 sum_secs: 50  threads: 5
[1453357993] min: 0.07  avg: 0.1405  max: 8.8463  percentile: 0.0001  throughput: 35312.90  requests: 353129  interval_secs: 10 sum_secs: 50  threads: 5
[1453358003] min: 0.07  avg: 0.1412  max: 6.1589  percentile: 0.0001  throughput: 35123.70  requests: 351237  interval_secs: 10 sum_secs: 50  threads: 5

flat profile for InnoDB 5.6.26

```
 6.05%  mysqld   mysqld               [.] MYSQLparse
 1.86%  mysqld   libc-2.17.so         [.] __memcpy_ssse3_back
 1.28%  mysqld   mysqld               [.] rec_get_offsets_func
 1.09%  mysqld   mysqld               [.] page_cur_search_with_match
 1.09%  mysqld   mysqld               [.] buf_page_get_gen
 1.05%  mysqld   mysqld               [.] lex_one_token
 0.95%  mysqld   mysqld               [.] btr_cur_search_to_nth_level
 0.85%  mysqld   mysqld               [.] dispatch_command
 0.84%  mysqld   mysqld               [.] alloc_root
 0.83%  mysqld   mysqld               [.] row_search_mvcc
 0.80%  mysqld   mysqld               [.] cmp_dtuple_rec_with_match_low
 0.75%  mysqld   mysqld               [.] my_hash_sort_bin
 0.72%  mysqld   libpthread-2.17.so   [.] pthread_getspecific
 0.67%  mysqld   libpthread-2.17.so   [.] __libc_recv
 0.65%  mysqld   mysqld               [.] JOIN::optimize
 0.61%  mysqld   mysqld               [.] buf_page_hash_get_low
 0.61%  mysqld   [kernel.kallsyms]    [k] fget_light
 0.60%  mysqld   mysqld               [.] build_template_field
 0.57%  mysqld   mysqld               [.] Lex_hash::get_hash_symbol
 0.57%  mysqld   mysqld               [.] malloc
 0.56%  mysqld   libpthread-2.17.so   [.] pthread_mutex_lock
 0.54%  mysqld   mysqld               [.] Protocol_classic::net_store_data
 0.53%  mysqld   mysqld               [.] pfs_start_stage_v1
 0.52%  mysqld   libc-2.17.so         [.] __memset_sse2
 0.50%  mysqld   mysqld               [.] JOIN::make_join_plan
```

flat profile for MyRocks

```
 4.33%  my-oneconnectio  mysqld               [.] MYSQLparse
 2.90%  my-oneconnectio  mysqld               [.] mutex_delay
 1.70%  my-oneconnectio  libpthread-2.17.so   [.] pthread_mutex_unlock
 1.62%  my-oneconnectio  libc-2.17.so         [.] __memcpy_ssse3_back
 1.34%  my-oneconnectio  libpthread-2.17.so   [.] pthread_mutex_lock
 1.26%  my-oneconnectio  mysqld               [.] rocksdb::StatisticsImpl::recordTick
 1.15%  my-oneconnectio  [kernel.kallsyms]    [k] _raw_spin_lock
 1.07%  my-oneconnectio  mysqld               [.] rocksdb::(anonymous namespace)::ShardedLRUCache::Lookup
 1.01%  my-oneconnectio  mysqld               [.] make_join_statistics
 1.01%  my-oneconnectio  mysqld               [.] lex_one_token
 0.96%  my-oneconnectio  mysqld               [.] malloc
 0.93%  my-oneconnectio  mysqld               [.] free
 0.85%  my-oneconnectio  mysqld               [.] rocksdb::BlockIter::BinarySeek
 0.85%  my-oneconnectio  mysqld               [.] dispatch_command
 0.74%  my-oneconnectio  mysqld               [.] rocksdb::Version::Get
 0.72%  my-oneconnectio  libc-2.17.so         [.] __memset_sse2
 0.71%  my-oneconnectio  libpthread-2.17.so   [.] pthread_mutex_trylock
 0.67%  my-oneconnectio  mysqld               [.] JOIN::optimize
 0.67%  my-oneconnectio  mysqld               [.] my_pthread_fastmutex_lock
 0.63%  my-oneconnectio  mysqld               [.] alloc_root
 0.62%  my-oneconnectio  mysqld               [.] rocksdb::BlockIter::ParseNextKey
 0.60%  my-oneconnectio  libc-2.17.so         [.] __memcmp_sse4_1
 0.57%  my-oneconnectio  libpthread-2.17.so   [.] __libc_recv
 0.56%  my-oneconnectio  mysqld               [.] mysql_execute_command
 0.53%  my-oneconnectio  mysqld               [.] find_keyword
 0.51%  my-oneconnectio  mysqld               [.] Item::Item
```

call graph profile for MyRocks

```
        ---mutex_delay
           |          
           |--51.99%-- register_snapshot_release
           |          ha_rocksdb::external_lock
           |          handler::ha_external_lock
           |          unlock_external
           |          mysql_unlock_tables
           |          JOIN::optimize
           |          mysql_select
           |          handle_select
           |          execute_sqlcom_select
           |          mysql_execute_command
           |          mysql_parse
           |          dispatch_command
           |          do_handle_one_connection
           |          handle_one_connection
           |          start_thread
           |          __clone
           |          
           |--46.19%-- register_snapshot
           |          ha_rocksdb::index_init
           |          handler::index_read_idx_map
           |          join_read_const
           |          join_read_const_table
           |          make_join_statistics
           |          JOIN::optimize
           |          mysql_select
           |          handle_select
           |          execute_sqlcom_select
           |          mysql_execute_command
           |          mysql_parse
           |          dispatch_command
           |          do_handle_one_connection
           |          handle_one_connection
           |          start_thread
           |          __clone
           |          
           |--0.73%-- open_table
           |          open_tables
           |          open_normal_and_derived_tables
           |          execute_sqlcom_select
           |          mysql_execute_command
           |          mysql_parse
           |          dispatch_command
           |          do_handle_one_connection
           |          handle_one_connection
           |          start_thread
           |          __clone
           |          
           |--0.51%-- close_thread_table
           |          close_thread_tables
           |          mysql_execute_command
           |          mysql_parse
           |          dispatch_command
           |          do_handle_one_connection
           |          handle_one_connection
           |          start_thread
           |          __clone
            --0.58%-- [...]
```

**Comment by mdcallag** [comment]
The snapshot map is used by this code. I wonder if I asked for that monitoring feature?
  std::string status =
    "\n============================================================\n" +
    get_timestamp_as_string() +
    " ROCKSDB TRANSACTION MONITOR OUTPUT\n"
    "============================================================\n"
    "---------\n"
    "SNAPSHOTS\n"
    "---------\n"
    "LIST OF SNAPSHOTS FOR EACH SESSION:\n";

  mysql_mutex_lock(&snapshot_mutex);

**Comment by jkedgar** [comment]
Yes you did.  It was one of the first features I implemented here.  I originally wanted to include the information in the RocksDB snapshot table but got pushback from that, so I ended up using our own table in MyRocks and having a mutex on it.  I'll be revisiting this code to see if there is a more efficient way to do it as soon as I can get to it.

**Comment by jkedgar** [comment]
What options are you using when running sysbench?

**Comment by mdcallag** [comment]
Will share more data and details later today. Can even loan you a host
setup with my sysbench binary.

On Fri, Jan 22, 2016 at 12:14 PM, Jay Edgar notifications@github.com
wrote:

> What options are you using when running sysbench?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/145#issuecomment-174034289.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Thanks.  If by "host setup" you mean a machine - that might be more difficult for me.  I'll probably find it easiest to work on my devserver.  I have some ideas on fixing this, but I'd like to get a baseline value on my machine so I can see if my changes improve things or not.

**Comment by mdcallag** [comment]
You can still use my sysbench binary. It runs on devservers too and
building it would be a hassle for you.

On Fri, Jan 22, 2016 at 12:23 PM, Jay Edgar notifications@github.com
wrote:

> Thanks. If by "host setup" you mean a machine - that might be more
> difficult for me. I'll probably find it easiest to work on my devserver. I
> have some ideas on fixing this, but I'd like to get a baseline value on my
> machine so I can see if my changes improve things or not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/145#issuecomment-174036522.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Sure.  Thanks.

**Comment by mdcallag** [comment]
For MySQL 5.6 I get up to ~15% more QPS from InnoDB than RocksDB at high concurrency. We might be able to remove some of the overhead.

I show the impact from two sources of over here. 
1) RocksDB statistics enabled by https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/ha_rocksdb.cc#L2278
2) register_snapshot as described early in this thread

While I provided data for #1 and #2 above this issue is only open for #2. We can reuse the results later to consider reducing the RocksDB stats overhead in a separate issue.

I ran my modified version of sysbench 0.4 for two workloads. I can share the binary offline. For each workload I ran sysbench for 8, 16, 24, 32, 40 and 48 concurrent clients. I forked 8 sysbench client processes so each process used 1, 2, 3, 4 & 5 connections. There was a separate table per sysbench process.

The test server has 24-cores and 48 HW threads. sysbench and mysqld share the host.

The nicknames for the workloads are:
- siac -> each query is an auto-commit select statement that fetches all columns for one row by PK
- ro -> each "query" is a read only transaction with 5 statements. 

Example transaction for the "ro" workload:
BEGIN
SELECT c from sbtest1 where id=146360
SELECT c from sbtest1 where id between 892051 and 892060 order by id desc
SELECT SUM(K) from sbtest1 where id between 810736 and 810745
SELECT c from sbtest1 where id between 50221 and 50230 order by c
SELECT DISTINCT c from sbtest1 where id between 622580 and 622590 order by c
COMMIT

I have results for several configurations:
- myrocks.orig - FB MySQL as of several weeks ago
- myrocks.nostat - like myrocks.orig but RocksDB statistics disabled
- myrocks.nosnap - like myrocks.orig but register_snapshot disabled
- myrocks.nostat.nosnap - ... but RocksDB stats and register_snapshot disabled
- innodb.56 - upstream MySQL 5.6.26 with InnoDB
- innodb.57 - upstream MySQL 5.7.10 with InnoDB

In the data below QPS/TPS gets better from disabling both 

QPS for siac, concurrent clients from 8 to 48

```
8       16      24      32      40      48      #clients/engine
 95422  162030  217378  241171  261795  273319  myrocks.orig
 95757  164156  221438  248450  275937  297532  myrocks.nostat
102540  171691  230282  258934  285763  309011  myrocks.nosnap
103232  176189  236986  269222  298416  326495  myrocks.nostat.nosnap
118994  199652  264233  295112  326769  353731  innodb.5626
102471  182979  245469  276110  308780  338392  innodb.57
```

TPS for ro workload, concurrent clients from 8 to 48

```
8       16      24      32      40      48      engine
5302     9054   11989   13460   15030   16285   myrocks.orig
5345     9208   12255   13998   15588   16952   myrocks.nostat
5972     9987   13522   15478   17300   19095   myrocks.nosnap
6083    10188   13810   16000   17768   19574   myrocks.nostat.nosnap
7069    11710   15395   17631   19838   21607   innodb.5626 
6288    10583   13888   15866   18040   19955   innodb.57
```

**Comment by mdcallag** [comment]
To run, first prepare tables

for tid in $( seq 1 8 ) ; do

e=rocksdb
./sysbench --batch --batch-delay=10 --test=oltp --mysql-host=127.0.0.1 --mysql-user=root --mysql-password=pw --mysql-db=test --oltp-table-size=1000000 --max-time=600 --max-requests=0 --mysql-table-engine=$e --db-ps-mode=disable --mysql-engine-trx=yes --oltp-table-name=sbtest${tid} --oltp-read-only --oltp-skip-trx --oltp-test-mode=simple --oltp-point-select-all-cols --oltp-dist-type=uniform --oltp-range-size=10 --mysql-create-options=key_block_size=4 --oltp-connect-delay=0 --percentile=99 --num-threads=5 --seed-rng=1453329058 prepare

done

---

Then run for siac workload

for tid in $( seq 1 8 ) ; do

e=rocksdb
./sysbench --batch --batch-delay=10 --test=oltp --mysql-host=127.0.0.1 --mysql-user=root --mysql-password=pw --mysql-db=test --oltp-table-size=1000000 --max-time=600 --max-requests=0 --mysql-table-engine=$e --db-ps-mode=disable --mysql-engine-trx=yes --oltp-table-name=sbtest${tid} --oltp-read-only --oltp-skip-trx --oltp-test-mode=simple --oltp-point-select-all-cols --oltp-dist-type=uniform --oltp-range-size=10 --mysql-create-options=key_block_size=4 --oltp-connect-delay=0 --percentile=99 --num-threads=5 --seed-rng=1453329058 run &

done

Then wait for clients forked above to finish

---

Then run for ro workload

for tid in $( seq 1 8 ) ; do

e=rocksdb
./sysbench --batch --batch-delay=10 --test=oltp --mysql-host=127.0.0.1 --mysql-user=root --mysql-password=pw --mysql-db=test --oltp-table-size=1000000 --max-time=600 --max-requests=0 --mysql-table-engine=$e --db-ps-mode=disable --mysql-engine-trx=yes --oltp-table-name=sbtest${tid} --oltp-read-only --oltp-dist-type=uniform --oltp-range-size=10 --mysql-create-options=key_block_size=4 --oltp-connect-delay=0 --percentile=99 --num-threads=5 --seed-rng=1453331005 run &

done

Then wait for clients forked above to finish

---

**Comment by mdcallag** [comment]
This confirms the query plans are the same between MyRocks and InnoDB

bin/mysql -uroot -ppw test -e 'explain SELECT c from sbtest1 where id=146360'
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref   | rows | Extra |
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------+
|  1 | SIMPLE      | sbtest1 | const | PRIMARY       | PRIMARY | 4       | const |    1 | NULL  |
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------+

+----+-------------+---------+------------+-------+---------------+---------+---------+-------+------+----------+-------+
| id | select_type | table   | partitions | type  | possible_keys | key     | key_len | ref   | rows | filtered | Extra |
+----+-------------+---------+------------+-------+---------------+---------+---------+-------+------+----------+-------+
|  1 | SIMPLE      | sbtest1 | NULL       | const | PRIMARY       | PRIMARY | 4       | const |    1 |   100.00 | NULL  |
+----+-------------+---------+------------+-------+---------------+---------+---------+-------+------+----------+-------+

bin/mysql -uroot -ppw test -e 'explain SELECT c from sbtest1 where id between 892051 and 892060 order by id desc'
+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref  | rows | Extra       |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+
|  1 | SIMPLE      | sbtest1 | range | PRIMARY       | PRIMARY | 4       | NULL |    1 | Using where |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+

+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+
| id | select_type | table   | partitions | type  | possible_keys | key     | key_len | ref  | rows | filtered | Extra       |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | sbtest1 | NULL       | range | PRIMARY       | PRIMARY | 4       | NULL |   10 |   100.00 | Using where |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+

bin/mysql -uroot -ppw test -e 'explain SELECT SUM(K) from sbtest1 where id between 810736 and 810745'

+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref  | rows | Extra       |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+
|  1 | SIMPLE      | sbtest1 | range | PRIMARY       | PRIMARY | 4       | NULL |   40 | Using where |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-------------+

+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+
| id | select_type | table   | partitions | type  | possible_keys | key     | key_len | ref  | rows | filtered | Extra       |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | sbtest1 | NULL       | range | PRIMARY       | PRIMARY | 4       | NULL |   10 |   100.00 | Using where |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-------------+

bin/mysql -uroot -ppw test -e 'explain SELECT c from sbtest1 where id between 50221 and 50230 order by c'
+----+-------------+---------+-------+---------------+---------+---------+------+------+-----------------------------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref  | rows | Extra                       |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-----------------------------+
|  1 | SIMPLE      | sbtest1 | range | PRIMARY       | PRIMARY | 4       | NULL |   40 | Using where; Using filesort |
+----+-------------+---------+-------+---------------+---------+---------+------+------+-----------------------------+

+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-----------------------------+
| id | select_type | table   | partitions | type  | possible_keys | key     | key_len | ref  | rows | filtered | Extra                       |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-----------------------------+
|  1 | SIMPLE      | sbtest1 | NULL       | range | PRIMARY       | PRIMARY | 4       | NULL |   10 |   100.00 | Using where; Using filesort |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+-----------------------------+

bin/mysql -uroot -ppw test -e 'explain SELECT DISTINCT c from sbtest1 where id between 622580 and 622590 order by c'
+----+-------------+---------+-------+---------------+---------+---------+------+------+----------------------------------------------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref  | rows | Extra                                        |
+----+-------------+---------+-------+---------------+---------+---------+------+------+----------------------------------------------+
|  1 | SIMPLE      | sbtest1 | range | PRIMARY       | PRIMARY | 4       | NULL |   40 | Using where; Using temporary; Using filesort |
+----+-------------+---------+-------+---------------+---------+---------+------+------+----------------------------------------------+

+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+----------------------------------------------+
| id | select_type | table   | partitions | type  | possible_keys | key     | key_len | ref  | rows | filtered | Extra                                        |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+----------------------------------------------+
|  1 | SIMPLE      | sbtest1 | NULL       | range | PRIMARY       | PRIMARY | 4       | NULL |   11 |   100.00 | Using where; Using temporary; Using filesort |
+----+-------------+---------+------------+-------+---------------+---------+---------+------+------+----------+----------------------------------------------+

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D53463 is out for review
