### ISSUE TITLE
ADD_SUBDIRECTORY(unittest) needs to be removed for certain build configurations to succeed

### ISSUE THREAD

**Issue by zhaiwx1987** [facebook/mysql-5.6#147]
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Ubuntu 15.04

Follow the build step described here : https://github.com/facebook/mysql-5.6/wiki/Build-Steps
And got the following error while executing cmake
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DCMAKE_INSTALL_PREFIX="/u01/my56"

storage/rocksdb/unittest/CMakeFiles/test_properties_collector.dir/build.make:92: recipe for target 'storage/rocksdb/unittest/test_properties_collector' failed
make[2]: **\* [storage/rocksdb/unittest/test_properties_collector] Error 1
CMakeFiles/Makefile2:603: recipe for target 'storage/rocksdb/unittest/CMakeFiles/test_properties_collector.dir/all' failed
make[1]: **\* [storage/rocksdb/unittest/CMakeFiles/test_properties_collector.dir/all] Error 2

I don't know how to solve this problem ,so I  comment out "ADD_SUBDIRECTORY(unittest)" in "storage/rocksdb/CMakeLists.txt". Then run cmake && make without any error. But failed to install the it with the error messge:
2016-01-21 12:45:29 31588 [ERROR] Unknown/unsupported storage engine: rocksdb
2016-01-21 12:45:29 31588 [ERROR] Aborting

From the output of "nm mysqld | grep rocksdb", it seems rocksdb has already been built in mysqld.    

Any suggestion ? 

my.cnf
[mysqld]
default-storage-engine=rocksdb
skip-innodb
default-tmp-storage-engine=MyISAM

basedir=/u01/my56
datadir=/u01/my56/data
tmpdir=/u01/my56/tmp
lc_messages_dir=/u01/my56/share
log-error=/u01/my56/log/alert.log
slow_query_log_file=/u01/my56/log/slow.log
general_log_file=/u01/my56/log/general.log
socket=/u01/my56/run/mysql.sock
core-file
# binlog

log-bin=/u01/my56/log/mysql-bin
max_binlog_size=100M
binlog-format=ROW
# server

port=3306

**Comment by mdcallag** [comment]
Builds without problem on Fedora 19 host, will try ubuntu next.

$ cat /etc/redhat-release 
Fedora release 19 (Schrödinger’s Cat)
$ cat /etc/fedora-release 
Fedora release 19 (Schrödinger’s Cat)

Followed the steps at https://github.com/facebook/mysql-5.6/wiki/Build-Steps

**Comment by mdcallag** [comment]
Followed steps without problems for Ubuntu 14.04 LTS. I don't have a more recent Ubuntu release as I stay on LTS.

**Comment by yoshinorim** [comment]
You need to add "rocksdb" in [mysqld] section.

**Comment by zhaiwx1987** [comment]
Oh, yes, I missed it! Thank you !!! :)  Now I only need to comment out  unittest of rockdb and everything works well.

**Comment by jkedgar** [comment]
Can this issue be closed now?

**Comment by valeriikravchuk** [comment]
I've got the same problem with unittest on Ubuntu 14.04. It wants to link with -lmysqlserver. I wonder why and how this library is supposed to be installed.

**Comment by gunnarku** [comment]
@valeriikravchuk: you can try using `VERBOSE=1 make` to debug this. This will result in a more detailed build log than the default output and will help you to see what paths are used to compile and link.

For the record, with Ubuntu 15.10 and default instructions I can build _Debug_, _RelWithDebInfo_, and _Release_ builds without any problems. Here's the data about the system I'm using:

```
$ g++ --version | grep g++
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
$ uname -a
Linux hostname 4.2.0-27-generic #32-Ubuntu SMP ...
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
```

Let us know how this goes.

**Comment by valeriikravchuk** [comment]
I had not problem to build from current source today (git log shows last commit dated Feb. 12) on the same Ubuntu 14.04.03 I've used 12 days ago.

**Comment by gunnarku** [comment]
Thank you for the confirmation! Based on that I'm closing this issue because it looks like the issue has been resolved. If you'll encounter any other problems then please let us know and we'll help to debug.

**Comment by valeriikravchuk** [comment]
I've got the same problem again today with recent code (cloned today) on Fedora Core 23. Had to comment out ADD_SUBDIRECTORY(unittest) in storage/rocksdb/CMakeLists.txt to proceed.

**Comment by gunnarku** [comment]
Re-activating because the problem still happens.

**Comment by gunnarku** [comment]
Fix known. Will most likely push on Monday (04/04/2016).

**Comment by gunnarku** [comment]
https://reviews.facebook.net/D56283
