### ISSUE TITLE
Documentation for Vector Support

### ISSUE THREAD

**Issue by imdxz** [facebook/mysql-5.6#1495]
MyRocks DB currently supports vector data via FAISS library, which is a valuable feature for many users. However, there is currently no documentation available for this functionality and users can only look for examles in the `fb_vectordb` test suite.  

I kindly request the creation of documentation for MyRocks DB's vector data support. This documentation may include:

- Overview of vector data support in MyRocks DB
- Installation and setup instructions (if any additional steps are required)
- Basic usage examples
- API reference for vector data-related functions and commands
- Best practices for working with vector data in MyRocks DB
- Performance considerations and optimization tips
- Limitations and known issues (if any)

**Comment by bladepan** [comment]
added page https://github.com/facebook/mysql-5.6/wiki/Vector-Database. thanks for the suggestion.

**Comment by imdxz** [comment]
@bladepan Hi, may I ask is there any plan to support HNSW index for MyRocks?

**Comment by bladepan** [comment]
no, there is no plan for HNSW index.

**Comment by imdxz** [comment]
May I ask the reason behind it? Is it too complicated or just not needed? 
I'm interested in implementing this feature.

> no, there is no plan for HNSW index.

**Comment by bladepan** [comment]
There is no internal user asking for this feature. We haven't evaluated NHSW, so I do not know how complex it would be.

**Comment by imdxz** [comment]
I see, thanks!
