### ISSUE TITLE
innochecksum fails on compressed tables with key_block_size=16

### ISSUE THREAD

**Issue by laurynas-biveinis** [facebook/mysql-5.6#15]
Running innochecksum on key_block_size=16 compressed table results in

InnoDB offline file checksum utility.
Table is uncompressed
Page size is 16384
Fail; page 0 invalid (fails log sequence number check)

This is a regression from the same patch in Facebook 5.1 branch and is caused by https://github.com/facebook/mysql-5.6/commit/5bd426922c022169ff1f3438f73660543e919067 assuming that table is compressed iff physical page size == logical page size.

I'll submit a PR shortly

**Comment by jtolmer** [comment]
In case this affects your interest in attempting to fix the problem and submit a pull request, Facebook MySQL engineering has stopped investing in improvements to InnoDB compression and are considering removing our compression commits next time we rebase to an upstream MySQL 5.6 point release (5.6.24 or 5.6.25).

**Comment by laurynas-biveinis** [comment]
Doesn't affect my plans; I have ported 5bd4269 to Percona Server where we need the feature, and I have the fix already

**Comment by laurynas-biveinis** [comment]
I don't know how to make a pull request from a mysql/mysql-server fork to your repo even if I took the right base branch etc. Given what Justin wrote, I'll stop there, here's the commit, which you can consider as a pull request if interested: 

https://github.com/laurynas-biveinis/percona-server/commit/2ba305a66be04575083ea26d9905b218f5797a7e

**Comment by jtolmer** [comment]
Thank you for providing a link to the fix. I will determine whether to incorporate it when I look more in depth about removing our compression diffs in the next rebase.

**Comment by jtolmer** [comment]
Laurynas, I was planning to pick up your proposed change, but it doesn't look to me like you've signed our CLA, https://code.facebook.com/cla. Would you be willing to do so?

Cheers,

Justin

**Comment by laurynas-biveinis** [comment]
Done

**Comment by jtolmer** [comment]
I just pushed webscalesql-5.6.24.97. In that branch, I incorporated your changes and squashed it with the commit you identified as introducing the problem. See https://github.com/facebook/mysql-5.6/commit/750dd658.

FYI: I had to stabilize the new tests you added by adding --force-restart to the opt files and --source include/have_innodb_16k.inc to the .test files.
