### ISSUE TITLE
can we remove strcmp from update_row_stats

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#151]
update_row_stats shows up in the top-10 functions by CPU consumption for sysbench. 

update_row_stats has several calls to strcmp and this can be called per row operation. I don't think we needed strcmp in the InnoDB version. Can we avoid using it for MyRocks?

https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/ha_rocksdb.cc#L69

It came from:
commit bf17c6d078fca5784da9b5c7b0cf000ac216a48d
Author: Santosh Praneeth Banda santoshb@fb.com
Date:   Thu Oct 29 15:55:24 2015 -0700

```
Add rocksdb_rows_read/inserted/deleted/updated status variables

Summary:
rocksdb_rows_read/inserted/deleted/updated status variables are added
to global status. The row operations on system databases can be misleading. So add
equivalent rocksdb_system_rows* status variables (see https://bugs.mysql.com/bug.php?id=68220).
```

**Comment by jkedgar** [comment]
Here is the current code:

```
  DBUG_ASSERT(type < ROWS_MAX);
  // Find if we are modifying system databases.
  if (table->s && (!strcmp(table->s->db.str, "mysql") ||
      !strcmp(table->s->db.str, "performance_schema") ||
      !strcmp(table->s->db.str, "information_schema"))) {
      global_stats.system_rows[type].inc();
  } else {
      global_stats.rows[type].inc();
  }
```

Are you thinking something like this?

```
bool is_system_database(const char *dbname)
{
  if (dbname[0] == 'm' && dbname[1] == 'y' && strcmp(dbname, "mysql") == 0)
    return true;

  if (dbname[0] == 'p' && dbname[1] == 'e' && strcmp(dbname, "performance_schema") == 0)
    return true;

  if (dbname[0] == 'i' && dbname[1] == 'n' && strcmp(dbname, "information_schema") == 0)
    return true;

  return false;
}

...

  DBUG_ASSERT(type < ROWS_MAX);
  // Find if we are modifying system databases.
  if (table->s && is_system_database(table->s->db.str)) {
      global_stats.system_rows[type].inc();
  } else {
      global_stats.rows[type].inc();
  }
```

Or are you thinking we shouldn't differentiate between system stats and user stats?

**Comment by jkedgar** [comment]
I suppose it would be even better to have a field in `table` that we could assign when the TABLE object is created that would indicate whether it was in a system database or not and then we could simply check this field here.

**Comment by mdcallag** [comment]
I'd like the solution to avoid calls to strcmp. This can be an extremely
frequent operation since it is called per row

On Wed, Jan 27, 2016 at 12:02 PM, Jay Edgar notifications@github.com
wrote:

> Here is the current code:
> 
> DBUG_ASSERT(type < ROWS_MAX);
> // Find if we are modifying system databases.
> if (table->s && (!strcmp(table->s->db.str, "mysql") ||
> !strcmp(table->s->db.str, "performance_schema") ||
> !strcmp(table->s->db.str, "information_schema"))) {
> global_stats.system_rows[type].inc();
> } else {
> global_stats.rows[type].inc();
> }
> 
> Are you thinking something like this?
> 
> `
> bool is_system_database(const char *dbname)
> {
> if (dbname[0] == 'm' && dbname[1] == 'y' && strcmp(dbname, "mysql") == 0)
> return true;
> 
> if (dbname[0] == 'p' && dbname[1] == 'e' && strcmp(dbname,
> "performance_schema") == 0)
> return true;
> 
> if (dbname[0] == 'i' && dbname[1] == 'n' && strcmp(dbname,
> "information_schema") == 0)
> return true;
> 
> return false;
> }
> 
> ...
> 
> DBUG_ASSERT(type < ROWS_MAX);
> // Find if we are modifying system databases.
> if (table->s && is_system_database(table->s->db.str)) {
> global_stats.system_rows[type].inc();
> } else {
> global_stats.rows[type].inc();
> }
> `
> 
> Or are you thinking we shouldn't differentiate between system stats and
> user stats?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/151#issuecomment-175826085.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D53547
