### ISSUE TITLE
rdb_perf_context_stop is expensive

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#152]
This is the 6th largest source of CPU time from a sysbench test. Can we make it cheaper by reducing the number of counters tracked here - https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/rdb_perf_context.cc#L29

The code is here -> https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/rdb_perf_context.cc#L194

See this for the CPU profile - https://github.com/facebook/mysql-5.6/issues/150#issuecomment-175834238

**Comment by hermanlee** [comment]
There is a setting to disable collecting perf context stats, but it looks like it still loops through all of the counters to look for differences, so some cpu is still used there. I can put in a change to skip all stats collection when perf_context is disabled. The default perf_context setting collects counters from rocksdb.

Would it be acceptable to disable perf_context collection for performance test runs? This will probably be the default setting in the future, but for now, the setting is set to collect statistics for development/testing.

**Comment by mdcallag** [comment]
Disabling without looping sounds like a great first step and then we can wait to see if another step is required

**Comment by hermanlee** [comment]
Resolved in https://reviews.facebook.net/D53481. To disable perf_context collection: "set global rocksdb_perf_context_level = 0". The default is currently set to 1.
