### ISSUE TITLE
support new configuration options: compaction_pri, allow_concurrent_memtable_write, enable_write_thread_adaptive_yield

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#154]
grep compaction_pri data/.rocksdb/LOG
2016/01/29-10:40:35.319661 7fb3a3f6b9c0                           Options.compaction_pri: 0

grep allow_concur data/.rocksdb/LOG
2016/01/29-10:40:35.319485 7fb3a3f6b9c0          Options.allow_concurrent_memtable_write: 1

grep enable_write data/.rocksdb/LOG
2016/01/29-10:40:35.319486 7fb3a3f6b9c0       Options.enable_write_thread_adaptive_yield: 1

**Comment by yoshinorim** [comment]
I'm going to write a diff to add base_compaction_threads parameter to support adaptive compaction concurrency. I'll add these DB options too.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D53601 added allow_concurrent_memtable_write and enable_write_thread_adaptive_yield. compaction_pri is CF option so you can add via rocksdb_default_cf_options.
