### ISSUE TITLE
crash with concurrent memtable enabled

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#155]
This crash happens immediately after starting the linkbench load with loaders=40. This doesn't happen with loaders=1. I disabled the nodetable load via generate_nodes=false in the config/LinkConfigMysql.properties file.

Concurrent memtable support was enabled by these parameters hardwired in the build:
Options.enable_write_thread_adaptive_yield: 1
Options.allow_concurrent_memtable_write: 1

The properties file also has mysql_bulk_insert_batch = 1024

mysqld: /home/mcallaghan/mysql2/5.6/rocksdb/db/db_impl.cc:4407: rocksdb::Status rocksdb::DBImpl::WriteImpl(const rocksdb::WriteOptions&, rocksdb::WriteBatch_, rocksdb::WriteCallback_): Assertion `last_writer->sequence == last_sequence' failed.
05:42:31 UTC - mysqld got signal 6 ;

MySQL 5.6 was built with MySQL at:
commit 1c7af8056332066477a3afcdde7679f1375109f0
Author: Gunnar Kudrjavets gunnarku@fb.com
Date:   Fri Jan 29 10:05:16 2016 -0800
    Remove unnecessary checks before releasing resources

And RocksDB at:
commit 94918ae84bec80c9aca7b03e14b2d0f2ddb76123
Author: sdong siying.d@fb.com
Date:   Fri Jan 15 14:13:08 2016 -0800
    db_bench: explicitly clear buffer in compress benchmark

I enabled the general log and there are 742 INSERT statements prior to the crash

**Comment by nbronson** [comment]
I haven't had time yet to get LinkBench running locally to test the fix, but I was able to reproduce the same assert using db_bench and fix that problem: https://reviews.facebook.net/D53595

**Comment by mdcallag** [comment]
Applied that change, new crash

```
2016-02-01 09:21:37 571636 [Note] /data/mysql/myrocks/libexec/mysqld: ready for connections.
Version: '5.6.27-fb-log'  socket: '/data/mysql/myrocks/var/mysql.sock'  port: 3306  mysql-5.6.27.not_packaged.mcallaghan
2016-02-01 09:21:50 571636 [Note] RocksDB: Begin filtering dropped index (2,260)
2016-02-01 09:21:50 571636 [Note] RocksDB: Begin filtering dropped index (3,261)
2016-02-01 09:21:50 571636 [Note] RocksDB: Begin filtering dropped index (4,262)
2016-02-01 09:21:50 571636 [Note] RocksDB: Finished filtering dropped index (3,261)
2016-02-01 09:21:50 571636 [Note] RocksDB: Finished filtering dropped index (2,260)
2016-02-01 09:21:50 571636 [Note] RocksDB: Begin filtering dropped index (5,263)
2016-02-01 09:21:50 571636 [Note] RocksDB: Finished filtering dropped index (5,263)
2016-02-01 09:21:50 571636 [Note] RocksDB: Finished filtering dropped index (4,262)
mysqld: /home/mcallaghan/mysql2/5.6/rocksdb/db/inlineskiplist.h:580: void rocksdb::InlineSkipList<Comparator>::FindLevelSplice(const char*, rocksdb::InlineSkipList<Comparator>::Node*, rocksdb::InlineSkipList<Comparator>::Node*, int, rocksdb::InlineSkipList<Comparator>::Node**, rocksdb::InlineSkipList<Comparator>::Node**) [with Comparator = const rocksdb::MemTableRep::KeyComparator&]: Assertion `before == head_ || next == nullptr || KeyIsAfterNode(next->Key(), before)' failed.
17:21:54 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.
```

MyRocks is at this diff before applying your patch:

```
commit 94918ae84bec80c9aca7b03e14b2d0f2ddb76123
Author: sdong <siying.d@fb.com>
Date:   Fri Jan 15 14:13:08 2016 -0800

    db_bench: explicitly clear buffer in compress benchmark
```

**Comment by nbronson** [comment]
fix += https://reviews.facebook.net/D53751
