### ISSUE TITLE
improve error message for rocksdb_skip_unique_check

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#156]
I don't understand what statements are disabled in this error message after I set rocksdb_skip_unique_check=1. Which of the following are not allowed?
- INSERT
- REPLACE
- INSERT ... ON DUPLICATE KEY UPDATE

ERROR 2016-01-29 19:22:29,205 [Thread-29]: SQLException thrown by MySQL driver during execution of operation: addBulkLinks.  Message was: 'When disables unique check in MyRocks, 'INSERT or UPDATE' statement (INSERT ON DUPLICATE KEY UPDATE, REPLACE) is not allowed.'.  SQLState was: HY000.  Error is probably non-transient, will abort operation.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D54369
