### ISSUE TITLE
investigate adding script for testing concurrent insert to test tables without primary keys

### ISSUE THREAD

**Issue by alxyang** [facebook/mysql-5.6#157]
currently in our test suite there is no straightforward way to test bulk inserts asynchronously.  
Research using a python script to create multiple threads that insert rows concurrently into database, and check count afterwards for tables with no primary key.

**Comment by jtolmer** [comment]
Talked to you in person, but putting here for everyone else too. We already have python for that: https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/mysql-test/suite/innodb_stress/t/load_generator.py.

**Comment by alxyang** [comment]
closed by https://reviews.facebook.net/D53703
