### ISSUE TITLE
FbsonJsonParser and FbsonToJson ignore JSON string escape sequences

### ISSUE THREAD

**Issue by ashoemaker** [facebook/mysql-5.6#16]
[FbsonJsonParser](https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.23.71/fbson/FbsonJsonParser.h#L390) does not decode JSON string escape sequences, with the exception of `\` and `"`. The [JSON standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) specifies the following sequences that should be unescaped when parsing:
- `\"`
- `\\` 
- `\/`
- `\b`
- `\f`
- `\n`
- `\r`
- `\t`
- `\uXXXX`, where XXXX is a hexadecimal Unicode code point.

In addition, [FbsonToJson](https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.23.71/fbson/FbsonUtil.h#L85) does not escape the characters that must be escaped when serializing:
- `"`
- `\`
- Control characters from U+0000 to U+001F.

Here is an example that does not parse correctly:

``` json
{"name": "Hello, \ud83c!"}
```

**Comment by tianx** [comment]
Thank you Austin for raising the issue. We actually have an internal task for those requirements and will fix them in the near future, so that Fbson library will more compatible to JSON standards.

In the current behavior (MySQL), we process and save JSON string values as binary, and the string values are also returned as is.

**Comment by ghost** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jtolmer** [comment]
I'm sorry for the delay in resolving your issue. I expect to push a new branch that contains the fix later this week.

**Comment by jtolmer** [comment]
The new webscalesql-5.6.24.97 branch I just pushed contains the fixes for this issue.

**Comment by ashoemaker** [comment]
@jtolmer thanks for following up.
