### ISSUE TITLE
Strange EXPLAIN output for UPDATE ("Using temporary")

### ISSUE THREAD

**Issue by valeriikravchuk** [facebook/mysql-5.6#163]
Consider the following table:

mysql> show create table tr2\G
**************************\* 1. row ***************************
       Table: tr2
Create Table: CREATE TABLE `tr2` (
  `id` varchar(10) COLLATE latin1_bin NOT NULL,
  `c1` varchar(10) COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=ROCKSDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin
1 row in set (0.00 sec)

mysql> analyze table tr2;
+----------+---------+----------+----------+
| Table    | Op      | Msg_type | Msg_text |
+----------+---------+----------+----------+
| test.tr2 | analyze | status   | OK       |
+----------+---------+----------+----------+
1 row in set (0.03 sec)

mysql> select \* from tr2;
+----+------+
| id | c1   |
+----+------+
| A  | a    |
| B  | b    |
| c  | X    |
| d  | X    |
| e  | e    |
| f  | e    |
+----+------+
6 rows in set (0.00 sec)

Now, let's check EXPLAIN output for the following UPDATE:

mysql> explain update tr2 set c1 = 'X' where id between 'c' and 'e';
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra                        |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | const |    1 | Using where; Using temporary |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
1 row in set (0.00 sec)

I wonder why this "Using temporary" text is present in Extra column? This is NOT strictly related to RocksDB:

mysql> alter table tr2 engine=MyISAM;
Query OK, 6 rows affected (0.11 sec)
Records: 6  Duplicates: 0  Warnings: 0

mysql> analyze table tr2;
+----------+---------+----------+----------+
| Table    | Op      | Msg_type | Msg_text |
+----------+---------+----------+----------+
| test.tr2 | analyze | status   | OK       |
+----------+---------+----------+----------+
1 row in set (0.00 sec)

mysql> explain select c1 from tr2 where id between 'c' and 'e';
+----+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref  | rows | Extra                 |
+----+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | NULL |    2 | Using index condition |
+----+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------+
1 row in set (0.00 sec)

mysql> explain update tr2 set c1 = 'X' where id between 'c' and 'e';
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra                        |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | const |    2 | Using where; Using temporary |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
1 row in set (0.00 sec)

So, same for MyISAM table. Qucik test does NOT show temporary table created when the query is executed:

mysql> flush status;
Query OK, 0 rows affected (0.00 sec)

mysql> update tr2 set c1 = 'X' where id between 'c' and 'e';
Query OK, 1 row affected (0.00 sec)
Rows matched: 3  Changed: 1  Warnings: 0

mysql> show status like '%tmp%';
+-------------------------+-------+
| Variable_name           | Value |
+-------------------------+-------+
| Created_tmp_disk_tables | 0     |
| Created_tmp_files       | 0     |
| Created_tmp_tables      | 0     |
| Tmp_table_bytes_written | 120   |
+-------------------------+-------+
4 rows in set (0.00 sec)

In upstream MySQL the plan is surely different:

mysql> CREATE TABLE `tr2` (
    ->   `id` varchar(10) COLLATE latin1_bin NOT NULL,
    ->   `c1` varchar(10) COLLATE latin1_bin DEFAULT NULL,
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=MyISAM;
Query OK, 0 rows affected (0.16 sec)

mysql> insert into tr2 values ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd');
Query OK, 4 rows affected (0.03 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> analyze table tr2;
+----------+---------+----------+----------+
| Table    | Op      | Msg_type | Msg_text |
+----------+---------+----------+----------+
| test.tr2 | analyze | status   | OK       |
+----------+---------+----------+----------+
1 row in set (0.00 sec)

mysql> explain select c1 from tr2 where id between 'b' and 'c';
+----+-------------+-------+-------+---------------+---------+---------+------+-
-----+-----------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref  |
rows | Extra                 |
+----+-------------+-------+-------+---------------+---------+---------+------+-
-----+-----------------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | NULL |
   1 | Using index condition |
+----+-------------+-------+-------+---------------+---------+---------+------+-
-----+-----------------------+
1 row in set (0.06 sec)

mysql> explain update tr2 set c1='A' where id between 'b' and 'c';
+----+-------------+-------+-------+---------------+---------+---------+-------+
------+-------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   |
 rows | Extra       |
+----+-------------+-------+-------+---------------+---------+---------+-------+
------+-------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | const |
    1 | Using where |
+----+-------------+-------+-------+---------------+---------+---------+-------+
------+-------------+
1 row in set (0.00 sec)

**Comment by spetrunia** [comment]
"Using temporary" is really using a read-write IO buffer.  This misleading wording has been in MySQL for a long time : http://s.petrunia.net/blog/?p=85 .   However, these queries should not be using the read-write IO-buffer, either.

I cant' reproduce with a slightly old tree:

```
commit 2f92d119a539498e5c3c79930f6bb4246602cbcf
Author: Yoshinori Matsunobu <yoshinori@fb.com>
Date:   Thu Jan 7 13:07:27 2016 -0800
```

so this must be something changed recently.

**Comment by yoshinorim** [comment]
I could reproduce this with official 5.6.28+MyISAM. We recently upgraded fb-mysql revision from 5.6.24 to 5.6.27 so it may have triggered this issue.

**Comment by hermanlee** [comment]
I think this is somehow related to row based replication being enabled. There are calls that set all of the bit fields in the table's write_set in TABLE::mark_columns_per_binlog_row_image(). These bitfields are checked during the explain to determine if the key field is also being updated. If it is, then mysql thinks it may need to use temporary tables.

```
mysql> CREATE TABLE tr2 ( id varchar(10) COLLATE latin1_bin NOT NULL, c1 varchar(10) COLLATE latin1_bin DEFAULT NULL, PRIMARY KEY (id) ) ENGINE=myisam DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
Query OK, 0 rows affected (3.64 sec)

mysql> set binlog_format='statement';
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'binlog_format';
+---------------+-----------+
| Variable_name | Value     |
+---------------+-----------+
| binlog_format | STATEMENT |
+---------------+-----------+
1 row in set (0.00 sec)

mysql> explain update tr2 set c1 = 'X' where id between 'c' and 'e';
+----+-------------+-------+-------+---------------+---------+---------+-------+------+-------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra       |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+-------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | const |    1 | Using where |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+-------------+
1 row in set (0.01 sec)

mysql> set binlog_format='row';
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'binlog_format';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| binlog_format | ROW   |
+---------------+-------+
1 row in set (0.00 sec)

mysql> explain update tr2 set c1 = 'X' where id between 'c' and 'e';
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
| id | select_type | table | type  | possible_keys | key     | key_len | ref   | rows | Extra                        |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
|  1 | SIMPLE      | tr2   | range | PRIMARY       | PRIMARY | 12      | const |    1 | Using where; Using temporary |
+----+-------------+-------+-------+---------------+---------+---------+-------+------+------------------------------+
1 row in set (0.00 sec)
```

**Comment by valeriikravchuk** [comment]
I've reported this upstream as http://bugs.mysql.com/bug.php?id=80424

**Comment by gunnarku** [comment]
Closing given it's an upstream issue.
