### ISSUE TITLE
Optionally raise an error when using Gap Lock that MyRocks doesn't support

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#177]
This task is for making transition from InnoDB to MyRocks easier, until we support full Gap Lock in MyRocks/RocksDB.

InnoDB supports Gap Lock. MyRocks has very limited support for Gap Lock. When running queries relying on Gap Lock, MyRocks behaves as below.
- (1) Getting “Deadlock” errors in MyRocks, on conflict  => when updating the same row, with repeatable read isolation level
- (2) Works as same as InnoDB => when using all primary key columns in WHERE clause (point lookup)
- (3) MyRocks does not work at all

Typical example of (3) is when building a blocking queue. For example, "select \* from t where id1 = 1 order by id2 desc for update limit 1" blocks inserting any value greater than the id2 in InnoDB. MyRocks has no way to do that.

A proposal is adding a new session variable allow_queries_using_gap_lock. The error should be raised from both InnoDB and MyRocks (engine independent). Ideally I want to reject only (3). But I am not sure if it is feasible to distinguish (1) and (3) automatically. I'm thinking of rejecting both (1) and (3) then ask developers to allow it as needed.

I assume that all transactions relying on gap lock do locking select. Locking select includes locking select without modification (SELECT ... FOR UPDATE, SELECT .. LOCK IN SHARE MODE), and modifications with read lock (i.e. INSERT ... SELECT, UPDATE .. WHERE (SELECT..)).

Queries with modifications with read lock can be identified as follows.

```
  (lock_type == TL_READ || lock_type == TL_READ_NO_INSERT)
                        && (sql_command == SQLCOM_INSERT_SELECT
                            || sql_command == SQLCOM_REPLACE_SELECT
                            || sql_command == SQLCOM_UPDATE
                            || sql_command == SQLCOM_DELETE
                            || sql_command == SQLCOM_CREATE_TABLE)))
```

 This was taken from ha_innobase::store_lock(). lock_type is table->reginfo.lock_type.

Locking select without modification => (lock_type >= TL_READ_WITH_SHARED_LOCKS && sql_command == SQLCOM_SELECT)

MyRocks has a logic to detect if using all primary key columns or not, at ha_rocksdb::index_read_map_impl().

```
  bool using_full_key= (keypart_map == HA_WHOLE_KEY) ||
                       (keypart_map == ((key_part_map(1) << actual_key_parts)
                                         - 1));
  if (active_index == table->s->primary_key &&
      find_flag == HA_READ_KEY_EXACT && using_full_key)
```

If ha_rocksdb::index_read_map_impl() is called, it is easy to distinguish if the query is using all primary key columns or not. The problem is this function is not called when not using index (i.e. full table scan). How to raise an error in that case?

**Comment by spetrunia** [comment]
> The problem is this function is not called when not using index (i.e. full table scan). How to raise an error in that case?

There are only a few functions that read rows: rnd_next(), index_first(), index_last(), index_read_map(), index_read_idx().
We could put in all these places a check that returns an error if we're doing a locking read and not using the full PK.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D54813
