### ISSUE TITLE
ALTER TABLE ... DROP INDEX does a table copy for MyRocks

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#181]
This is a feature request. ALTER TABLE ... DROP INDEX is too slow for MyRocks and does a table copy. PMP output from a slow one is at https://gist.github.com/mdcallag/f86882470941f58b0cd4

Dropping index for tpcc-mysql with 20 warehouses:
alter table order_line drop index fkey_order_line_2;

MyRocks: Query OK, 6003079 rows affected (4 min 15.31 sec)
InnoDB: Query OK, 0 rows affected (0.02 sec)

**Comment by alxyang** [comment]
I have been working on this as part of https://github.com/facebook/mysql-5.6/issues/47.
The first pass of fast drop index implementation should be out in a diff today for review.

**Comment by alxyang** [comment]
https://reviews.facebook.net/D54777 is currently awaiting review

**Comment by alxyang** [comment]
fast drop index is now supported as of the previous diff
