### ISSUE TITLE
Builds on Ubuntu don't support snappy for RocksDB

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#197]
My builds on Ubuntu link mysqld with libsnappy but the nested build for RocksDB doesn't add -DSNAPPY and Snappy compression cannot be used with it. If I build RocksDB stand-alone it supports Snappy.

my cmake command line:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 

I get this error message at startup

```
2016-03-09 10:01:51 26540 [ERROR] RocksDB: Error opening instance: Invalid argument: Compression type Snappy is not linked with the binary.
2016-03-09 10:01:51 26540 [ERROR] Plugin 'ROCKSDB' init function returned error.
2016-03-09 10:01:51 26540 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
2016-03-09 10:01:51 26540 [ERROR] Unknown/unsupported storage engine: rocksdb
2016-03-09 10:01:51 26540 [ERROR] Aborting
```

**Comment by yoshinorim** [comment]
You need to set env variable WITH_SNAPPY. For example, if libsnappy.a is located at /usr/lib/, you need to execute "export WITH_SNAPPY=/usr" then run cmake&make. By default, only zlib is linked. This should be documented.

**Comment by yoshinorim** [comment]
Updated https://github.com/facebook/mysql-5.6/wiki/Build-Steps

**Comment by yoshinorim** [comment]
@mdcallag Let me know if you're unhappy with my comments.

**Comment by mdcallag** [comment]
That helps but isn't enough. Now I get "-lsnappy" on the link for mysqld but $root/rocksdb is not using -DSNAPPY while it is using -DZLIB. 

This didn't work: cmake ... -DUSE_SNAPPY_DEFAULT=1

From $root/rocksdb/thirdparty.inc I see:

```
#
# Edit these lines to set defaults for use of external libraries
#
set(USE_GFLAGS_DEFAULT 0)        # GFLAGS is disabled by default, enable with -DGFLAGS=1 cmake command line agrument
set(USE_SNAPPY_DEFAULT 0)        # SNAPPY is disabled by default, enable with -DSNAPPY=1 cmake command line agrument
set(USE_LZ4_DEFAULT 0)           # LZ4 is disabled by default, enable with -DLZ4=1 cmake command line agrument
set(USE_ZLIB_DEFAULT 0)          # ZLIB is disabled by default, enable with -DZLIB=1 cmake command line agrument
set(USE_JEMALLOC_DEFAULT 0)      # JEMALLOC is disabled by default, enable with -DJEMALLOC=1 cmake command line agrument
set(USE_JENONINIT_DEFAULT 1)     # Default is enabled do not call je_init/je_uninit as the newer versions do not have it disable with -DJENONINIT=0
```

**Comment by mdcallag** [comment]
Editing $root/rocksdb/thirdparty.inc worked but I'd rather not have to do that

**Comment by gunnarku** [comment]
There's yet another issue here as well. Logic in `CMakeLists.txt` assumes that the library is always under `someprefix/lib` when for example on my Ubuntu laptop the libraries are installed under `/usr/lib/x86_64-linux-gnu/` because library packages are multiarch.

IMHO the prefix (`WITH_SNAPPY` or whatnot) needs to specify the full directory path before the library name.

**Comment by 3manuek** [comment]
I'm having the same issue with LZ4, followed #354 and edited CMake. If I try to set the default with `-DLZ4=1` (environment variable is already set), it takes the libraries but it does not recognize to set it as default.

```
CMake Warning:
  Manually-specified variables were not used by the project:
    LZ4
```

**Comment by mdcallag** [comment]
Duplicates include:
https://github.com/facebook/mysql-5.6/issues/354
https://github.com/facebook/mysql-5.6/issues/104

Anyone fixing CMakeLists.txt should also consider fixing this at the same time:
https://github.com/facebook/mysql-5.6/issues/351

**Comment by mdcallag** [comment]
fixed by https://github.com/facebook/mysql-5.6/commit/24ffae78ef27ec4611cea285017e14e70dca404b

**Comment by unoexperto** [comment]
Guys, unfortunately none of the above helped me. Could you please take a look at https://github.com/facebook/rocksdb/issues/1663 ?

**Comment by gunnarku** [comment]
It seems that RocksDB team is following up on this as part of discussion associated with https://github.com/facebook/rocksdb/issues/1663. Please note that MyRocks and RocksDB use different build environments and therefore the solutions will be specific to an environment.
