### ISSUE TITLE
I want to compile mysql for facebook without rocksdb 

### ISSUE THREAD

**Issue by joanney1** [facebook/mysql-5.6#20]
Hello,

I want to compile mysql for facebook without rocksdb. 
What do you use when executing cmake with?
for example  -DWITH_ROCKSDB_STORAGE_ENGINE=0 

And, 
I want to test document type for json data. 
So, I think It is not problem compiling source without rocksdb. 
Is it right? 

Thx.

**Comment by maykov** [comment]
Here is the fix: https://reviews.facebook.net/D47331 
The proper variable name for disabling rocksdb is: WITHOUT_ROCKSDB_SE_STORAGE_ENGINE=1

**Comment by maykov** [comment]
I hope, it builds now. Let me know if not.
