### ISSUE TITLE
Make ha_rocksdb::convert_record_from_storage_format and RDBSE_KEYDEF::unpack_record more efficient

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#200]
How to repeat:

```
create table t1 (id1 bigint, id2 bigint, c1 bigint, c2 bigint, c3 bigint, c4 bigint, c5 bigint, c6 bigint, c7 bigint, primary key (id1, id2), index i(c1, c2));

load data local infile '/data/mysql/10m.dat' into table t1 fields terminated by ',';

set global rocksdb_perf_context_level=0;
(disconnect and reconnect)
select count(*) from t1 force index(primary);
```

In MyRocks, the select took 6.71 sec. InnoDB took 3.30 sec.

10m.dat can be created as follows. You can reduce the number of lines, depending on your machine spec.

```
#!/usr/bin/perl

for (my $i = 1; $i <= 10000000; $i++) {
  print "$i,0,$i,0,0,0,0,0,0\n";
}
```

Here are Perf outputs in MyRocks.

```
-   14.03%  my-oneconnectio  mysqld               [.] myrocks::ha_rocksdb::convert_record_from_storage_format          a
   - myrocks::ha_rocksdb::convert_record_from_storage_format                                                           `
      + myrocks::ha_rocksdb::rnd_next_with_direction                                                                   a
-    8.37%  my-oneconnectio  libc-2.20.so         [.] __memcpy_sse2_unaligned                                          a
   - __memcpy_sse2_unaligned                                                                                           a
      + 52.32% myrocks::ha_rocksdb::rnd_next_with_direction                                                            a
      + 30.75% myrocks::ha_rocksdb::convert_record_from_storage_format                                                 a
      + 13.34% rocksdb::(anonymous namespace)::TwoLevelIterator::Next                                                  a
      + 3.58% rocksdb::DBIter::Next                                                                                    a
-    4.72%  my-oneconnectio  mysqld               [.] myrocks::RDBSE_KEYDEF::unpack_record                             a
   - myrocks::RDBSE_KEYDEF::unpack_record                                                                              a
      + 84.41% myrocks::ha_rocksdb::convert_record_from_storage_format                                                 a
      + 7.71% myrocks::ha_rocksdb::rnd_next_with_direction                                                             a
-    4.39%  my-oneconnectio  mysqld               [.] Field::set_notnull                                               a
   - Field::set_notnull                                                                                                a
      + 55.38% myrocks::ha_rocksdb::convert_record_from_storage_format                                                 a
      + 44.62% myrocks::ha_rocksdb::rnd_next_with_direction                                                            a
+    4.26%  my-oneconnectio  mysqld               [.] rocksdb::StatisticsImpl::recordTick                              a
-    3.70%  my-oneconnectio  mysqld               [.] Field::move_field_offset                                         a
   - Field::move_field_offset                                                                                          a
      + 75.54% myrocks::ha_rocksdb::rnd_next_with_direction                                                            a
      + 24.46% myrocks::ha_rocksdb::convert_record_from_storage_format  
```

**Comment by spetrunia** [comment]
my first idea was: 

> InnoDB only unpacks table fields that are requested by the query, while MyRocks always unpacks all fields.

Trying to check this - running queries that read different sets of columns.

Q1: 
`select count(*) from t1 force index(primary);`

Q2:

```
select  sum(id1),sum(id2) from t1 force index(PRIMARY);
```

(Starting from this query it uses full table scan, but this is comparable to 'index' scan on pk)
Q3:

``` select
  sum(id1),sum(id2),sum(c1),sum(c2)
from t1 force index(PRIMARY);
```

Q4:

```
select
  sum(id1),sum(id2),sum(c1),sum(c2),sum(c3),sum(c4)
from t1 force index(PRIMARY);
```

Q5:

```
select
  sum(id1),sum(id2),sum(c1),sum(c2),sum(c3),sum(c4),sum(c5),sum(c6),sum(c7)
from t1 force index(PRIMARY);
```

Results: (exec time on InnoDB, exec time on MyRocks):

```
Q1: 2.30  6.84    
Q2: 3.39  8.21
Q3: 4.70  9.14
Q4: 5.75  10.90
Q5: 8.07  12.7
```

**Comment by spetrunia** [comment]
![image](https://cloud.githubusercontent.com/assets/2734550/13823667/b6a545d4-ebbb-11e5-95e0-d909ce62319c.png)

**Comment by spetrunia** [comment]
Looks like the difference in execution time doesn't depend on the number of columns read?  I'll try to make a version where ha_rocksdb::convert_record_from_storage_format detects that it doesn't need anything for COUNT(*) and measure again.

**Comment by spetrunia** [comment]
Make a diff that skips the call to convert_record_from_storage_format() if the caller doesn't need any columns:  https://gist.github.com/spetrunia/23bcdbbe36518b53b2ba

Tried it on Q1: issue200-try.diff 4.12 sec
Comparing it with previous results:
InnoDB: 2.30 
MyRocks + dif: 4.12  (+1.82)
MyRocks: 6.84  (+2.72)

This shows that decoding columns is 40% of the slowdown.

**Comment by spetrunia** [comment]
@yoshinorim, I assume this means that 
- I should make column unpacking more efficient
- although there are other causes of slowdown (which hopefully will be easier to track after unpacking is fixed)
  ?

**Comment by yoshinorim** [comment]
@spetrunia: I tried your experimental patch (https://gist.github.com/spetrunia/23bcdbbe36518b53b2ba) then "select count(*) from t1 force index(primary)" time reduced from 6.71s to 3.26s, which is very effective and close to InnoDB. Now the biggest bottleneck is "rocksdb::StatisticsImpl::recordTick()", which is known issue in RocksDB internal.

So yes, please make column unpacking more efficient. This is very promising.

**Comment by yoshinorim** [comment]
I tried commenting out RecordTick() at DBIter::Next(), then select time decreased from 3.26s to 2.83s.

```
diff --git db/db_iter.cc db/db_iter.cc
index 07c8d9e..69eeccc 100644
--- db/db_iter.cc
+++ db/db_iter.cc
@@ -258,10 +258,10 @@ void DBIter::Next() {
   }
   FindNextUserEntry(true /* skipping the current user key */);
   if (statistics_ != nullptr) {
-    RecordTick(statistics_, NUMBER_DB_NEXT);
+    //RecordTick(statistics_, NUMBER_DB_NEXT);
     if (valid_) {
-      RecordTick(statistics_, NUMBER_DB_NEXT_FOUND);
-      RecordTick(statistics_, ITER_BYTES_READ, key().size() + value().size());
+      //RecordTick(statistics_, NUMBER_DB_NEXT_FOUND);
+      //RecordTick(statistics_, ITER_BYTES_READ, key().size() + value().size());
     }
   }
```

**Comment by spetrunia** [comment]
https://reviews.facebook.net/D56115 - the patch that makes MyRocks only decode columns that were requested by the SQL layer.

**Comment by spetrunia** [comment]
![image](https://cloud.githubusercontent.com/assets/2734550/14128539/6d7c444c-f62a-11e5-988e-81ec4bc267c4.png)
- _patch#2_ is the above patch
- _No-row-decoding_ is performance when convert_record_from_storage_format does nothing at all (so it's an unachievable ideal).

From this chart one can see that the speedup of the patch is greater when SQL layer expects fewer columns (which is expected).  When SQL layer asks for no columns, there is some overhead still.

**Comment by spetrunia** [comment]
Possible further improvements:
- When doing a secondary index scan and using index condition pushdown, index columns are decoded so that the condition can be checked. We don't need to decode these columns when reading the table row.
- When doing a secondary index scan and decoding index columns, don't decode columns that were not requested.
- Don't decode PK columns when they are not requested (need to check if this actually happens, there used to be a redundant prepare_for_position() call on the SQL layer that caused PK columns to be read for many queries)
- Apply the optimization for UPDATEs.  It is currently not applied:
  Current state is that ha_rocksdb::update_row(old_row, new_row) assumes
  that the new_row has the values for all columns. The assumption is true
  since the SQL layer reads the row before updating it, and the read 
  operation decodes all columns.
  If we make the read operation to read only the requested columns, then the 
  write operation should write only the written columns. That is, we'll need 
  to take the storage form of the row that was just read, take the table->record[0] 
  form of the row that was passed to ::update_row() and merge them.

**Comment by yoshinorim** [comment]
@spetrunia : Was rocksdb_perf_context_level turned off on your latest benchmark? If not, could you turn it off and try again?

**Comment by yoshinorim** [comment]
@spetrunia  Also, could you please use count(id1)~count(c7), not sum() for Q2~Q5? I am seeing that sum() overhead is not negligible -- some functions like do_add() uses lots of cpu time.

On my machine, without your patch, Q1 took 7.07s in MyRocks and 3.23s in InnoDB. Q5 with s/sum/count/g took 7.69s in MyRocks and 8.21s in InnoDB. I have not tried your diff yet but I assume it fixes Q1. Q5 is already close to (or even better than) InnoDB.

**Comment by spetrunia** [comment]
@yoshinorim the tests were run with `rocksdb_perf_context_level=0`. This is the default that I get. 

I am running one the latest where the patch you've posted earlier here 
https://github.com/facebook/mysql-5.6/issues/200#issuecomment-197536034 is not applicable because the counter increments were already changed to BumpGlobalStats.

**Comment by spetrunia** [comment]
@yoshinorim, confim.  I've tried queries with COUNT, and here are the results:

```
    COUNT-tree  COUNT-patch2    SUM-tree    SUM-patch2
Q1   6.9    5.12    6.88    5.18
Q2  6.99    5.22    7.91    6.22
Q3  7.26    5.87    8.96    7.65
Q4  7.56    6.40    9.94    8.83
Q5  8.23    7.39    11.44   10.63
```

![image](https://cloud.githubusercontent.com/assets/2734550/14158743/819567fa-f6da-11e5-8e04-5f18f29b9485.png)

I'll compare with InnoDB now

**Comment by spetrunia** [comment]
Tried comparing with InnoDB.  All setting are either default or very close.  For innodb, tried all default settings, and 12G buffer pool. (The machine is m4.4xlarge, 64G RAM).
(I hope I'm not missing anything important with this setup?)

`skip-row-recode` is not decoding the columns at all, https://gist.github.com/spetrunia/2cb9f3df2a2d8087441400f902c16e3d (this produces wrong query result)

```
MyRocks-tree    MyRocks-patch2  MyRocks-skip-row-decode InnoDB-12G-bufpool  InnoDB-all-defaults
Q1  6.90    5.12    4.36    2.30    2.70
Q2  6.99    5.22    4.45    2.78    3.18
Q3  7.26    5.87    4.76    3.52    3.94
Q4  7.56    6.40    5.05    4.22    4.63
Q5  8.23    7.39    5.70    5.99    6.38
```

![image](https://cloud.githubusercontent.com/assets/2734550/14159585/3a8b22e6-f6df-11e5-9333-73ed0497a44c.png)

So
- the patch fixes a good fraction of costs to decode the row
- InnoDB is still faster
- Except for Q5, even using skip-row-decode won't let MyRocks to catch up

**Comment by spetrunia** [comment]
InnoDB has a thing called "prefetch cache". I saw it on other occasions and always wondered what its impact is. I made a patch which I believe disables it: https://gist.github.com/spetrunia/7ec9b54b5720feaa370671b4dc44bdf8  and re-ran the test from the previous comment:

```
InnoDB-no-prefetch-cache
4.24
4.73
5.45
6.1
7.51
```

![image](https://cloud.githubusercontent.com/assets/2734550/14160348/84a28a7c-f6e4-11e5-8732-4a7e284fd3cf.png)

With prefetch cache disabled, innodb is noticeably slower.

**Comment by yoshinorim** [comment]
@spetrunia Thanks! Apparently all rows are cached in buffer pool so no read i/o prefetch matters here. Does MYSQL_FETCH_CACHE prefetch up to 8 consecutive rows then converting them into MySQL format at once? It would certainly reduce frequency of unpack calls so it would have visible impacts for in memory scans. Maybe it's worth supporting in MyRocks too?

**Comment by mdcallag** [comment]
What is the status of this? It will help with some of my perf test results.

**Comment by spetrunia** [comment]
I've addressed all review feedback for https://reviews.facebook.net/D56115. This patch gives these   speedups (the number is new_query_time / old_query_time)

```
Q1 0.69
Q2 0.74
Q2 0.82
Q2 0.86
Q2 0.91
```

InnoDB is still ~2x faster then the patched version in my measurements.

I think it makes sense to still push this patch, and then continue in two directions:
1. More of optimization like this.  I think I know how to make convert_record_from_storage_format faster)
2. Do something like InnoDB's row prefetch feature

**Comment by mdcallag** [comment]
I am happy with a partial fix for now. This will help for some of the perf
results I want to publish.

On Fri, Apr 8, 2016 at 8:02 AM, Sergei Petrunia notifications@github.com
wrote:

> I've addressed all review feedback for https://reviews.facebook.net/D56115.
> This patch gives these speedups (the number is new_query_time /
> old_query_time)
> 
> Q1 0.69
> Q2 0.74
> Q2 0.82
> Q2 0.86
> Q2 0.91
> 
> InnoDB is still ~2x faster in my measurements.
> 
> I think it makes sense to still push this patch, and then continue in two
> directions:
> 1. More of optimization like this. I think I know how to make
>    convert_record_from_storage_format faster)
> 2. Do something like InnoDB's row prefetch feature
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/200#issuecomment-207468692

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by mdcallag** [comment]
Is there an ETA for when this gets pushed?

**Comment by spetrunia** [comment]
@mdcallag , pushed this now

**Comment by mdcallag** [comment]
Benefit was between 2% and 11% at 16 clients for my tests of sysbench. I didn't choose this test to highlight the best case, I just happened to have results from a binary without the fix.
https://gist.github.com/mdcallag/6e0482d86d195cc51ceedde64981587e

I will try to repeat this test for a longer range scan. It used 100 rows.

**Comment by spetrunia** [comment]
The second part of the patch: https://reviews.facebook.net/D57975

It gives 1-2% benefit when scanning large ranges (less than I expected it do).  

I've also tried 
- removing other virtual calls
- adding custom functions for 4-byte or 8-byte [unsigned] integer (following the example of MySQL's ref access and GROUP BY code)
- other similar things

but these didn't produce any measurable benefit.  So, it seems the above patch is as good as one can get by trying to make column unpacking more lightweight.

**Comment by spetrunia** [comment]
Pushed the second part of the patch.
