### ISSUE TITLE
Compiling the MyRocks project failed

### ISSUE THREAD

**Issue by mariadb-DanielLee** [facebook/mysql-5.6#207]
myrocks@rocksdb:~/builds/mytest/mysql-5.6$ git show
commit d3054d2915ffcde166cd67760ac6a618c6d02b82

end of the make command output
.
.
.
.
  1043  [ 57%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/unireg.cc.o
  1044  [ 57%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/sql_timer.cc.o
  1045  Linking CXX static library libsql_embedded.a
  1046  [ 57%] Built target sql_embedded
  1047  make: **\* [all] Error 2

myrocks@rocksdb:~/builds/mytest/log$ cat -n 5.make.log |grep error
    27  [  2%] [  2%] Building C object regex/CMakeFiles/regex.dir/regerror.c.o
   109  Building C object mysys/CMakeFiles/mysys.dir/errors.c.o
   153  Building C object mysys/CMakeFiles/mysys.dir/my_error.c.o
   308  [ 14%] Generating ../include/mysqld_error.h, ../sql/share/english/errmsg.sys
   538  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb.h:599:40: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   544  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:49:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   547  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:53:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   550  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:57:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   567  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb.h:599:40: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   575  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:49:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   578  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:53:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   581  /home/myrocks/builds/mytest/mysql-5.6/storage/rocksdb/./ha_rocksdb_proto.h:57:62: error: ‘**returns_nonnull**’ attribute directive ignored [-Werror=attributes]
   599  [ 28%] cc1plus: all warnings being treated as errors
   616  cc1plus: all warnings being treated as errors
   806  [ 41%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/error_stats.cc.o
   816  [ 41%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/derror.cc.o
   950  [ 50%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/sql_alloc_error_handler.cc.o
   994  Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/**/sql/sql_error.cc.o

**Comment by gunnarku** [comment]
Can you please follow the steps at https://github.com/facebook/mysql-5.6/wiki/Reporting-bugs-and-asking-for-help and add the relevant information about the OS which is being used, toolset version etc. This way we can do something actionable to investigate the issue.

**Comment by mariadb-DanielLee** [comment]
myrocks@rocksdb:~/builds/mytest/log$ uname -a
Linux rocksdb 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

myrocks@rocksdb:~/builds/mytest/log$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

Commands used to make the project:

   echo `date` 1/5 git clone ...... 1.gitclone.log
   git clone https://github.com/facebook/mysql-5.6.git > ./log/1.gitclone.log 2>&1
   cd mysql-5.6
   echo `date` 2/5 git init ....... 2.gitinit.log
   git submodule init > ../log/2.gitinit.log 2>&1
   echo `date` 3/5 git update ..... 3.gitupdate.log
   git submodule update > ../log/3.gitupdate.log 2>&1
   echo `date` 4/5 cmake .......... 4.cmake.log
   cmake . -DCMAKE_BUILD_TYPE=Debug -DWITH_SSL:STRING=system -DWITH_ZLIB:STRING=system -DMYSQL_MAINTAINER_MODE=1 > ../log/4.cmake.log 2>&1
   echo `date` 5/5 make ........... 5.make.log
   make -j8 > ../log/5.make.log 2>&1
   echo `date` Done
#

These commands were extracted from a .sh script.  They were working fine last week.

**Comment by gunnarku** [comment]
What is the version of the toolset you're using and what is it (Clang, GCC)? For example:

```
gcc --version
g++ --version
```

**Comment by mariadb-DanielLee** [comment]
myrocks@rocksdb:~/builds/mytest/log$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

myrocks@rocksdb:~/builds/mytest/log$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gunnarku** [comment]
Thank you for detailed information, gcc 4.8.x doesn't implement a support for `returns_nonnull`. Take a look at https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/Function-Attributes.html vs. https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Function-Attributes.html.

Good way to fix this issue is to update the compiler toolset to at least gcc 4.9.2.

Most likely this won't be the first or last change which will rely on the enhanced error detection in the newer versions of GCC.

**Comment by gunnarku** [comment]
Quick alternative is also to remove all the four instances of `__returns_nonnull__` from the source code temporarily. This will unblock you as well.

HTH

**Comment by gunnarku** [comment]
Attributes breaking build with gcc 4.8.x removed. Please try `git pull --rebase` and see if the new changes will fix the issues. If the break will still be present then please re-open the issue.

**Comment by mariadb-DanielLee** [comment]
myrocks@rocksdb:~/builds/reptest/mysql-5.6$ git show
commit d3054d2915ffcde166cd67760ac6a618c6d02b82
Author: Peng Tian pengt@fb.com
Date:   Mon Feb 15 10:09:36 2016 -0800

Compiled successfully after upgrading gcc to 4.9.3

**Comment by gunnarku** [comment]
Thank you for validating!
