### ISSUE TITLE
ALTER TABLE may cause data inconsistency

### ISSUE THREAD

**Issue by mariadb-DanielLee** [facebook/mysql-5.6#209]
Build tested:

myrocks@rocksdb:~/builds/reptest/mysql-5.6$ git show
commit d3054d2915ffcde166cd67760ac6a618c6d02b82
Author: Peng Tian pengt@fb.com
Date:   Mon Feb 15 10:09:36 2016 -0800

After executing the statements from lines 22 to 972, I got:

mysql> desc t1;
+-------+---------+------+-----+---------+-------+
| Field | Type    | Null | Key | Default | Extra |
+-------+---------+------+-----+---------+-------+
| col4  | text    | YES  |     | NULL    |       |
| col2  | int(11) | YES  |     | NULL    |       |
| col1  | int(11) | YES  | MUL | NULL    |       |
| col3  | int(11) | YES  |     | NULL    |       |
+-------+---------+------+-----+---------+-------+
4 rows in set (0.00 sec)

mysql> select \* from t1;
+------+------+------+------+
| col4 | col2 | col1 | col3 |
+------+------+------+------+
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
+------+------+------+------+
11 rows in set (0.00 sec)

I then execute the "ALTER TABLE t1 ADD PRIMARY KEY ( col4(10), col2 );", which failed.  I check the table again and got two extra rows.

mysql> ALTER TABLE t1 ADD PRIMARY KEY ( col4(10), col2 );
ERROR 1062 (23000): Duplicate entry '2' for key 'PRIMARY'
mysql> select \* from t1;
+------+------+------+------+
| col4 | col2 | col1 | col3 |
+------+------+------+------+
| NULL |    2 |    2 |    2 |
| NULL |    2 |    2 |    2 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
+------+------+------+------+
13 rows in set (0.00 sec)

I spent some time trying to pinpoint where the two rows came from and was unable to do so.  I assume that they were either delete rows, or rows that were inserted and rolled back.

[exec.txt](https://github.com/facebook/mysql-5.6/files/180264/exec.txt)

**Comment by yoshinorim** [comment]
Thanks. Verified as described.

**Comment by yoshinorim** [comment]
I managed to reproduce with the following queries. I'm still not sure why this has happened, but it reproduced without ALTER TABLE ADD PRIMARY KEY.

```
DROP TABLE if exists t1;
SET AUTOCOMMIT = 0;
CREATE TABLE `t1` (
  `col4` text COLLATE latin1_bin,
  `col2` int(11) DEFAULT NULL,
  `col1` int(11) DEFAULT NULL,
  `col3` int(11) DEFAULT NULL,
  KEY `idx` (`col1`)
) ENGINE=ROCKSDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
insert into t1 (col2, col1, col3) values (2,2,2),(2,2,2),(2,3,3),(2,3,3),(2,3,3),(3,3,3),(3,3,3),(3,3,3),(2,3,3),(3,3,3),(3,3,3),(3,3,3),(3,3,3);
COMMIT;

ALTER TABLE t1 ADD COLUMN extra INT;
 UPDATE t1 SET extra = col3 ;
 ALTER TABLE t1 DROP COLUMN col3 ;
 ALTER TABLE t1 CHANGE COLUMN extra col3 INT;

DELETE FROM t1 WHERE col1 = 1 OR col1 IS NULL ;
 INSERT INTO t1 (col1,col2,col3,col4) VALUES /* 3 */ (3,3,3,REPEAT(CAST(3 AS CHAR(1)),@fill_amount)), (3,3,3,REPEAT(CAST(3 AS CHAR(1)),@fill_amount)) ;
 COMMIT;
UPDATE t1 SET col2 = NULL LIMIT 2 ;
 COMMIT;
 DELETE FROM t1 WHERE col1 = 2 OR col1 IS NULL ;
 COMMIT;
 checksum table t1;
 select * from t1;
select sleep(2);
checksum table t1;
select * from t1;
```

The last two select and checksum table results were as follows.

```
mysql>  checksum table t1;
+---------+-----------+
| Table   | Checksum  |
+---------+-----------+
| test.t1 | 613834697 |
+---------+-----------+
1 row in set (0.00 sec)

mysql>  select * from t1;
+------+------+------+------+
| col4 | col2 | col1 | col3 |
+------+------+------+------+
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
+------+------+------+------+
13 rows in set (0.00 sec)

mysql> select sleep(2);
+----------+
| sleep(2) |
+----------+
|        0 |
+----------+
1 row in set (2.00 sec)

mysql> checksum table t1;
+---------+------------+
| Table   | Checksum   |
+---------+------------+
| test.t1 | 3178074051 |
+---------+------------+
1 row in set (0.00 sec)

mysql> select * from t1;
+------+------+------+------+
| col4 | col2 | col1 | col3 |
+------+------+------+------+
| NULL |    2 |    2 |    2 |
| NULL |    2 |    2 |    2 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    2 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
| NULL |    3 |    3 |    3 |
+------+------+------+------+
15 rows in set (0.00 sec)
```

The last select returned two extra rows. Both were col1=2, which were supposed to be deleted by the last DELETE.

**Comment by yoshinorim** [comment]
I couldn't reproduce if table t1 had primary key.
