### ISSUE TITLE
add memtable memory counters to SHOW GLOBAL STATUS

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#210]
These are displayed in SHOW ENGINE ROCKSDB STATUS. I want that in SHOW GLOBAL STATUS as well to monitor memory consumption.

MemTable Total: 4687688240  
MemTable Unflushed: 667581960

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/ca29921f32e7267f7fc1814092a4a374411853a6
