### ISSUE TITLE
increase MALLOC_STATUS_LEN

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#215]
This is in sql_parse.cc and is the result buffer for SHOW MEMORY STATUS that gets the result of malloc_stats_print() from jemalloc. The current buffer is 300,000 which is too small and truncates the per-arena stats. I think this should be set to 1,000,000

```
static int show_memory_status(THD* thd)
{
  List<Item> field_list;
  Protocol *protocol= thd->protocol;
  malloc_status mstat;
  char* buf;
  const uint MALLOC_STATUS_LEN= 300000;
```

**Comment by gunnarku** [comment]
This is trivial to fix. Will send a diff out today.

**Comment by gunnarku** [comment]
Fixed.
