### ISSUE TITLE
request for version info

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#223]
I want to know what version of MyRocks I am using I expect others to have the same request when debugging. I think this should include the git hash used to build MyRocks, and given that RocksDB is a git submodule I want to know the git hash for both MySQL and RocksDB.

I think this should be available via SHOW GLOBAL STATUS and written to the db error log.

Today I have nothing in SHOW GLOBAL STATUS. I thought there used to be something.

```
bin/mysql -uroot -ppw -e 'show global status' | grep -i version
Ssl_version
rocksdb_number_superversion_acquires    237
rocksdb_number_superversion_cleanups    6
rocksdb_number_superversion_releases    11
```

And this in the 
 this information on connecting

```
bin/mysql -uroot -ppw 
...
Server version: 5.6.27-log Source distribution
```

This is in the db error log today:

```
2016-04-01 07:41:06 0 [Note] /home/mdcallag/b/myrocks/bin/mysqld (mysqld 5.6.27-log) starting as process 28871 ...
```

If I am clever I can get this from $datadir/.rocksdb/LOG. But I want something in the db error log

```
2016/04/01-07:41:06.724420 7fdd5553a9c0 RocksDB version: 4.6.0
2016/04/01-07:41:06.724444 7fdd5553a9c0 Git sha rocksdb_build_git_sha:ad2fdaa823bff24e71e7b20c3b22c76d2688823c
```

**Comment by jkedgar** [comment]
I think I have this working.  The output in the error log looks like this:

```
2016-04-07 00:56:39 80690 [Note] MyRocks git hash: f98f8e1a22c5e5cdb7a35e8ade91ae5fe4338c21 (Wed Apr 6 14:08:18 2016 -0700)
2016-04-07 00:56:39 80690 [Note] Rocksdb git hash: 2feafa3db92c966345343bf6a813e8aa9f39fd21 (Thu Mar 31 17:12:18 2016 -0700)
```

And the values in the global status look like this:

```
mysql> show global status like "%git%";
+----------------------------+------------------------------------------+
| Variable_name              | Value                                    |
+----------------------------+------------------------------------------+
| rocksdb_git_date           | Wed Apr 6 14:08:18 2016 -0700            |
| rocksdb_git_hash           | f98f8e1a22c5e5cdb7a35e8ade91ae5fe4338c21 |
| rocksdb_git_submodule_date | Thu Mar 31 17:12:18 2016 -0700           |
| rocksdb_git_submodule_hash | 2feafa3db92c966345343bf6a813e8aa9f39fd21 |
+----------------------------+------------------------------------------+
```

Does this look good?  I included the dates of the git hashes, but I'm not sure it is helpful.

**Comment by jkedgar** [comment]
Diff is https://reviews.facebook.net/D56355

**Comment by mdcallag** [comment]
looks good

On Wed, Apr 6, 2016 at 3:04 PM, Jay Edgar notifications@github.com wrote:

> Diff is https://reviews.facebook.net/D56355
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/223#issuecomment-206590662

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
There were comments that the naming was confusing so I changed the names a bit.  It now looks like this and all the values are present even if RocksDB is not enabled.

```
mysql> show global status like "%git%";
+------------------+------------------------------------------+
| Variable_name    | Value                                    |
+------------------+------------------------------------------+
| Git_date         | Thu Apr 28 09:03:10 2016 -0700           |
| Git_hash         | b9f22219a5a6f65b29edee8872e61d86967b6c63 |
| Rocksdb_git_date | Wed Apr 13 19:06:48 2016 -0700           |
| Rocksdb_git_hash | 535af525d6940a4eb3c4b6eaf3ba219ab65b4731 |
+------------------+------------------------------------------+
4 rows in set (0.00 sec)
```
