### ISSUE TITLE
assert in LRUHandle::Free 

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#228]
The test case is the insert benchmark. I think it happens during DROP DATABASE when the database is > 10gb, but my logging doesn't capture that. This reproduces on at least 25% of the tests when using jemalloc 4.1.0. This didn't reproduce when using glibc 2.17, jemalloc 3.6.0, tcmalloc 2.1 or tcmalloc 2.5.

From mysqld error log

```
2016-04-03 19:16:53 16111 [Note] RocksDB: Finished filtering dropped index (0,282)
2016-04-03 19:16:53 16111 [Note] RocksDB: Finished filtering dropped index (0,286)
2016-04-03 19:16:53 16111 [Note] RocksDB: Finished filtering dropped index (0,287)
mysqld: /home/mdcallag/git/fbmysql/rocksdb/util/cache.cc:75: void rocksdb::{anonymous}::LRUHandle::Free(): Assertion `(refs == 1 && in_cache) || (refs == 0 && !in_cache)' failed.
02:39:50 UTC - mysqld got signal 6 ;
```

RocksDB git hash. Feature request open for mysqld to log something too:

```
2016/04/04-05:45:19.478461 7f710eefda80 RocksDB version: 4.6.0
2016/04/04-05:45:19.478529 7f710eefda80 Git sha rocksdb_build_git_sha:ad2fdaa823bff24e71e7b20c3b22c76d2688823c
```

HEAD from my git repos for FB MySQL and the RocksDB submodule

```
commit 73ee46076d13cc4a33b39c81435b21f4dabbaccb
Author: Vasile Paraschiv <vasilep@fb.com>
Date:   Wed Mar 30 13:03:05 2016 -0700

    Improve coding style for class Binlog_info_manager

    Summary:
    Rename class Binlog_info_manager into Rdb_binlog_manager
    Make members start with m_

commit ad2fdaa823bff24e71e7b20c3b22c76d2688823c
Author: Yueh-Hsuan Chiang <yhchiang@fb.com>
Date:   Thu Mar 24 19:39:13 2016 -0700

    Correct a typo in a comment

    Summary: Correct a typo in a comment
```

The command line is using scripts at https://github.com/mdcallag/mytools/tree/master/bench/ibench. This runs 4 processes, each doing an insert to a different table and each with 2 query threads so there are 12 connections total. At the start of each test DROP DATABASE is done and I think the crash occurs around that time.

```
# dname is database device name in iostat output
dop=4; for i in $( seq 1 24 ); do bash np.sh 500000000 rocksdb "" 3 ~/b/myrocks/bin/mysql /path/to/db/data/dir $dop 10 20 0 $dname no 1 100 0 2 ; mkdir r.$i; mv o.* r.$i; done
```

**Comment by jkedgar** [comment]
Mark, I tried to run this, but it didn't run very long.  I got output like this a bunch of times.  Any idea what is wrong?

```
vmstat: no process killed
iostat: no process killed
Runtime error (func=(main), adr=17): Divide by zero
(standard_in) 1: syntax error
Runtime error (func=(main), adr=7): Divide by zero
/home/jkedgar/bin/np.sh: line 84: 3663658 Terminated              vmstat 10 &>o.vm.$sfx
/home/jkedgar/bin/np.sh: line 84: 3663659 Terminated              iostat -kx 10 &>o.io.$sfx
awk: fatal: division by zero attempted
awk: (FILENAME=- FNR=2) fatal: division by zero attempted
awk: fatal: division by zero attempted
awk: (FILENAME=- FNR=2) fatal: division by zero attempted
4 processes, 125000000 rows-per-process, 0 seconds, rows-per-second, rows-per-second-per-user, 0 queries, queries-per-second

iostat, vmstat normalized by insert rate
samp    r/s     rkb/s   wkb/s   r/q     rkb/q   wkb/q   ips

samp    cs/s    cpu/c   cs/q    cpu/q

iostat, vmstat normalized by query rate
samp    r/s     rkb/s   wkb/s   r/q     rkb/q   wkb/q   ips

samp    cs/s    cpu/c   cs/q    cpu/q

1.5M    /home/jkedgar/MySQLOnRocksDB/mysql-5.6/_build-5.6-Debug/mysql-test/var/mysqld.1/data

jkedgar  1827193 32.9  0.0 150368 25952 pts/0    Sl   Apr05 336:38 /data/users/jkedgar/MySQLOnRocksDB/mysql-5.6/_build-5.6-Debug/sql/mysqld --defaults-group-suffix=.1 --defaults-file=/home/jkedgar/MySQLOnRocksDB/mysql-5.6/_build-5.6-Debug/mysql-test/var/my.cnf --log-output=file --loose-debug-sync-timeout=600 --default-storage-engine=MyISAM --default-tmp-storage-engine=MyISAM --gdb --default-storage-engine=rocksdb --skip-innodb --default-tmp-storage-engine=MyISAM --rocksdb --binlog-format=row --gtid_mode=ON --enforce_gtid_consistency --log_bin --log_slave_updates --core-file --skip-innodb-dump-core-without-large-mem-buf
jkedgar  2801377  0.0  0.0 106112  1404 pts/2    S    Mar02   0:00 /bin/bash /data/users/jkedgar/fbsource/fbcode/buck-out/gen/third-party-buck/tools/bison/__bison__/bison.sh -y -d -o /data/users/jkedgar/fbsource/fbcode/buck-out/gen/mysqldump_tools/mysql.yy/mysql.yy.c /data/users/jkedgar/fbsource/fbcode/mysqldump_tools/mysql.yy
jkedgar  2801411  0.0  0.0 101824  1180 pts/2    S    Mar02   0:00 /tmp/sh_binary.XzVK9odA0Z/third-party-buck/tools/bison/bin/bison -y -d -o /data/users/jkedgar/fbsource/fbcode/buck-out/gen/mysqldump_tools/mysql.yy/mysql.yy.c /data/users/jkedgar/fbsource/fbcode/mysqldump_tools/mysql.yy
mysql    3151202  0.5  0.0 851476 104060 ?       Sl   Apr04  13:42 /usr/libexec/mysqld --defaults-file=/etc/mysql/my-3300.cnf --basedir=/usr --datadir=/dev/shm/itestdb/3300/ --plugin-dir=/usr/lib64/mysql/plugin --user=mysql --log-error=/dev/shm/itestdb/mysqld-3300.log --open-files-limit=32767 --pid-file=/var/run/mysqld/3300.pid --socket=/var/lib/mysql/mysql-3300.sock --port=3300
jkedgar  3663527  0.0  0.0 106120  1528 pts/3    S+   10:09   0:00 bash np.sh 500000000 rocksdb  3 /home/jkedgar/MySQLOnRocksDB/mysql-5.6/_build-5.6-Debug/client/mysql /home/jkedgar/MySQLOnRocksDB/mysql-5.6/_build-5.6-Debug/mysql-test/var/mysqld.1/data 4 10 20 0 no 1 100 0 2

insert and query rate at nth percentile
50th, 2 / 3 = 5990 insert, 7 query
75th, 2 / 3 = 5990 insert, 7 query
90th, 3 / 3 = rows_per_reports insert, inserted. query
95th, 3 / 3 = rows_per_reports insert, inserted. query
99th, 3 / 3 = rows_per_reports insert, inserted. query
50th, 2 / 3 = 5990 insert, 7 query
75th, 2 / 3 = 5990 insert, 7 query
90th, 3 / 3 = rows_per_reports insert, inserted. query
95th, 3 / 3 = rows_per_reports insert, inserted. query
99th, 3 / 3 = rows_per_reports insert, inserted. query
50th, 2 / 3 = 5990 insert, 7 query
75th, 2 / 3 = 5990 insert, 7 query
90th, 3 / 3 = rows_per_reports insert, inserted. query
95th, 3 / 3 = rows_per_reports insert, inserted. query
99th, 3 / 3 = rows_per_reports insert, inserted. query
50th, 2 / 3 = 5990 insert, 7 query
75th, 2 / 3 = 5990 insert, 7 query
90th, 3 / 3 = rows_per_reports insert, inserted. query
95th, 3 / 3 = rows_per_reports insert, inserted. query
99th, 3 / 3 = rows_per_reports insert, inserted. query
```

**Comment by mdcallag** [comment]
look at sb.1.o.*, my guess is that you don't have the Python MySQL package installed (MySqlDB). For Centos try "yum search mysqldb"

**Comment by mdcallag** [comment]
With gdb attached I get no crashes, repeating test without gdb attached

**Comment by jkedgar** [comment]
What should $dname be?  It appears I don't have that set.

**Comment by mdcallag** [comment]
Device name to grep iostat output

On Wed, Apr 6, 2016 at 10:33 AM, Jay Edgar notifications@github.com wrote:

> What should $dname be? It appears I don't have that set.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/228#issuecomment-206479924

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Ah, I misunderstood it as database name.  When I look at r.1/o.io.dop4.ns3 I see this.

```
Linux 3.10.72-74_fbk19_04713_g9a2573c (devbig206.ash4.facebook.com)   04/06/2016  _x86_64_  (32 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.27    0.03    0.56    0.11    0.00   98.03

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.76    18.47    3.75   11.36   395.11   888.07   169.87     0.29   19.05   2.57   3.88
fioa              0.00     0.00    3.03   24.48   316.99   625.29    68.50     0.07    2.52   0.05   0.14
```

I think I'm working on the flash drive, so I would want to set dname to 'fioa', right?

**Comment by mdcallag** [comment]
yes

On Wed, Apr 6, 2016 at 10:40 AM, Jay Edgar notifications@github.com wrote:

> Ah, I misunderstood it as database name. When I look at r.1/o.io.dop4.ns3
> I see this.
> 
> Linux 3.10.72-74_fbk19_04713_g9a2573c (devbig206.ash4.facebook.com)   04/06/2016  _x86_64_  (32 CPU)
> 
> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>            1.27    0.03    0.56    0.11    0.00   98.03
> 
> Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await  svctm  %util
> sda               0.76    18.47    3.75   11.36   395.11   888.07   169.87     0.29   19.05   2.57   3.88
> fioa              0.00     0.00    3.03   24.48   316.99   625.29    68.50     0.07    2.52   0.05   0.14
> 
> I think I'm working on the flash drive, so I would want to set dname to
> 'fioa', right?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/228#issuecomment-206482887

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Thanks.  It appears I have it working... at least it is no longer returning with text right away.  Now I'll just have to wait for it to fail.

**Comment by jkedgar** [comment]
I ran this over the weekend on my devserver and the 'du -k' reports that my .rocksdb subdirectory is about 23Gb, however I don't see anything in the mysqld error log indicating that it has attempted any drop database command.  Did I miss something that I was supposed to do?

**Comment by mdcallag** [comment]
DROP is done by np.sh, at start of each run
https://github.com/mdcallag/mytools/blob/master/bench/ibench/np.sh

On Mon, Apr 11, 2016 at 9:23 AM, Jay Edgar notifications@github.com wrote:

> I ran this over the weekend on my devserver and the 'du -k' reports that
> my .rocksdb subdirectory is about 23Gb, however I don't see anything in the
> mysqld error log indicating that it has attempted any drop database
> command. Did I miss something that I was supposed to do?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/228#issuecomment-208433506

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by mdcallag** [comment]
I was unable to reproduce this after several more days. I think it should be closed.

**Comment by jkedgar** [comment]
Okay.  Closing.  Let me know if you see it again.

**Comment by maykov** [comment]
I added this assert to make sure that cache blocks could be freed only when refcount is 0. If this assert fired, it means that somebody tried to free the block which was in use.
