### ISSUE TITLE
sysbench read-only loses too much performance on MyRocks secondary indexes

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#229]
Full results are here:
https://gist.github.com/mdcallag/b4682b0e9715b64f599c8c09e9dfdfed

The problem is that for the "read only" sysbench test, the QPS ratio (QPS using secondary index / QPS using PK) is much worse for MyRocks than for InnoDB. The problem is that MyRocks loses more QPS when using the secondary index compared to InnoDB. The ratio is  7385 / 12698 for InnoDB 5.7, 7678 / 13034 for InnoDB 5.6 vs 2557 / 12219 for MyRocks. So InnoDB gets almost 60% of QPS from secondary index compared to PK while MyRocks only gets ~21% of QPS from secondary compared to PK.

From the 32-threads column in "--- cached database, pk index" for the "read only" test the QPS is:
32 clients
12219  -> myrocks, FB MySQL 5.6
13034 -> MySQL 5.6.26, InnoDB, uncompressed
12698 -> MySQL 5.7.10, InnoDB, uncompressed

From the 32-threads column in "--- cached database, secondary index"
32  clients
2557 -> myrocks, FB MySQL 5.6
7678   -> MySQL 5.6.26, InnoDB, uncompressed
7385 -> MySQL 5.7.10, InnoDB, uncompressed

I will repeat the test after a fix for https://github.com/facebook/mysql-5.6/issues/200 is pushed, then I will debug a bit more and reassign.

**Comment by spetrunia** [comment]
I was really curious to try the benchmark myself also.  I've ran a CPU-bound load, trying to do something close, (details https://gist.github.com/spetrunia/2c6c9c9f2c9676f0b40b5d539b1e89a0) and got these numbers:

```
client_threads         8    16                24    32
innodb_sec_key  56294.43    65233.46    66462.74    66813.65
innodb_pk   70518.11    85847.51    88438.22    89749.98
innodb_pk_remote     35357.5    51129.54    62256.28    71953.19
rocksdb_sec_key 33440.93    39756.11    40194.6     40424.17
rocksdb_pk  60871.62       74459    76580.93    77442.88
```

Slowdown of secondary key run wrt the primary key run, in percent:

```
innodb_sec_key_slowdown_    20.17   24.01   24.85   25.56
rocksdb_sec_key_slowdown    45.06   46.61   47.51   47.80

```

**Comment by spetrunia** [comment]
![image](https://cloud.githubusercontent.com/assets/2734550/15256450/288d9f5a-194a-11e6-9d48-912d84bff20e.png)

**Comment by spetrunia** [comment]
ran perf for MyRocks run that uses PK  and MyRocks run that uses a secondary index: 
https://gist.github.com/spetrunia/6c2a8d30ce52a45bad06a804bc0efffe
don't see anything that one could jump to fix.

**Comment by gunnarku** [comment]
Will start replicating experiments internally as well to see if we will see similar trends from three different sources.

**Comment by gunnarku** [comment]
My results match quite closely Sergei's: with our internal default MyRocks settings I see on average `47%` slowdown for MyRocks when using a secondary index.

**Comment by spetrunia** [comment]
Example query (and EXPLAIN) that sysbench uses when `--oltp-point-select-all-cols  --oltp-secondary` are specified:

```
mysql> explain SELECT id, k, c, pad from sbtest1 where id=15627817;
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
| id | select_type | table   | type | possible_keys | key  | key_len | ref   | rows | Extra |
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
|  1 | SIMPLE      | sbtest1 | ref  | xid           | xid  | 4       | const |    1 | NULL  |
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
```

Without `--oltp-point-select-all-cols` it is:

```
mysql> explain SELECT c from sbtest1 where id=6770033;
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
| id | select_type | table   | type | possible_keys | key  | key_len | ref   | rows | Extra |
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
|  1 | SIMPLE      | sbtest1 | ref  | xid           | xid  | 4       | const |    1 | NULL  |
+----+-------------+---------+------+---------------+------+---------+-------+------+-------+
```

**Comment by spetrunia** [comment]
That is, both query are not using index-only scans.  I'm wondering, if one benchmarks index-only scans, will MyRocks also lag behind InnoDB or not?

**Comment by spetrunia** [comment]
An opportunity to do some optimization is: 

> if we are doing a scan on index that includes column $COL, then we will unpack $COL from the secondary index' key-value pair, and then again from the pk->row key-value pair.  The second can be avoided. 

But, when I look at the 'perf' output I've posted above, it doesn't seems that double-unpacking the columns is the problem.
