### ISSUE TITLE
compaction throughput cut in half from many threads incrementing shared global counters

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#231]
I get between 70k and 80k of inserts from iibench + MyRocks using current code. When I comment out the increment of the global counters in AddUserKey I get ~150k inserts/second. The real fix is to maintain local counters and then only increment the global counters once per SST file. Today the increment is once per key-value pair in an SST file.

The problem is increments to the rocksdb_num_sst_entry_\* counters in Rdb_tbl_prop_coll::AddUserKey. See https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/properties_collector.cc#L76

The test case is the insert benchmark at https://github.com/mdcallag/mytools/tree/master/bench/ibench
1) insert 2B rows across 8 tables
2) insert 200M rows across the same 8 tables 

Performance is measured for step 2 above. The compaction IO steps below shows how much slower each compaction step is when the global counter are increments (43.557 vs 9.849 seconds for L3). zlib starts with L5 so some slowdown is expected there.

Command lines for steps 1 and 2

```
# md2 is name of device in iostat output
dop=8; bash np.sh 2000000000 rocksdb "" 3 /data/mysql/myrocks/bin/mysql /data/mysql/myrocks/data $dop 10 20 0 md2 no 0 100 0 0 yes

dop=8; bash np.sh 200000000 rocksdb "" 3 /data/mysql/myrocks/bin/mysql /data/mysql/myrocks/data $dop 10 20 0 md2 no 1 100 0 0 no
```

Compaction IO stats for the current code. Look at the "Avg(sec)" column to see how slow each compaction step is. No compression is used for L0, L3, L4. zlib is used for L5, L6

```
** DB Stats **
Uptime(secs): 3216.9 total, 354.6 interval
Cumulative writes: 2001K writes, 800M keys, 1228K batches, 1.6 writes per batch, ingest: 21.81 GB, 6.94 MB/s
Cumulative WAL: 2001K writes, 0 syncs, 2001500.00 writes per sync, written: 21.81 GB, 6.94 MB/s
Cumulative compaction: 232.09 GB write, 73.88 MB/s write, 221.30 GB read, 70.44 MB/s read, 42197.4 seconds
Cumulative stall: 00:21:41.237 H:M:S, 40.5 percent

Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop  
---------------------------------------------------------------------------------------------------------------------------------------------------------------------  
  L0      6/5     459.70   0.2      0.0     0.0      0.0      23.3     23.3       0.0   0.0      0.0     13.0      1835       308    5.957       0      0  
  L3      3/3     100.18   0.0     28.2    28.2      0.0      27.0     27.0       0.0   1.0     17.0     16.3      1699        39   43.557    952M      0  
  L4     67/5    1228.32   1.0     36.3    15.5     20.8      36.2     15.3       6.2   2.3     10.8     10.7      3458       456    7.583   1266M      0  
  L5    568/50  11774.78   1.0     77.6    21.3     56.4      69.1     12.7       0.0   3.2      6.3      5.6     12683       620   20.456   4593M      0  
  L6   3175/21  107800.03   0.0     79.1    10.8     68.3      76.6      8.3       0.0   7.1      3.6      3.5     22523       254   88.674   2743M      0  
 Sum   3819/84  121363.02   0.0    221.3    75.8    145.5     232.1     86.6       6.2  10.0      5.4      5.6     42197      1677   25.162   9555M      0  
 Int      0/0       0.00   0.0     29.7     9.9     19.8      30.7     10.8       1.0  11.3      5.0      5.2      6037       224   26.951   1930M      0  
Flush(GB): cumulative 23.279, interval 2.714  
Stalls(count): 759 level0_slowdown, 683 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 97 total count
```

Compaction IO stats with the global increments remove. The "Avg(sec)" column is much better

```
** DB Stats **
Uptime(secs): 1350.9 total, 105.5 interval
Cumulative writes: 2001K writes, 800M keys, 1314K batches, 1.5 writes per batch, ingest: 21.81 GB, 16.53 MB/s
Cumulative WAL: 2001K writes, 0 syncs, 2001124.00 writes per sync, written: 21.81 GB, 16.53 MB/s
Cumulative compaction: 266.20 GB write, 201.78 MB/s write, 255.61 GB read, 193.76 MB/s read, 18088.0 seconds
Cumulative stall: 00:00:4.507 H:M:S, 0.3 percent

Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0     152.53   0.5      0.0     0.0      0.0      23.3     23.3       0.0   0.0      0.0     60.5       394       317    1.243       0      0
  L3      4/0      87.08   0.8     30.7    30.7      0.0      29.6     29.6       0.0   1.0     46.3     44.6       680        69    9.849   1088M      0
  L4     82/6    1267.04   1.0     44.3    19.3     24.9      44.0     19.1       2.8   2.3     46.4     46.1       977       611    1.599   1692M      0
  L5    553/65  11425.84   0.9     99.8    21.6     78.2      91.0     12.8       0.0   4.2     13.5     12.3      7570       659   11.488   6087M      0
  L6   3192/81  108219.13   0.0     80.8    11.2     69.5      78.2      8.7       0.0   7.0      9.8      9.5      8467       254   33.334   2893M      0
 Sum   3833/152 121151.63   0.0    255.6    82.9    172.7     266.2     93.5       2.8  11.4     14.5     15.1     18088      1910    9.470     11G      0
 Int      0/0       0.00   0.0     19.9     7.0     12.9      20.3      7.4       0.3  13.9     14.2     14.5      1437       159    9.039   1263M      0

```

**Comment by jkedgar** [comment]
How much did you comment out?  The entire function or just the switch at the top?  I'm interested in how much CollectStatsForRow() affects it.

**Comment by mdcallag** [comment]
just the switch at the top

On Wed, Apr 13, 2016 at 3:20 PM, Jay Edgar notifications@github.com wrote:

> How much did you comment out? The entire function or just the switch at
> the top? I'm interested in how much CollectStatsForRow() affects it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/231#issuecomment-209672396

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Weird - those are not atomic values nor are they being protected by a mutex (that I see), so I'm not sure why it would have made that much of a difference.

**Comment by mdcallag** [comment]
memory system traffic, made worse with contention, made even worse when
that is cross socket

On Wed, Apr 13, 2016 at 3:23 PM, Jay Edgar notifications@github.com wrote:

> Weird - those are not atomic values nor are they being protected by a
> mutex (that I see), so I'm not sure why it would have made that much of a
> difference.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/231#issuecomment-209673130

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
I'll see what I can do.

**Comment by mdcallag** [comment]
It would be nice if we didn't execute the same switch statement in AddUserKey and CollectStatsForRow. Doing it once will save a small amount of CPU from reducing branches.

**Comment by jkedgar** [comment]
I tried your original test and you are correct - it took a very long time.  I was doing this on my devserver, so I couldn't leave it running and not getting any work done, so I tried a smaller test - instead of 2B inserts followed by 200M, I ran 20M and then another 20M.  Here are my results.

With the original code I got this.

```
** DB Stats **
Uptime(secs): 8024.0 total, 0.4 interval
Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.28 MB/s
Cumulative WAL: 201K writes, 48 syncs, 4104.76 writes per sync, written: 2.20 GB, 0.28 MB/s
Cumulative compaction: 38.14 GB write, 4.87 MB/s write, 38.09 GB read, 4.86 MB/s read, 7137.7 seconds
Cumulative stall: 00:46:44.900 H:M:S, 35.0 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0       3.50   0.5      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.1       143       990    0.144       0      0
  L1      5/0     238.52   0.9     31.2     1.7     29.5      31.0      1.5       0.0  18.1      5.6      5.5      5725       121   47.315   1656M      0
  L2     19/0    1151.95   0.4      6.9     1.0      5.9       5.5     -0.4       0.4   5.3      5.6      4.4      1270        17   74.695    366M    78M
 Sum     26/0    1393.97   0.0     38.1     2.7     35.4      38.1      2.8       0.4  22.6      5.5      5.5      7138      1128    6.328   2023M    78M
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Flush(GB): cumulative 1.684, interval 0.000
Stalls(count): 98 level0_slowdown, 88 level0_slowdown_with_compaction, 2 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
```

Removing the code that incremented the global counters I got this:

```
** DB Stats **
Uptime(secs): 7867.9 total, 0.4 interval
Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.29 MB/s
Cumulative WAL: 201K writes, 47 syncs, 4190.46 writes per sync, written: 2.20 GB, 0.29 MB/s
Cumulative compaction: 42.51 GB write, 5.53 MB/s write, 42.43 GB read, 5.52 MB/s read, 7334.0 seconds
Cumulative stall: 00:54:59.888 H:M:S, 41.9 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      0/0       0.00   0.0      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.4       139      1000    0.139       0      0
  L1      4/0     209.24   0.8     37.1     1.7     35.4      36.8      1.4       0.0  21.6      6.1      6.0      6238       107   58.299   1881M  2734K
  L2     19/0    1188.50   0.5      5.4     1.1      4.3       4.0     -0.2       0.3   3.7      5.7      4.3       957        16   59.791    297M    73M
 Sum     23/0    1397.74   0.0     42.4     2.8     39.6      42.5      2.9       0.3  25.3      5.9      5.9      7334      1123    6.531   2178M    76M
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Flush(GB): cumulative 1.683, interval 0.000
Stalls(count): 103 level0_slowdown, 89 level0_slowdown_with_compaction, 4 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
```

I'm not seeing nearly the same impact that you are.  Just to experiment some more I went back to the original code and ran it again.  These are the results.

```
** DB Stats **
Uptime(secs): 7923.1 total, 0.4 interval
Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.28 MB/s
Cumulative WAL: 201K writes, 47 syncs, 4190.31 writes per sync, written: 2.20 GB, 0.28 MB/s
Cumulative compaction: 37.72 GB write, 4.88 MB/s write, 37.69 GB read, 4.87 MB/s read, 6698.1 seconds
Cumulative stall: 00:36:7.497 H:M:S, 27.4 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

CF_COMPACTION default
** Compaction Stats [default] **
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0       5.25   0.8      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.1       142       984    0.144       0      0
  L1     13/0     247.89   1.0     32.1     1.7     30.4      31.9      1.5       0.0  18.6      5.8      5.8      5632       127   44.345   1706M   408K
  L2     19/0    1138.09   0.4      5.6     1.2      4.4       4.2     -0.2       0.3   3.5      6.2      4.6       924        16   57.758    282M    77M
 Sum     35/0    1391.23   0.0     37.7     2.9     34.8      37.7      2.9       0.3  22.4      5.8      5.8      6698      1127    5.943   1989M    78M
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Flush(GB): cumulative 1.686, interval 0.000
Stalls(count): 86 level0_slowdown, 78 level0_slowdown_with_compaction, 2 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 1 memtable_compaction, 0 memtable_slowdown, interval 0 total count
```

Those numbers look better that the numbers with the global counters commented out.  Clearly I'm not seeing the same results, so I think I need to switch to a udb machine and try the full test again.

**Comment by mdcallag** [comment]
Reproduction requires high ingest rate, high ingest rate requires good IO,
my repro server has fast SSD. I doubt yours does given you get ~0.3 MB/sec
of ingest and ~5 MB/sec of compaction writes.

On Mon, Apr 18, 2016 at 10:27 AM, Jay Edgar notifications@github.com
wrote:

> I tried your original test and you are correct - it took a very long time.
> I was doing this on my devserver, so I couldn't leave it running and not
> getting any work done, so I tried a smaller test - instead of 2B inserts
> followed by 200M, I ran 20M and then another 20M. Here are my results.
> 
> With the original code I got this.
> 
> *\* DB Stats **
> Uptime(secs): 8024.0 total, 0.4 interval
> Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.28 MB/s
> Cumulative WAL: 201K writes, 48 syncs, 4104.76 writes per sync, written: 2.20 GB, 0.28 MB/s
> Cumulative compaction: 38.14 GB write, 4.87 MB/s write, 38.09 GB read, 4.86 MB/s read, 7137.7 seconds
> Cumulative stall: 00:46:44.900 H:M:S, 35.0 percent
> Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
> Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
> Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
> Interval stall: 00:00:0.000 H:M:S, 0.0 percent
> 
> ## Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
> 
>   L0      2/0       3.50   0.5      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.1       143       990    0.144       0      0
>   L1      5/0     238.52   0.9     31.2     1.7     29.5      31.0      1.5       0.0  18.1      5.6      5.5      5725       121   47.315   1656M      0
>   L2     19/0    1151.95   0.4      6.9     1.0      5.9       5.5     -0.4       0.4   5.3      5.6      4.4      1270        17   74.695    366M    78M
>  Sum     26/0    1393.97   0.0     38.1     2.7     35.4      38.1      2.8       0.4  22.6      5.5      5.5      7138      1128    6.328   2023M    78M
>  Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
> Flush(GB): cumulative 1.684, interval 0.000
> Stalls(count): 98 level0_slowdown, 88 level0_slowdown_with_compaction, 2 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
> 
> Removing the code that incremented the global counters I got this:
> 
> *\* DB Stats **
> Uptime(secs): 7867.9 total, 0.4 interval
> Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.29 MB/s
> Cumulative WAL: 201K writes, 47 syncs, 4190.46 writes per sync, written: 2.20 GB, 0.29 MB/s
> Cumulative compaction: 42.51 GB write, 5.53 MB/s write, 42.43 GB read, 5.52 MB/s read, 7334.0 seconds
> Cumulative stall: 00:54:59.888 H:M:S, 41.9 percent
> Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
> Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
> Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
> Interval stall: 00:00:0.000 H:M:S, 0.0 percent
> 
> ## Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
> 
>   L0      0/0       0.00   0.0      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.4       139      1000    0.139       0      0
>   L1      4/0     209.24   0.8     37.1     1.7     35.4      36.8      1.4       0.0  21.6      6.1      6.0      6238       107   58.299   1881M  2734K
>   L2     19/0    1188.50   0.5      5.4     1.1      4.3       4.0     -0.2       0.3   3.7      5.7      4.3       957        16   59.791    297M    73M
>  Sum     23/0    1397.74   0.0     42.4     2.8     39.6      42.5      2.9       0.3  25.3      5.9      5.9      7334      1123    6.531   2178M    76M
>  Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
> Flush(GB): cumulative 1.683, interval 0.000
> Stalls(count): 103 level0_slowdown, 89 level0_slowdown_with_compaction, 4 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
> 
> I'm not seeing nearly the same impact that you are. Just to experiment
> some more I went back to the original code and ran it again. These are the
> results.
> 
> *\* DB Stats **
> Uptime(secs): 7923.1 total, 0.4 interval
> Cumulative writes: 201K writes, 80M keys, 201K batches, 1.0 writes per batch, ingest: 2.20 GB, 0.28 MB/s
> Cumulative WAL: 201K writes, 47 syncs, 4190.31 writes per sync, written: 2.20 GB, 0.28 MB/s
> Cumulative compaction: 37.72 GB write, 4.88 MB/s write, 37.69 GB read, 4.87 MB/s read, 6698.1 seconds
> Cumulative stall: 00:36:7.497 H:M:S, 27.4 percent
> Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
> Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
> Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
> Interval stall: 00:00:0.000 H:M:S, 0.0 percent
> 
> CF_COMPACTION default
> *\* Compaction Stats [default] **
> 
> ## Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
> 
>   L0      3/0       5.25   0.8      0.0     0.0      0.0       1.7      1.7       0.0   0.0      0.0     12.1       142       984    0.144       0      0
>   L1     13/0     247.89   1.0     32.1     1.7     30.4      31.9      1.5       0.0  18.6      5.8      5.8      5632       127   44.345   1706M   408K
>   L2     19/0    1138.09   0.4      5.6     1.2      4.4       4.2     -0.2       0.3   3.5      6.2      4.6       924        16   57.758    282M    77M
>  Sum     35/0    1391.23   0.0     37.7     2.9     34.8      37.7      2.9       0.3  22.4      5.8      5.8      6698      1127    5.943   1989M    78M
>  Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
> Flush(GB): cumulative 1.686, interval 0.000
> Stalls(count): 86 level0_slowdown, 78 level0_slowdown_with_compaction, 2 level0_numfiles, 2 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 1 memtable_compaction, 0 memtable_slowdown, interval 0 total count
> 
> Those numbers look better that the numbers with the global counters
> commented out. Clearly I'm not seeing the same results, so I think I need
> to switch to a udb machine and try the full test again.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/231#issuecomment-211486499

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by jkedgar** [comment]
Here are the results on a 24 core UDB machine (the full test - not the scaled down version above).  I don't see the dramatic results you see.  I'll be trying a 48 core machine next.

Original code:

```
Original code:
** DB Stats **
Uptime(secs): 4085.3 total, 0.4 interval
Cumulative writes: 2001K writes, 802M keys, 2001K batches, 1.0 writes per batch, ingest: 22.23 GB, 5.57 MB/s
Cumulative WAL: 2001K writes, 49 syncs, 40026.30 writes per sync, written: 22.23 GB, 5.57 MB/s
Cumulative compaction: 183.04 GB write, 45.88 MB/s write, 190.78 GB read, 47.82 MB/s read, 31526.1 seconds
Cumulative stall: 00:13:12.972 H:M:S, 19.4 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

CF_COMPACTION   default
** Compaction Stats [default] **
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0     155.22   0.5      0.0     0.0      0.0      23.6     23.6       0.0   0.0      0.0     21.0      1152       328    3.513       0      0
  L3      5/0     139.70   2.7     27.6    27.6      0.0      26.4     26.4       0.0   1.0     24.8     23.8      1139        63   18.073    941M      0
  L4     26/4     613.02   0.9     45.0    16.7     28.3      44.5     16.2       5.8   2.7     15.0     14.9      3066       551    5.565   1736M   455K
  L5    211/30   5901.51   1.0     93.6    22.3     71.3      81.2      9.9       0.0   3.6      4.1      3.6     23160       639   36.244   8261M    34M
  L6    122/0    3696.89   0.0     24.6     4.2     20.4       7.3    -13.1       3.4   1.7      8.4      2.5      3008       130   23.142   2986M  2086M
 Sum    366/34  10506.34   0.0    190.8    70.7    120.0     183.0     63.0       9.2   7.7      6.2      5.9     31526      1711   18.426     13G  2121M
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Flush(GB): cumulative 23.627, interval 0.000
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 524 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
```

Removing increment of global counters:

```
** DB Stats **
Uptime(secs): 4227.4 total, 0.4 interval
Cumulative writes: 2001K writes, 802M keys, 2001K batches, 1.0 writes per batch, ingest: 22.23 GB, 5.38 MB/s
Cumulative WAL: 2001K writes, 50 syncs, 39242.57 writes per sync, written: 22.23 GB, 5.38 MB/s
Cumulative compaction: 190.14 GB write, 46.06 MB/s write, 204.77 GB read, 49.60 MB/s read, 32519.4 seconds
Cumulative stall: 00:14:46.508 H:M:S, 21.0 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

CF_COMPACTION   default
** Compaction Stats [default] **
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0     231.20   0.8      0.0     0.0      0.0      23.6     23.6       0.0   0.0      0.0     22.1      1093       329    3.323       0      0
  L3      2/0      66.19   1.3     27.4    27.4      0.0      26.2     26.2       0.0   1.0     24.9     23.9      1126        65   17.325    935M      0
  L4     28/6     693.07   1.0     49.7    17.8     31.9      49.2     17.3       4.8   2.8     14.2     14.1      3574       610    5.860   1925M   348K
  L5    200/34   5760.01   0.9     98.5    22.3     76.2      86.3     10.1       0.0   3.9      4.1      3.6     24336       654   37.212   8805M    13M
  L6    118/0    3641.58   0.0     29.1     4.4     24.7       4.8    -19.9       2.3   1.1     12.5      2.1      2389       125   19.115   3461M  2944M
 Sum    351/40  10392.04   0.0    204.8    72.0    132.8     190.1     57.4       7.1   8.0      6.4      6.0     32519      1783   18.239     15G  2958M
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Flush(GB): cumulative 23.625, interval 0.000
Stalls(count): 14 level0_slowdown, 12 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 504 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
```

**Comment by mdcallag** [comment]
Edited, I forgot that I was running iibench, not linkbench, so everything goes in the default column family. The result above shows Size(MB) == ~10G in the Sum column. How large was your database?

Can you check in the suggested fix sooner (increment the global counters less frequently) while you figure out the other changes?

**Comment by jkedgar** [comment]
- I just followed your instructions which said to run insert benchmark (iibench.py) using a shell script that runs np.sh twice - once creating the database and then inserting 2 billion rows and then using the existing database and inserting 200 million rows.  I restarted the database between the two and (I think) I am only measuring the second run.  My results show only two column families - `__system__` and `default`, so I just published the default ones.  Is there something else I should be configuring?  I didn't see anything about linkbench in your original description.
- In the first case (original code) a `du -k` on /data/mysql/3307/.rocksdb shows 101520392 (10G) after the first 2B and 14416680 (14G) after the next 200M.  In the second case (removed the global increments) I got 99221892 after the first 2B and 14454536 after the next 200M.

I will try to check in my current changes soon.  It needs more validation to make sure I don't break anything else.

**Comment by mdcallag** [comment]
For iibench 2B rows with PK index and 3 secondary indexes needs a lot more than 10G on disk.

**Comment by jkedgar** [comment]
I went back and looked at the database and there are only 200M entries in it, so I investigated further and found I was using an `np.sh` from before you created this issue.  The one I had always dropped and recreated the database - so the first 2B rows were tossed away.  I'll retry the test with this new np.sh.

**Comment by jkedgar** [comment]
I was able to validate the problem using the machine and settings that you provided.  I have also verified that my fix works.  You can access it at https://reviews.facebook.net/D57309 and it includes all of the following changes:
- Moved updating the global counters from AddUserKey() into Finish().  They are now atomic values so we won't lose any values.
- The previous code made a copy of the Rdb_key_def every time we switched key types in the compaction.  These had to be constructed and destructed during compaction and the purpose for this was that we didn't want to crash if that key type was being dropped while we were compacting.  Now the Rdb_key_def pointer is shared_ptr, so if a key type is dropped we will still have a valid Rdb_key_def object.
- Other miscellaneous changes (removed a call to '%' (mod) by using a separate counter, reorganized code so objects didn't need to get create until absolutely necessary, etc.)

**Comment by jkedgar** [comment]
I'm getting some failures from the tests, so don't expect this first iteration to work flawlessly yet.

**Comment by jkedgar** [comment]
Okay - I've fixed the test failures.  You can use the current version.

**Comment by jkedgar** [comment]
Committed (https://reviews.facebook.net/D57309)
