### ISSUE TITLE
Add automatic deadlock detection in MyRocks

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#235]

**Comment by lth** [comment]
https://reviews.facebook.net/D64623 to enable it.

Waiting on https://reviews.facebook.net/D64491 to land in RocksDB.

**Comment by lth** [comment]
https://reviews.facebook.net/D64623 is landed.

Note that unlike InnoDB, deadlock detection currently only works for row locks. If you do `LOCK TABLES`, the storage engine will not track your table locks.
