### ISSUE TITLE
RQG test failed with a core dump

### ISSUE THREAD

**Issue by mariadb-DanielLee** [facebook/mysql-5.6#237]
Build tested:

myrocks@rocksdb:~/builds/reptest/mysql-5.6$ git show
commit e4f22e08efe45e660197daa988daa03f32639725
Author: Jay Edgar jkedgar@fb.com
Date:   Wed Apr 6 12:48:20 2016 -0700

When running the RQG test "combinations.zz.combinations.yy", test failed with an environment error.  The test was performed on "Myrocks-to-InnoDB" replication.  The same test on "InnoDB-to-InnoDB" replication worked fine.

(gdb) thread apply all bt

Thread 7 (Thread 0x7f4b579df700 (LWP 43936)):
#0  0x00007f4b57a17eea in do_sigwaitinfo (info=0x7f4b579dec80, set=0x7f4b579dec00)

```
at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwaitinfo.c:54
```
#1  __GI___sigwaitinfo (set=0x7f4b579dec00, info=0x7f4b579dec80)

```
at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwaitinfo.c:81
```
#2  0x0000000000f7e635 in timer_notify_thread_func (arg=0x7ffc8502d740)

```
at /home/myrocks/builds/reptest/mysql-5.6/mysys/posix_timers.c:77
```
#3  0x00007f4b585d7182 in start_thread (arg=0x7f4b579df700) at pthread_create.c:312
#4  0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7f4b559db700 (LWP 43997)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000f7a832 in safe_cond_timedwait (cond=0x21503a0 <mysql_bin_log+1888>, mp=0x2150330 <mysql_bin_log+1776>,

```
abstime=0x7f4b559d81b0, file=0x17db708 "/home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h", 
line=1214) at /home/myrocks/builds/reptest/mysql-5.6/mysys/thr_mutex.c:278
```
#2  0x0000000000ef1fdd in inline_mysql_cond_timedwait (that=0x21503a0 <mysql_bin_log+1888>,

```
mutex=0x2150330 <mysql_bin_log+1776>, abstime=0x7f4b559d81b0)
at /home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h:1214
```
#3  0x0000000000f0188c in MYSQL_BIN_LOG::wait_for_update_bin_log (this=0x214fc40 <mysql_bin_log>, thd=0x2d116b0,

```
timeout=0x7f4b559d81b0) at /home/myrocks/builds/reptest/mysql-5.6/sql/binlog.cc:6459
```
#4  0x0000000000f1b4a8 in mysql_binlog_send (thd=0x2d116b0, log_ident=0x7f4b400053e0 "mysql-bin.000003", pos=192386,

```
slave_gtid_executed=0x0, flags=0) at /home/myrocks/builds/reptest/mysql-5.6/sql/rpl_master.cc:1992
```
#5  0x0000000000f17c6e in com_binlog_dump (thd=0x2d116b0, packet=0x2cf7de1 "", packet_length=26)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/rpl_master.cc:799
```
#6  0x0000000000c7f20e in dispatch_command (command=COM_BINLOG_DUMP, thd=0x2d116b0, packet=0x2cf7de1 "",

```
packet_length=26) at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:1935
```
#7  0x0000000000c7ccab in do_command (thd=0x2d116b0) at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:1132
#8  0x0000000000c4230d in do_handle_one_connection (thd_arg=0x2d116b0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_connect.cc:1101
```
#9  0x0000000000c41adb in handle_one_connection (arg=0x2d116b0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_connect.cc:929
```
#10 0x00007f4b585d7182 in start_thread (arg=0x7f4b559db700) at pthread_create.c:312
#11 0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7f4b59b34700 (LWP 43939)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f4b585df0d1 in do_sigwait (sig=0x7f4b59b33c80, set=<optimized out>)

```
at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwait.c:60
```
#1  __sigwait (set=0x7f4b59b33c90, sig=0x7f4b59b33c80)

```
at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwait.c:97
```
#2  0x0000000000a7fea5 in signal_hand (arg=0x0) at /home/myrocks/builds/reptest/mysql-5.6/sql/mysqld.cc:3851
#3  0x00007f4b585d7182 in start_thread (arg=0x7f4b59b34700) at pthread_create.c:312
#4  0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7f4b59c90940 (LWP 43934)):
#0  0x00007f4b57acd12d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000a86bd2 in handle_connections_sockets (admin=false)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/mysqld.cc:7665
```
#2  0x0000000000a85098 in handle_connections_sockets_all ()

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/mysqld.cc:6429
```
#3  0x0000000000a85d94 in mysqld_main (argc=18, argv=0x2baf0f0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/mysqld.cc:7065
```
#4  0x0000000000a799f6 in main (argc=3, argv=0x7ffc8502dcd8) at /home/myrocks/builds/reptest/mysql-5.6/sql/main.cc:25

Thread 3 (Thread 0x7f4b561dc700 (LWP 43938)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000f7a832 in safe_cond_timedwait (cond=0x218c080 myrocks::drop_index_interrupt_cond,

```
mp=0x218c000 <myrocks::drop_index_interrupt_mutex>, abstime=0x7f4b561dbbb0, 
file=0x18bea80 "/home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h", line=1214)
at /home/myrocks/builds/reptest/mysql-5.6/mysys/thr_mutex.c:278
```
#2  0x00000000012e16c6 in inline_mysql_cond_timedwait (that=0x218c080 myrocks::drop_index_interrupt_cond,

```
mutex=0x218c000 <myrocks::drop_index_interrupt_mutex>, abstime=0x7f4b561dbbb0)
at /home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h:1214
```
#3  0x00000000012f2489 in myrocks::drop_index_thread ()

```
at /home/myrocks/builds/reptest/mysql-5.6/storage/rocksdb/ha_rocksdb.cc:7192
```
#4  0x00007f4b585d7182 in start_thread (arg=0x7f4b561dc700) at pthread_create.c:312
#5  0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f4b569dd700 (LWP 43937)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000f7a832 in safe_cond_timedwait (cond=0x2183740 myrocks::stop_cond,

```
mp=0x2183680 <myrocks::stop_cond_mutex>, abstime=0x7f4b569dccc0, 
```

---Type <return> to continue, or q <return> to quit---
    file=0x18bea80 "/home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h", line=1214)
    at /home/myrocks/builds/reptest/mysql-5.6/mysys/thr_mutex.c:278
#2  0x00000000012e16c6 in inline_mysql_cond_timedwait (that=0x2183740 myrocks::stop_cond,

```
mutex=0x2183680 <myrocks::stop_cond_mutex>, abstime=0x7f4b569dccc0)
at /home/myrocks/builds/reptest/mysql-5.6/include/mysql/psi/mysql_thread.h:1214
```
#3  0x00000000012f5d32 in myrocks::background_thread ()

```
at /home/myrocks/builds/reptest/mysql-5.6/storage/rocksdb/ha_rocksdb.cc:8148
```
#4  0x00007f4b585d7182 in start_thread (arg=0x7f4b569dd700) at pthread_create.c:312
#5  0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f4b5598a700 (LWP 44020)):
#0  0x00007f4b57a16cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f4b57a1a0d8 in __GI_abort () at abort.c:89
#2  0x00007f4b57a0fb86 in __assert_fail_base (fmt=0x7f4b57b60830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",

```
assertion=assertion@entry=0x1729b40 "!check_datetime_range(ltime)", 
file=file@entry=0x1729908 "/home/myrocks/builds/reptest/mysql-5.6/sql-common/my_time.c", line=line@entry=1819, 
function=function@entry=0x1729da0 <__PRETTY_FUNCTION__.8788> "TIME_to_longlong_datetime_packed") at assert.c:92
```
#3  0x00007f4b57a0fc32 in __GI___assert_fail (assertion=0x1729b40 "!check_datetime_range(ltime)",

```
file=0x1729908 "/home/myrocks/builds/reptest/mysql-5.6/sql-common/my_time.c", line=1819, 
function=0x1729da0 <__PRETTY_FUNCTION__.8788> "TIME_to_longlong_datetime_packed") at assert.c:101
```
#4  0x0000000000d77ff1 in TIME_to_longlong_datetime_packed (ltime=0x7f4b55986a60)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql-common/my_time.c:1819
```
#5  0x0000000000dc5b17 in Field_datetimef::store_internal (this=0x7f4b442688c0, ltime=0x7f4b55986a60,

```
warnings=0x7f4b559867c0) at /home/myrocks/builds/reptest/mysql-5.6/sql/field.cc:6697
```
#6  0x0000000000dc2150 in Field_temporal_with_date::store_internal_with_round (this=0x7f4b442688c0,

```
ltime=0x7f4b55986a60, warnings=0x7f4b559867c0) at /home/myrocks/builds/reptest/mysql-5.6/sql/field.cc:5359
```
#7  0x0000000000dc1e67 in Field_temporal_with_date::store_time (this=0x7f4b442688c0, ltime=0x7f4b55986a60,

```
dec_arg=0 '\000') at /home/myrocks/builds/reptest/mysql-5.6/sql/field.cc:5301
```
#8  0x0000000000b025b0 in Field::store_time (this=0x7f4b442688c0, ltime=0x7f4b55986a60)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/field.h:728
```
#9  0x0000000000de7336 in copy_time_to_time (from=0x7f4b442c5d88, to=0x7f4b442688c0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/field_conv.cc:413
```
#10 0x0000000000de513b in do_field_time (copy=0x7f4b44354748)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/field_conv.cc:421
```
#11 0x0000000000de488a in do_copy_null (copy=0x7f4b44354748)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/field_conv.cc:268
```

---Type <return> to continue, or q <return> to quit---
#12 0x0000000000c5a7e0 in copy_fields (param=0x7f4b443544c8)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:4051
```
#13 0x0000000000c58650 in end_write_group (join=0x7f4b44163060, join_tab=0x7f4b44353d18, end_of_records=false)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:3273
```
#14 0x0000000000c5b5d3 in QEP_tmp_table::put_record (this=0x7f4b441635e0, end_of_records=false)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:4356
```
#15 0x0000000000c5c183 in QEP_tmp_table::put_record (this=0x7f4b441635e0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.h:242
```
#16 0x0000000000c538a7 in sub_select_op (join=0x7f4b44163060, join_tab=0x7f4b44353d18, end_of_records=false)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:1105
```
#17 0x0000000000c54572 in evaluate_join_record (join=0x7f4b44163060, join_tab=0x7f4b44353a18)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:1639
```
#18 0x0000000000c53b8c in sub_select (join=0x7f4b44163060, join_tab=0x7f4b44353a18, end_of_records=false)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:1314
```
#19 0x0000000000c53341 in do_select (join=0x7f4b44163060)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:950
```
#20 0x0000000000c512f8 in JOIN::exec (this=0x7f4b44163060)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_executor.cc:207
```
#21 0x0000000000cb8a53 in mysql_execute_select (thd=0x2d1ce60, select_lex=0x2d20868, free_join=true)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_select.cc:1133
```
#22 0x0000000000cb8d01 in mysql_select (thd=0x2d1ce60, tables=0x7f4b44162140, wild_num=0, fields=...,

```
conds=0x7f4b44162978, order=0x2d20a30, group=0x2d20968, having=0x0, select_options=2147748608, 
result=0x7f4b44163038, unit=0x2d20210, select_lex=0x2d20868)
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_select.cc:1254
```
#23 0x0000000000cb6c32 in handle_select (thd=0x2d1ce60, result=0x7f4b44163038, setup_tables_done_option=0)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_select.cc:126
```
#24 0x0000000000c8a203 in execute_sqlcom_select (thd=0x2d1ce60, all_tables=0x7f4b44162140, last_timer=0x7f4b559886a8)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:6019
```
#25 0x0000000000c82654 in mysql_execute_command (thd=0x2d1ce60, statement_start_time=0x7f4b55988580,

```
post_parse=0x7f4b559886a8) at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:3340
```
#26 0x0000000000c8d984 in mysql_parse (thd=0x2d1ce60,

```
rawbuf=0x7f4b44161600 "SELECT `col_datetime_default_null`, `col_datetime_default_null`, `col_datetime_key_default_null`, `col_char_64_latin1_default_null` FROM `table100_key_pk_parts_2_int_autoinc` WHERE `col_char_64_utf8` "..., 
length=320, parser_state=0x7f4b55988f00, last_timer=0x7f4b559886a8, async_commit=0x7f4b5598867b "", db="test", 
exit_admission_control=0x7f4b5598867c "") at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:7656
```
#27 0x0000000000c7e72e in dispatch_command (command=COM_QUERY, thd=0x2d1ce60, packet=0x2d217c1 "", packet_length=320)

---Type <return> to continue, or q <return> to quit---
    at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:1690
#28 0x0000000000c7ccab in do_command (thd=0x2d1ce60) at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_parse.cc:1132
#29 0x0000000000c4230d in do_handle_one_connection (thd_arg=0x2d1ce60)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_connect.cc:1101
```
#30 0x0000000000c41adb in handle_one_connection (arg=0x2d1ce60)

```
at /home/myrocks/builds/reptest/mysql-5.6/sql/sql_connect.cc:929
```
#31 0x00007f4b585d7182 in start_thread (arg=0x7f4b5598a700) at pthread_create.c:312
#32 0x00007f4b57ada47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

(gdb)

**Comment by hermanlee** [comment]
@dleeyh: Can you post the command line for this run?

**Comment by mariadb-DanielLee** [comment]
RQG test command:

```
  perl gentest.pl --dsn=dbi:mysql:host=localhost:port=3306:user=root:database=$testDB:mysql_socket=3307 --gendata=conf/transactions/combinations.zz --grammar=conf/transactions/combinations.yy --threads=3 --queries=10000 --sqltrace
```

**Comment by jkedgar** [comment]
This is caused by the same problem as #238.
