### ISSUE TITLE
env_posix.cc:(.text+0x2dd): undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by nshigit** [facebook/mysql-5.6#240]
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)

uname -a
Linux node52 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

rpm -qa | grep devtoolset
devtoolset-2-libstdc++-devel-4.8.2-15.1.el6.x86_64
devtoolset-2-gcc-4.8.2-15.1.el6.x86_64
devtoolset-2-libquadmath-devel-4.8.2-15.1.el6.x86_64
devtoolset-2-memstomp-0.1.4-11.el6.x86_64
devtoolset-2-elfutils-libelf-0.157-2.el6.x86_64
devtoolset-2-systemtap-runtime-2.1-8.el6.x86_64
devtoolset-2-elfutils-0.157-2.el6.x86_64
devtoolset-2-vc-2.1-4.el6.noarch
devtoolset-2-elfutils-libs-0.157-2.el6.x86_64
devtoolset-2-perl-Git-1.8.4-9.el6.noarch
devtoolset-2-systemtap-client-2.1-8.el6.x86_64
devtoolset-2-systemtap-devel-2.1-8.el6.x86_64
devtoolset-2-gdb-7.6.1-47.el6.x86_64
devtoolset-2-strace-4.7-13.el6.x86_64
devtoolset-2-valgrind-devel-3.9.0-8.3.el6.x86_64
devtoolset-2-runtime-2.1-4.el6.noarch
devtoolset-2-git-1.8.4-9.el6.x86_64
devtoolset-2-gcc-c++-4.8.2-15.1.el6.x86_64
devtoolset-2-systemtap-2.1-8.el6.x86_64
devtoolset-2-oprofile-0.9.8-6.el6.x86_64
devtoolset-2-toolchain-2.1-4.el6.noarch
devtoolset-2-dyninst-8.0-6dw.el6.x86_64
devtoolset-2-binutils-2.23.52.0.1-10.el6.x86_64
devtoolset-2-perftools-2.1-4.el6.noarch
devtoolset-2-valgrind-3.9.0-8.3.el6.x86_64
devtoolset-2-gcc-gfortran-4.8.2-15.1.el6.x86_64
devtoolset-2-dwz-0.11-1.el6.x86_64

cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/mysql-5.6 -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DWITH_EMBEDDED_SERVER=0

make
[  0%] Built target INFO_BIN
[  0%] Built target INFO_SRC
[  0%] Built target abi_check
[  1%] Built target zlib
[  6%] Built target strings
[ 17%] Built target mysys
[ 18%] Built target dbug
[ 19%] Built target mysys_ssl
[ 19%] Built target comp_err
[ 19%] Built target GenError
[ 19%] Built target federated
[ 39%] Built target rocksdb_se
Linking CXX executable ldb
librocksdb_se.a(env_posix.cc.o): In function `rocksdb::(anonymous namespace)::PosixEnv::NowNanos()':
env_posix.cc:(.text+0x2dd): undefined reference to`clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: **\* [storage/rocksdb/ldb] Error 1
make[1]: **\* [storage/rocksdb/CMakeFiles/ldb.dir/all] Error 2
make: **\* [all] Error 2

**Comment by zhaiwx1987** [comment]
I got same error while compiling the code. :(

```
librocksdb_se.a(env_posix.cc.o): In function `NowNanos':
/home/yinfeng.zwx/fb-mysql-5.6/rocksdb/util/env_posix.cc:588: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [storage/rocksdb/ldb] Error 1
make[1]: *** [storage/rocksdb/CMakeFiles/ldb.dir/all] Error 2
```

**Comment by jkedgar** [comment]
A change was made yesterday to include `-lrt` in the list of libraries to link.  The clock_gettime() function is supposed to be in that library.  Can you update and see if the problem is resolved?

**Comment by gunnarku** [comment]
Verified that after adding `-lrt` this works on Fedora (previously broken). Please re-activate if the issue manifests again.
