### ISSUE TITLE
MyRocks error 122 from storage engine when doing count on specific table

### ISSUE THREAD

**Issue by tplavcic** [facebook/mysql-5.6#242]
When I create a simple table in MyRocks like in the example below I get "ERROR 1030 (HY000): Got error 122 from storage engine" although I don't see how this can be related to quota or disk space (both should be fine and work with InnoDB).

The problematic insert seems to be "insert INTO t1 values (null,0), (null,0), (null,0);".
If it's not used then it works and it also seem to work if I don't use nulls for column "a" but some other values.

So when I have that table created I cannot do "SELECT COUNT(b) FROM t1;" the error is always the same.

FB-MyRocks:

```
mysql> CREATE TABLE t1(a INT, b INT NOT NULL);
Query OK, 0 rows affected (0.13 sec)

mysql> insert INTO t1 values (0,100),(1,2), (1,3), (2,2), (2,7), (2,-1), (3,10);
Query OK, 7 rows affected (0.00 sec)
Records: 7  Duplicates: 0  Warnings: 0

mysql> insert INTO t1 values (null,0), (null,0), (null,0);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT COUNT(b) FROM t1;
ERROR 1030 (HY000): Got error 122 from storage engine

mysql> SELECT COUNT(a) FROM t1;
+----------+
| COUNT(a) |
+----------+
|        7 |
+----------+
1 row in set (0.00 sec)

mysql> select * from t1;
+------+-----+
| a    | b   |
+------+-----+
|    0 | 100 |
|    1 |   2 |
|    1 |   3 |
|    2 |   2 |
|    2 |   7 |
|    2 |  -1 |
|    3 |  10 |
| NULL |   0 |
| NULL |   0 |
| NULL |   0 |
+------+-----+
10 rows in set (0.00 sec)
```

FB-InnoDB seems to work fine:

```
mysql> CREATE TABLE t1(a INT, b INT NOT NULL);
Query OK, 0 rows affected (0.28 sec)

mysql> insert INTO t1 values (0,100),(1,2), (1,3), (2,2), (2,7), (2,-1), (3,10);
Query OK, 7 rows affected (0.09 sec)
Records: 7  Duplicates: 0  Warnings: 0

mysql> insert INTO t1 values (null,0), (null,0), (null,0);
Query OK, 3 rows affected (0.03 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT COUNT(b) FROM t1;
+----------+
| COUNT(b) |
+----------+
|       10 |
+----------+
1 row in set (0.00 sec)

mysql> SELECT COUNT(a) FROM t1;
+----------+
| COUNT(a) |
+----------+
|        7 |
+----------+
1 row in set (0.00 sec)

mysql> select * from t1;
+------+-----+
| a    | b   |
+------+-----+
|    0 | 100 |
|    1 |   2 |
|    1 |   3 |
|    2 |   2 |
|    2 |   7 |
|    2 |  -1 |
|    3 |  10 |
| NULL |   0 |
| NULL |   0 |
| NULL |   0 |
+------+-----+
10 rows in set (0.00 sec)
```

**Comment by yoshinorim** [comment]
@tplavcic Which MyRocks revision did you use? We committed a fix (https://reviews.facebook.net/D57633) a few days ago. If you used older revision, could you update the repo by "git pull --rebase" and try again?

**Comment by tplavcic** [comment]
@yoshinorim Thanks, seem I was using the commit "c35c6c88eec6a1623129149a420d381bc4d0e773" which is one before the mentioned change. I will re-check with the latest version and close this if it doesn't apply any more

**Comment by tplavcic** [comment]
With the latest version it seems to work fine so it can be closed (I don't have permissions to do so).

**Comment by yoshinorim** [comment]
Thanks for checking!
