### ISSUE TITLE
SHOW ENGINE ROCKSDB TRANSACTION STATUS should print rows_inserted|updated|deleted

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#243]
It would be useful if SHOW ENGINE ROCKSDB TRANSACTION STATUS prints uncommitted row modifications for each session. For example, it will be easier to find a long running transaction that has modified millions of records.

**Comment by alxyang** [comment]
Should be closed by https://github.com/facebook/mysql-5.6/commit/2fc12aaa52e12255a108c69489eb8bee11f050af
