### ISSUE TITLE
Support 'sync per second' similar to innodb_flush_log_at_trx_commit=2

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#245]
See http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit for InnoDB details. I'd like an option to make MyRocks durable once per second to bound the amount of commits that can be lost. We need a background thread within MyRocks to make the call (do a write with an empty write batch with sync=true requested)

**Comment by yoshinorim** [comment]
"rocksdb_background_sync=1" is the option to sync WAL every 1 second.

**Comment by mdcallag** [comment]
:)
