### ISSUE TITLE
Needs better error handling on rocksdb_strict_collation_exceptions regex syntax error

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#248]
How to repeat:

```
my.cnf
[mysqld]
...
rocksdb_strict_collation_exceptions='t1,*delme'
```

Then

```
create table x (id char(30) primary key) collate latin1_swedish_ci;
```

mysqld crashes like this.

```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
20:58:22 UTC - mysqld got signal 6 ;
```

**Comment by hermanlee** [comment]
We should ignore any regex fragment that throws back an exception. When the variable is being set during runtime by "set global" or initialized during server startup by the my.cnf file, we should test for invalid regex fragments and issue a warning to the error log.

**Comment by gunnarku** [comment]
Already fixed.
