### ISSUE TITLE
Fast data loading in MyRocks

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#256]
Let's investigate ways to write SST files directly via data loading.

**Comment by mdcallag** [comment]
Can we have a private instance of the vector memtable?

**Comment by yoshinorim** [comment]
There is a use case to load data into instances that serve production read/write traffics, so vector memtable can't be always used. It is guaranteed that the load target index/table is not used by anybody else. There was a discussion about bypassing memtable.

**Comment by mdcallag** [comment]
Why can't we have a separate vector memtable only visible to the loading
session?

On Tue, May 24, 2016 at 11:16 AM, Yoshinori Matsunobu <
notifications@github.com> wrote:

> There is a use case to load data into instances that serve production
> read/write traffics, so vector memtable can't be always used. It is
> guaranteed that the load target index/table is not used by anybody else.
> There was a discussion about bypassing memtable.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/256#issuecomment-221351660

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by gunnarku** [comment]
This is bulk load.
