### ISSUE TITLE
Support 'fast index create' for RocksDB

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#26]
<a href="https://github.com/jonahcohen"><img src="https://avatars.githubusercontent.com/u/8269165?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jonahcohen](https://github.com/jonahcohen)**
_Wednesday Jan 07, 2015 at 23:04 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/12_

---

From @mdcallag:

This should avoid doing a table copy when adding an index. See http://dev.mysql.com/doc/refman/5.5/en/innodb-create-index.html

**Comment by alxyang** [comment]
can we close either this or https://github.com/facebook/mysql-5.6/issues/182 since they seem to be duplicates

**Comment by mdcallag** [comment]
ok

On Wed, Mar 2, 2016 at 4:29 PM, Alex Yang notifications@github.com wrote:

> can we close either this or #182
> https://github.com/facebook/mysql-5.6/issues/182 since they seem to be
> duplicates
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/26#issuecomment-191507588.

## 

Mark Callaghan
mdcallag@gmail.com
