### ISSUE TITLE
Implement Read Free Replication

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#27]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Wednesday Jan 14, 2015 at 01:48 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/21_

---

This is about implementing read-free slave, similar to what TokuDB has recently implemented.

The idea is that one can process RBR events without making Get() calls or scans. They have sufficient information to issue Put/Delete calls.

RocksDB SE will support RBR only so RBR restriction is not a problem.

**Comment by yoshinorim** [comment]
Note that SingleDelete() can't be used if Read Free Replication is used.

**Comment by yoshinorim** [comment]
I talked with Anthony and Siying about this. SingleDelete() used to have an assertion that it aborted if there was no matching Put, but the logic no longer exists. This means it's possible to add Reed Free Replication support in current MyRocks. It's worth revisiting this task again.

**Comment by yoshinorim** [comment]
Diffs:
https://reviews.facebook.net/D55437
https://reviews.facebook.net/D55449
