### ISSUE TITLE
export counters for number of point and range queries done by RocksDB

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#281]
I did not see counters in SHOW GLOBAL STATUS output the number of point and range queries done by RocksDB. I prefer to have one for each.  They would help debug problems like https://github.com/facebook/mysql-5.6/issues/279

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/f90e91169ddfa19736fd409d822f5d351d959441
