### ISSUE TITLE
change histograms from fixed width to scaled

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#282]
Histograms used for response time that we added to MySQL use a fixed width. These are hard to use for fast & slow storage devices without changing my.cnf. For example, I looked at a server today for binlog fsync latency and the bucket width is 16ms, so all operations go to the first bucket.

My suggestion is to scale the bucket, for example -- let bucket 0 cover 0 to 10us, bucket 1 cover 2X or 1.5X the time (10us to 30us or 10us to 25us), bucket 2 covers 4X or 2.25X the time range compared to bucket 0, etc. That will allow fewer buckets to be defined and let us use the same histogram settings for slow and fast storage devices. 

The histogram code could have two configuration options. 
1) Width (time range) for bucket 0
2) scale factor -- 2X or 1.5X by which the width of the next bucket grows

```
Latency_histogram_binlog_fsync_0-16ms   3172149
Latency_histogram_binlog_fsync_16-32ms  6
Latency_histogram_binlog_fsync_32-48ms  6       
Latency_histogram_binlog_fsync_48-64ms  4       
Latency_histogram_binlog_fsync_64-80ms  0
Latency_histogram_binlog_fsync_80-96ms  0
Latency_histogram_binlog_fsync_96-112ms 0
Latency_histogram_binlog_fsync_112-128ms        0
Latency_histogram_binlog_fsync_128-144ms        0
Latency_histogram_binlog_fsync_144-160ms        0
Latency_histogram_binlog_fsync_160-176ms        0
Latency_histogram_binlog_fsync_176-192ms        0
Latency_histogram_binlog_fsync_192-208ms        0
Latency_histogram_binlog_fsync_208-224ms        0
Latency_histogram_binlog_fsync_224-240ms        0
```

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/b3c120260
