### ISSUE TITLE
provide counters to let us determine the average number of transactions with group commit

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#283]
This is a feature request. I'd like two SHOW GLOBAL STATUS counters from which I can compute  the average number of transactions in a group'ed commit. One of these counters might exist today:
1) total number of group commits. I don't think that Binlog_fsync_count is sufficient assuming that is only incremented when sync_binlog=1. I also want to compute this avg when sync_binlog=0.
2) total number of committed transactions

**Comment by sargunv** [comment]
We have this: https://github.com/facebook/mysql-5.6/commit/4b8125171ad814aab39a6cae459a9e704e5708a1 which is tracking something similar. Is this good enough for you, or do you still need these two counters?

**Comment by mdcallag** [comment]
that is good enough
