### ISSUE TITLE
mysqlbinlog reconnect has memory leak

### ISSUE THREAD

**Issue by AllenChien** [facebook/mysql-5.6#291]
By reading mysqlbinlog.cc, when mysqlbinlog reconnects, it always allocates new MYSQL handle 'mysql';
It should call mysql_close to release allocated 'mysql'.

Simple fix like this:
static Exit_status safe_connect()
{
  if (NULL != mysql) {
    mysql_close(mysql);
  }
  mysql= mysql_init(NULL);

  if (!mysql)
  {
    error("Failed on mysql_init.");
    return ERROR_STOP;
  }

**Comment by gunnarku** [comment]
This issue got fixed with https://github.com/facebook/mysql-5.6/commit/304feac29b2eb7cee698808c6a0f1f3c12e392bb.

**Comment by laurynas-biveinis** [comment]
This issue is http://bugs.mysql.com/bug.php?id=81675 at Oracle bug db
