### ISSUE TITLE
show_table_status test fails

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#294]
rocksdb.show_table_status test fails. I can observe this on multiple machines, it always fails in the same way:

```
rocksdb.show_table_status                [ fail ]
        Test ended at 2016-08-04 16:20:01

CURRENT_TEST: rocksdb.show_table_status
--- /home/ubuntu/mysql-5.6/mysql-test/suite/rocksdb/r/show_table_status.result  2016-08-04 18:52:41.097375000 +0300
+++ /home/ubuntu/mysql-5.6/mysql-test/var/log/show_table_status.reject  2016-08-04 19:20:00.901375000 +0300
@@ -12,7 +12,7 @@
 t3     ROCKSDB 10      Fixed   1000    0       0       0       0       0       NULL    NULL    NULL    NULL    utf8_general_ci NULL
 SHOW TABLE STATUS WHERE name LIKE 't2';
 Name   Engine  Version Row_format      Rows    Avg_row_length  Data_length     Max_data_length Index_length    Data_free       Auto_increment      Create_time     Update_time     Check_time      Collation       Checksum        Create_options  Comment
-t2     ROCKSDB 10      Fixed   10000   6       65000   0       0       0       NULL    NULL    NULL    NULL    latin1_swedish_ci       NULL
+t2     ROCKSDB 10      Fixed   10000   13      134659  0       0       0       NULL    NULL    NULL    NULL    latin1_swedish_ci       NULL
 DROP TABLE t1, t2, t3;
 CREATE DATABASE `db_new..............................................end`;
 USE `db_new..............................................end`;
```

**Comment by spetrunia** [comment]
Looking at the SST file:

```
# data blocks: 34
# entries: 9998
raw key size: 159968
raw average key size: 16.000000
raw value size: 9998
raw average value size: 1.000000
...
```

Looking at DDL for table t2:
They key is 8 bytes Rocksdb internals + 4 bytes index_nr + 4 bytes PK value.
The value is 1 NULL-flags byte.

The new stats look closer to truth for me, I would just update the .result file.
The question is, does this test currently succeed for anybody (because if I update .result, it will start to fail for them...)

**Comment by jkedgar** [comment]
This test is passing for me on the current source.  Are you trying this on what is checked in or on something that has other fixes for you?

**Comment by jkedgar** [comment]
While your calculation may be correct, prefix encoding may reduce the number of bytes per row quite a bit.

**Comment by yoshinorim** [comment]
I could reproduce the error on my personal VPS. I think the estimated rows/data_length are affected by built in compression library. I'll file a diff to make these numbers hided.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D61605
