### ISSUE TITLE
can't run mysql-test case in myrocks

### ISSUE THREAD

**Issue by chuckcai** [facebook/mysql-5.6#305]
When I try to  run mysql-test case by using mysql-test-run.pl,there are something wrong.It seems by default,  rocksdb is not default engine. So, If I want to run testcase, for example, run allow_os_buffer.test, I need do two things:
1. add allow_os_buffer.opt file with content as follows:
--default-storage-engine=rocksdb
--rocksdb
--skip-innodb
--default-tmp-storage-engine=MyISAM
2 modify mysql-test-run.pl, sub mysql_install_db:
  mtr_add_arg($args, "--default-storage-engine=rocksdb");
  mtr_add_arg($args, "--rocksdb");
  mtr_add_arg($args, "--skip-innodb");
  mtr_add_arg($args, "--default-tmp-storage-engine=MyISAM");

If I should add *.opt by every case, i think it's troublesome. Is there any fast path t
o run testcase in myrocks? 

thank you!

**Comment by laurynas-biveinis** [comment]
1. can be simplified, if all your tests are in a single suite, by creating a suite.opt file with these options in the suite t/ subdirectory.
2. is http://bugs.mysql.com/bug.php?id=72615.

Even with 2. fixed I'm not aware of an easy way to run an existing suite (say engines/funcs) for a different storage engine. It's possible to do that by --mysqld=--plugin-load... options to MTR, but there is no single invocation recipe that works for both in-source and out-of-source builds.

**Comment by chuckcai** [comment]
I followed suggestion 1,  and create suite.opt file in dir mysql-test/suite/rocksdb, the content is below:
--rocksdb
--default-storage-engine=rocksdb
--skip-innodb
--default-tmp-storage-engine=MyISAM

but it was doesn't work. Now I run testcase use  command as below:
./mysql-test-run.pl  --mysqld=--rocksdb --mysqld=--default-storage-engine=rocksdb --mysqld=--skip-innodb --mysqld=--default-tmp-storage-engine=MyISAM --suite=rocksdb

**Comment by laurynas-biveinis** [comment]
The suite.opt file must be in mysql-test/suite/rocksdb/t directory, you seem to have placed it in its parent instead

**Comment by jkedgar** [comment]
This looks like it has been resolved.  Closing.
