### ISSUE TITLE
Using the new sst file writer interface to bulk load the primary key can result in tables with missing rows in the primary index

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#307]
Dumping an innodb instance and restoring it to a myrocks instance with bulk_loading enabled and utilizing the new sst filewriter code can result in mismatch number of rows between the primary and secondary indexes.

The sst filewriter code currently does not add index statistics for the primary key, so the estimate number of rows for the primary key much lower than the actual number of rows.

**Comment by yoshinorim** [comment]
The latter issue will be resolved by https://reviews.facebook.net/D62253. Does it affect the former issue too?

**Comment by jkedgar** [comment]
I'm investigating that right now.  I have confirmed that with D62253 we are seeing statistics accumulated but I have not yet determined whether this has any effect on the difference between primary and secondary indexes.

**Comment by alxyang** [comment]
can we close this?
