### ISSUE TITLE
MAX_STATEMENT_TIME support?

### ISSUE THREAD

**Issue by DABH** [facebook/mysql-5.6#317]
Hi,

I'm using the client library from this repo in a C++ program.  Everything has worked well so far.

If a query takes too long, I want to be able to have my MySQL server timeout and return an error code through the client.  In MySQL 5.7 and various forks of 5.6 etc., there is support for the server-side option MAX_STATEMENT_TIME, which does exactly what I describe.  With the server I'm using (Percona 5.6), I can successfully use MAX_STATEMENT_TIME; for example, via the standard mysql shell on Linux, I can execute a long query, and I get an error code 1866 from the server (with some associated non-zero state).

However, via the libwebscalesql client, I don't see any error.  The query terminates, as desired, but the client library returns 0 from mysql_error and 00000 from mysql_state, even though the server is returning an error to the client.  Thus, for example, I don't have a good way of differentiating between a query that timed out and a query that returned an empty result set.

(Note that with other more common MySQL errors, the client library does report the correct error codes and MySQL states, so I don't think there's a problem with my code.)

Should the libwebscalesql client support errors due to MAX_STATEMENT_TIME being exceeded on the server (e.g. error code 1866)?  If not, is it possible to add support?  I'm not sure where errors are defined and handled in the codebase, or I would look at adding handling for this error myself.  I did search the repo and saw several mentions of MAX_STATEMENT_TIME, which gave me hope.  Thanks for any feedback!

P.S. I'm working from the webscalesql-5.6.27.75 branch

**Comment by jkedgar** [comment]
I looked into this problem and it appears that the error is not returned from mysql_query (or mysql_real_query) as you mentioned but is returned when you attempt to retrieve the result set (i.e. from mysql_store_results).  I'm not sure why it was done this way, but I suspect that is the way Oracle designed it.

I'm going to close this issue.  If you can show that upstream Oracle has different behavior, please reopen the issue.
