### ISSUE TITLE
auto_cf is not work when column family is reverse 

### ISSUE THREAD

**Issue by justfortaste** [facebook/mysql-5.6#321]
auto_cf is not work when column family is reverse 

```
CREATE TABLE t1 (a INT, b CHAR(8), pk INT AUTO_INCREMENT ,PRIMARY KEY(pk) comment 'cf_1', key idx1(a) comment '$per_index_cf', key idx2(b) comment 'rev:$per_index_cf') ENGINE=rocksdb;
INSERT INTO t1 (a,b) VALUES (1,'a'),(2,'b');

select * from INFORMATION_SCHEMA.ROCKSDB_DDL where table_name='t1';
TABLE_SCHEMA    TABLE_NAME      PARTITION_NAME  INDEX_NAME      COLUMN_FAMILY   INDEX_NUMBER    INDEX_TYPE      KV_FORMAT_VERSION       CF
test    t1      NULL    PRIMARY 2       260     1       11      cf_1
test    t1      NULL    idx1    3       261     2       11      test.t1.idx1
test    t1      NULL    idx2    4       262     2       11      rev:$per_index_cf
```

rev:$per_index_cf should be rev:test.t1.idx2

**Comment by yoshinorim** [comment]
Sorry for late reply. auto_cf is actually experimental feature and is not recommended in production use cases. Auto reverse cf is not implemented yet, but we're not sure if we support in the future. If you have many (100~ or even more) indexes in an instance, 100~ column families are created with auto cf. RocksDB does not perform well if having so many column families. Operation and monitoring can be harder too (i.e. MemTable is allocated per column family. Total memtable size will be MemTable size \* number of CFs \* number of memtables per CF, which can be huge if not setting memtable size very low).

General recommendation is having limited number of (less than 10) column families per instance and share CFs from multiple indexes.

**Comment by gunnarku** [comment]
We should remove `auto_cf` support.

**Comment by yizhang82** [comment]
We have already removed `auto_cf` from MyRocks back in [this commit](https://github.com/facebook/mysql-5.6/commit/27e1273f266b78e370c376d11999dcf5cc216a37) back in 2017. Today you'll get a warning if existing database has `auto_cf`.
