### ISSUE TITLE
Address the TODO comment on Table_ddl_manager::put

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#33]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maykov](https://github.com/maykov)**
_Thursday Apr 02, 2015 at 06:35 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/50_

---

This function modifies ddl_hash and index_num_to_keydef.
However, these changes need to be reversed if dict_manager.commit fails
See the discussion here: https://reviews.facebook.net/D35925#inline-259167

**Comment by hermanlee** [comment]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoshinorim](https://github.com/yoshinorim)**
_Wednesday Aug 12, 2015 at 23:52 GMT_

---

@maykov  Now MyRocks always aborts if dict_manager.commit() fails. Do we still need to fix this?

**Comment by alxyang** [comment]
came across this comment, while working on inplace alter table.  Are we still planning to fix this? Can I assume that dict_manager.commit will not fail (or if it does, MyRocks will abort anyways)

**Comment by hermanlee** [comment]
I think there is probably enough functionality depending on dict_manager.commit() succeeding that if it fails, MyRocks needs to abort. So you can depend on this requirement. Do others feel this is the case?

**Comment by yoshinorim** [comment]
MyRocks aborts on dict_manager.commit() errors and we are unlikely to change it. So you can rely on it.

**Comment by alxyang** [comment]
ok, sounds good.
