### ISSUE TITLE
Investigate what happens if STL allocation causes OOM

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#34]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maykov](https://github.com/maykov)**
_Tuesday Apr 14, 2015 at 22:48 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/52_

---

STL relies on exceptions to handle OOM. We should check that opreator new is not overloaded to return NULL. We should also add exception handlers into all high level handler functions.

**Comment by hermanlee** [comment]
<a href="https://github.com/spetrunia"><img src="https://avatars.githubusercontent.com/u/2734550?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spetrunia](https://github.com/spetrunia)**
_Sunday May 24, 2015 at 07:54 GMT_

---

I think I have accidentally hit this on a debug build. The following happened:

```
2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 202
2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 197
2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 198
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by hermanlee** [comment]
<a href="https://github.com/mdcallag"><img src="https://avatars.githubusercontent.com/u/1641037?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdcallag](https://github.com/mdcallag)**
_Sunday May 24, 2015 at 22:11 GMT_

---

I got that once

On Sunday, May 24, 2015, Sergei Petrunia notifications@github.com wrote:

> I think I have accidentally hit this on a debug build. The following
> happened:
> 
> 2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 202
> 2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 197
> 2015-05-24 00:36:35 10087 [Note] RocksDB: Finished filtering dropped index 198
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MySQLOnRocksDB/mysql-5.6/issues/52#issuecomment-104989113
> .

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by hermanlee** [comment]
<a href="https://github.com/igorcanadi"><img src="https://avatars.githubusercontent.com/u/1091023?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [igorcanadi](https://github.com/igorcanadi)**
_Tuesday May 26, 2015 at 18:34 GMT_

---

huh yeah. we never really looked at what happens when OOM. we should never corrupt the data, but rocksdb will likely crash hard.

**Comment by hermanlee** [comment]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maykov](https://github.com/maykov)**
_Friday Jun 05, 2015 at 22:40 GMT_

---

So it is important

**Comment by gunnarku** [comment]
Internal investigation completed. Behavior observed, documented, and understood for various scenarios. To decide if we'll change the _status quo_ (`SIGABRT` because of an unhandled exception which leads to process teardown) will require data from the field and further discussion.
