### ISSUE TITLE
target_file_size_base & max_bytes_for_level_base are not in SHOW GLOBAL VARIABLES

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#349]
These are important. See https://github.com/facebook/mysql-5.6/issues/347 for an example. How many other useful variables do we not display thus requiring people to find data/.rocksdb/LOG to explain configuration problems.

**Comment by mdcallag** [comment]
I'd also like a SQL command to show all configuration options that are currently dumped to .rocksdb/LOG

**Comment by yoshinorim** [comment]
These are CF variables so they are not printed in show global variables, unless explicitly setting at rocksdb_default_cf_options. But we have i_s and you can query as follows.

```
select * from information_schema.rocksdb_cf_options where option_type='target_file_size_base';
```

**Comment by yoshinorim** [comment]
Documented here: https://github.com/facebook/mysql-5.6/wiki/Information-Schema

I'm closing this since querying from i_s would be sufficient.
