### ISSUE TITLE
Expose SST file properties through the information schema

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#35]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maykov](https://github.com/maykov)**
_Thursday Apr 23, 2015 at 21:45 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/55_

---

This will make it easier to debug issues and write tests

**Comment by maykov** [comment]
Implemented here: https://github.com/facebook/mysql-5.6/commit/6437dfed583a442760f6a0444ce564b1e4e699eb
