### ISSUE TITLE
mysql-5.6/unittest/gunit/test_utils.cc:92:3: error: invalid use of member function ‘THD* my_testing::Server_initializer::thd() const’ (did you forget the ‘()’ ?)

### ISSUE THREAD

**Issue by javacty** [facebook/mysql-5.6#357]
Ubuntu 16.04
gcc 6.2.0

export WITH_SNAPPY=/usr
export WITH_BZ2=/usr
export WITH_LZ4=/usr
export WITH_ZSTD=/usr
<pre>
[ 78%] Building C object storage/myisam/CMakeFiles/myisam.dir/rt_split.c.o
/opt/mysql-5.6/unittest/gunit/test_utils.cc: In member function ‘void my_testing::Server_initializer::SetUp()’:
/opt/mysql-5.6/unittest/gunit/test_utils.cc:92:3: error: invalid use of member function ‘THD\* my_testing::Server_initializer::thd() const’ (did you forget the ‘()’ ?)
   thd->variables.pseudo_thread_id= thd->set_new_thread_id();
   ^~~
/opt/mysql-5.6/unittest/gunit/test_utils.cc:92:6: error: base operand of ‘->’ is not a pointer
   thd->variables.pseudo_thread_id= thd->set_new_thread_id();
      ^~
/opt/mysql-5.6/unittest/gunit/test_utils.cc:92:36: error: invalid use of member function ‘THD\* my_testing::Server_initializer::thd() const’ (did you forget the ‘()’ ?)
   thd->variables.pseudo_thread_id= thd->set_new_thread_id();
                                    ^~~
/opt/mysql-5.6/unittest/gunit/test_utils.cc:92:39: error: base operand of ‘->’ is not a pointer
   thd->variables.pseudo_thread_id= thd->set_new_thread_id();
                                       ^~
[ 78%] Building C object storage/myisam/CMakeFiles/myisam.dir/sort.c.o

**Comment by jkedgar** [comment]
The Pull Request (https://github.com/facebook/mysql-5.6/pull/554) solves this immediate problem.  While testing this I found other problems that I have sent fixes for internally.  I'll try to update this when they have all landed.

**Comment by jkedgar** [comment]
All the internal issues have landed.
