### ISSUE TITLE
Support index-only scans for type DOUBLE

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#36]
<a href="https://github.com/spetrunia"><img src="https://avatars.githubusercontent.com/u/2734550?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [spetrunia](https://github.com/spetrunia)**
_Friday Apr 24, 2015 at 00:50 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/56_

---

(branching this off from issue #26)

Currently, index-only scans are not supported for column type DOUBLE.  
Testcase:

```
create table t31 (pk int auto_increment primary key, key1 double, key(key1)) engine=rocksdb;
insert into t31 values (),(),(),(),(),(),(),();
explain select key1 from t31 where key1=1.234;
```

It is actually possible to restore double from its mem-comparable form and thus support index-only scans.
See filesort.cc: void change_double_for_sort(double nr,uchar *to) for the code that needs to be inverted.

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D51765
