### ISSUE TITLE
Suggest using std::unique_ptr<std::regex> m_pattern in Regex_list_handler in sql/handler.*

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#363]
`std::unique_ptr<std::regex> m_pattern;`

`bool Regex_list_handler::set_patterns(const std::string& pattern_str)
{
  ...
  m_pattern.reset(new std::regex(norm_pattern));
  ...
}
`

**Comment by jkedgar** [comment]
Great catch!

https://github.com/facebook/mysql-5.6/pull/397
