### ISSUE TITLE
Check duplicates on "Table Name => internal index id mappings" data dictionary 

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#37]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Friday Apr 24, 2015 at 22:43 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/58_

---

create table t (id int primary key ) engine=rocksdb;
insert into t values (1), (2), (3);
$ rm /data/test/t.frm
flush tables;
create table t (id int primary key, value int ) engine=rocksdb;
=> Succeeded
select \* from t;
=> Empty Set

MyRocks needs to be more robust so that second create table fails.

**Comment by yoshinorim** [comment]
InnoDB behavior:

```
mysql> create table t (id int primary key) engine=innodb;
ERROR 1813 (HY000): Tablespace for table '`test`.`t`' exists. Please DISCARD the tablespace before IMPORT.
```

**Comment by gabijs** [comment]
Fixed by https://reviews.facebook.net/D53889.
