### ISSUE TITLE
rocksdb_store_checksums & rocksdb_verify_checksums need a better name

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#374]
AFAIK, these are for debugging and when enabled we add per-row checksums in addition to the per page checksum. They are off by default because they are for debugging. But someone seeing them in "SHOW GLOBAL VARIABLES" output will be concerned because it looks like the default config means no checksums.

Better names might be rocksdb_store_row_debug_checksums, rocksdb_verify_row_debug_checksums

**Comment by yoshinorim** [comment]
We also should change default rocksdb_checksums_pct to 0. This has not been very useful to find real inconsistency.

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/942063fb6a9716414987d56c51824aadd2a3bbab
