### ISSUE TITLE
failed to compile from source code 

### ISSUE THREAD

**Issue by zhaiwx1987** [facebook/mysql-5.6#4]
Hi,
I got an error while trying to compile from source code.  And after commenting out the conflict codes,  everything goes well ...

bellow is the error message:
./libmysqld.a(zutil.c.o):(.data.rel.ro.local+0x0): multiple definition of `z_errmsg'
../libmysqld.a(zutil.c.o):(.data.rel.ro.local+0x0): first defined here
../libmysqld.a(adler32.c.o): In function`adler32_combine_':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/adler32.c:141: multiple definition of `adler32_combine'
../libmysqld.a(adler32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/adler32.c:138: first defined here
../libmysqld.a(crc32.c.o): In function`crc32_combine':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/crc32.c:432: multiple definition of `crc32_combine'
../libmysqld.a(crc32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/crc32.c:381: first defined here
collect2: error: ld returned 1 exit status
make[2]: **\* [libmysqld/examples/mysql_embedded] Error 1

**Comment by steaphan-fb-com** [comment]
I'd need a lot more detail to be able to help you.

Which branch are you building, and which revision (git hash)?

What versions of tools (cmake, gcc, etc...) are you building with?  On which platform?

Can you include the full output of the build?

**Comment by zhaiwx1987** [comment]
I downloaded the source code from 
https://github.com/facebook/mysql-5.6/archive/webscalesql-5.6.16-47.zip

$gcc --version
gcc (GCC) 4.7.2

$cmake --version
cmake version 2.8.8

$uname -a
Linux db031134.sqa.cm4 2.6.32-220.17.1.tb619.el6.x86_64 #1 SMP Fri Jun 8 13:48:13 CST 2012 x86_64 x86_64 x86_64 GNU/Linux

full error message..

../../../zlib/libzlib.a(zutil.c.o):(.data.rel.ro.local+0x0): multiple definition of `z_errmsg'
../../innobase/libinnobase.a(zutil.c.o):(.rodata+0x0): first defined here
../../../zlib/libzlib.a(adler32.c.o): In function`adler32_combine':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/adler32.c:138: multiple definition of `adler32_combine'
../../innobase/libinnobase.a(adler32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/adler32.c:141: first defined here
../../../zlib/libzlib.a(crc32.c.o): In function`crc32_combine':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/crc32.c:381: multiple definition of `crc32_combine'
../../innobase/libinnobase.a(crc32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/crc32.c:432: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [storage/perfschema/unittest/pfs_connect_attr-t] Error 1
make[1]: *** [storage/perfschema/unittest/CMakeFiles/pfs_connect_attr-t.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../zlib/libzlib.a(crc32.c.o): In function`crc32_combine':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/crc32.c:381: multiple definition of `crc32_combine'
../storage/innobase/libinnobase.a(crc32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/crc32.c:432: first defined here
../zlib/libzlib.a(zutil.c.o):(.data.rel.ro.local+0x0): multiple definition of`z_errmsg'
../storage/innobase/libinnobase.a(zutil.c.o):(.rodata+0x0): first defined here
../zlib/libzlib.a(adler32.c.o): In function `adler32_combine':
/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/zlib/adler32.c:138: multiple definition of`adler32_combine'
../storage/innobase/libinnobase.a(adler32.c.o):/u01/project/offical/mysql-5.6-webscalesql-5.6.16-47/storage/innobase/zlib_embedded/adler32.c:141: first defined here
collect2: error: ld returned 1 exit status
make[2]: **\* [sql/mysqld] Error 1
make[1]: **\* [sql/CMakeFiles/mysqld.dir/all] Error 2
make: **\* [all] Error 2

**Comment by steaphan-fb-com** [comment]
I just tested the current version here myself, and it builds fine.

What were your full "cmake" and "make" commands?  The intent is that neither should need any options.  I built with just "cmake . && make".

**Comment by eonghk** [comment]
I have the same problem if I just type cmake ./ && make in the source directory.
Anyway, I'm using gentoo and if I use the system zlib, it compiles fine.
There are three zlib in the source, any reason?

**Comment by mictadlo** [comment]
I failed to compile it on Manjaro linux:

```
$ git clone https://github.com/facebook/mysql-5.6.git
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/mictadlo/apps/ && make all install
 ...
85%] Building CXX object sql/CMakeFiles/mysqld.dir/main.cc.o
Linking CXX executable mysqld
../zlib/libzlib.a(crc32.c.o): In function `crc32_combine':
/home/mictadlo/Downloads/mysql-5.6/zlib/crc32.c:381: multiple definition of `crc32_combine'
../storage/innobase/libinnobase.a(crc32.c.o):/home/mictadlo/Downloads/mysql-5.6/storage/innobase/zlib_embedded/crc32.c:432: first defined here
../zlib/libzlib.a(zutil.c.o):(.data.rel.ro.local+0x0): multiple definition of `z_errmsg'
../storage/innobase/libinnobase.a(zutil.c.o):(.rodata+0x0): first defined here
../zlib/libzlib.a(adler32.c.o): In function `adler32_combine':
/home/mictadlo/Downloads/mysql-5.6/zlib/adler32.c:138: multiple definition of `adler32_combine'
../storage/innobase/libinnobase.a(adler32.c.o):/home/mictadlo/Downloads/mysql-5.6/storage/innobase/zlib_embedded/adler32.c:141: first defined here
collect2: error: ld returned 1 exit status
sql/CMakeFiles/mysqld.dir/build.make:114: recipe for target 'sql/mysqld' failed
make[2]: *** [sql/mysqld] Error 1
CMakeFiles/Makefile2:4521: recipe for target 'sql/CMakeFiles/mysqld.dir/all' failed
make[1]: *** [sql/CMakeFiles/mysqld.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by steaphan-fb-com** [comment]
If anyone is still having problems with the latest branch, please open a new issue with details.
