### ISSUE TITLE
Add rocksdb_rows_read|inserted|updated|deleted

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#40]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Friday May 15, 2015 at 21:49 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/65_

---

We can get these from table statistics but will still be very useful if exposing as status variables. Calculating and getting these stats need to be fast enough.

**Comment by hermanlee** [comment]
Performing the row_counters need to be efficient. Using atomic counters across multiple threads (especially rows_read) can cause too much contention. Look at innodb's srv_stats_t structure on an example of how ib_counters_t were implemented.

**Comment by santoshbanda** [comment]
https://reviews.facebook.net/D49719
