### ISSUE TITLE
Additions to the wiki regarding `make` compilation phase

### ISSUE THREAD

**Issue by 3manuek** [facebook/mysql-5.6#401]
I couldn't find the way to work around pull requests for the wiki, there are a few notes that would be nice to add.

If you want to test, I recommend to install using `-DCMAKE_INSTALL_PREFIX` (you can have several binaries with different patches), i.e:

```
cmake . \
-DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system \
-DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 \
-DENABLED_LOCAL_INFILE=1 \
-DENABLE_DTRACE=0 -DCMAKE_CXX_FLAGS="-march=native"\
-DCMAKE_INSTALL_PREFIX:PATH=/home/emanuel.calvo/myrocks
```

Also, if running on limited resources machines (like 1 core VMs), you need to decrease the number of jobs for the `make` phase to =< 2. In the wiki assumes you have enough for 8  concurrent jobs.

Also, there are a couple of missing libraries when installing on a fresh EC2 Ubuntu based image at AWS:

```
apt-get install build-essential python python-mysqldb libssl-dev libncurses5-dev libreadline-dev
```

**Comment by 3manuek** [comment]
Missing libraries from the doc if installing in scratch EC2:

```
apt-get install build-essential python python-mysqldb libssl-dev libncurses5-dev libreadline-dev
```

**Comment by 3manuek** [comment]
I'm going to send this changes for posterior review to the wiki. Closing.

**Comment by vasilep** [comment]
We've just turned on external contributors' write access for the wiki.
