### ISSUE TITLE
How to solve the error when compiling

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#42]
<a href="https://github.com/MrDimension"><img src="https://avatars.githubusercontent.com/u/8252310?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MrDimension](https://github.com/MrDimension)**
_Thursday May 28, 2015 at 03:00 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/73_

---

The error occurred during "make" process. And I got the error message below:
// ==========================================================
/u01/weidu.lww/myrocks/vio/viosslfactories.c: In function ‘new_VioSSLFd’:
/u01/weidu.lww/myrocks/vio/viosslfactories.c:266:3: warning: implicit declaration of function ‘ERR_clear_error’ [-Wimplicit-function-declaration]
   ERR_clear_error();
   ^
/u01/weidu.lww/myrocks/vio/viosslfactories.c:307:5: error: unknown type name ‘EC_KEY’
     EC_KEY _ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
     ^
/u01/weidu.lww/myrocks/vio/viosslfactories.c:307:5: warning: implicit declaration of function ‘EC_KEY_new_by_curve_name’ [-Wimplicit-function-declaration]
/u01/weidu.lww/myrocks/vio/viosslfactories.c:307:45: error: ‘NID_X9_62_prime256v1’ undeclared (first use in this function)
     EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
                                             ^
/u01/weidu.lww/myrocks/vio/viosslfactories.c:307:45: note: each undeclared identifier is reported only once for each function it appears in
/u01/weidu.lww/myrocks/vio/viosslfactories.c:309:7: warning: implicit declaration of function ‘SSL_CTX_set_tmp_ecdh’ [-Wimplicit-function-declaration]
       SSL_CTX_set_tmp_ecdh(ssl_fd->ssl_context, ecdh);
       ^
/u01/weidu.lww/myrocks/vio/viosslfactories.c:310:7: warning: implicit declaration of function ‘EC_KEY_free’ [-Wimplicit-function-declaration]
       EC_KEY_free(ecdh);
       ^
make[2]: *_\* [vio/CMakeFiles/vio.dir/viosslfactories.c.o] Error 1
make[1]: **\* [vio/CMakeFiles/vio.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make: **\* [all] Error 2
// ==========================================================
I found the code in vio directory is a little different from the official version of mysql 5.6. When I compile the official version of mysql 5.6, there is no error about this.  After a lot of trying, I guess the reason may be about openssl. Did someone meet the same problem? What can I do to solve the problem? 
(ps: my gcc version is gcc-4.9.2)

**Comment by gunnarku** [comment]
Determine if this is still an issue and if something needs to be done about it.

**Comment by jtolmer** [comment]
This _may_ have been the same issue I fixed with https://github.com/facebook/mysql-5.6/commit/95257cb5d5e7fcbd8fd3ad23d0d9d4e1c8afb91d.

**Comment by jtolmer** [comment]
Yep. See https://github.com/facebook/mysql-5.6/issues/6#issuecomment-118214648 that complains of the same compilation errors.

**Comment by gunnarku** [comment]
Thanks, you saved me some time :-)
