### ISSUE TITLE
Improvement on Wiki; Update my.cnf for "Getting Started with MyRocks"

### ISSUE THREAD

**Issue by ShahriyarR** [facebook/mysql-5.6#436]
Hi dear all,
Based on -> https://github.com/facebook/mysql-5.6/wiki/Getting-Started-with-MyRocks
# Set up my.cnf
As general user, I just copied and pasted my.cnf and failed to start because of,
`collation-server=latin1_bin (or utf8_bin, binary)` 
So it can be changed in a way:
```
collation-server=latin1_bin 
#(or utf8_bin, binary) 
```
Again full my.cnf is based on default settings:

```
[mysqld]
rocksdb
default-storage-engine=rocksdb
skip-innodb
default-tmp-storage-engine=MyISAM
collation-server=latin1_bin (or utf8_bin, binary)

log-bin
binlog-format=ROW
```
So for usability and to be more informative, datadir= option should be there to show where it is going to be initialized , port= and socket= info must be there too. Also I can't see sql_mode= option which is there in support-files/my-default.cnf

**Comment by jkedgar** [comment]
Done.
