### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by dohungthuan** [facebook/mysql-5.6#439]
I install mysql 5.7 and mysql-5.6 with myrockdb same desktop with ubuntu server 14.04(core i3, ram 8gb, HDD not SSD), i use fb_linkbench run test same time into 2 mysql server. when test, i command "top" and show mysql 5.7 get about 100% cpu but mysql5.6 with myrockdb about 200-300% cpu(avg: 1:3). 2 mysql setting is default and set max_connection = 3000. Do have special settings for mysql with myrockdb for use cpu?

**Comment by mdcallag** [comment]
I prefer to answer questions on the email list and leave github issues for bugs & feature requests.
See https://groups.google.com/forum/#!forum/myrocks-dev

**Comment by jkedgar** [comment]
I'm going to close this issue.  Feel free to ask your question on the email list if you haven't already.
