### ISSUE TITLE
increase default size of RocksDB block cache

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#441]
Defaults for RocksDB in MyRocks include:
* 8M block cache
* 64 shards for block cache -> 128kb / shard
* 128M write buffer

If the default is setup for "low memory" servers, then the ratio of memory between the block cache and write buffer is wrong (8M to block cache, 128M to write buffer).

128kb/shard  for the block cache leads to lousy performance, possibly because index & filter blocks are large and displace data blocks or even wipe the shard when loaded, then loading the next data block wipes the index/filter  blocks.

I will have more perf results over the next week but this is a lousy experience today for a user who doesn't set the block cache size. If the default is done with low memory servers in mind then lets use 32M for the write buffer and 128M or even 256M for the block cache.

**Comment by mdcallag** [comment]
A few examples.

1) I started linkbench on servers with TLC SSD (10k IOPs/server). After ~12 hours server with default my.cnf is 2.8% done with the load. Another server that started at the same time is ~70% done with the load. The only difference is rocksdb_block_cache_size=10G

2) I ran the insert benchmark on servers with fast SSD and inserted 250M documents. The database is cached in RAM. The server with a default my.cnf has been running for almost 24 hours and is now doing ~800 inserts/second and is only 20% done. Another server averaged 20,000 inserts/second by test end. The only difference, rocksdb_block_cache_size=128M

**Comment by spetrunia** [comment]
In current server I see @@rocksdb_block_cache_size=536870912, 512M


The change was made by this commit:

```
commit b573e1407052568d33023bbeb2f50901e84de70c
Author: Yoshinori Matsunobu <yoshinori@fb.com>
Date:   Mon Nov 28 16:11:14 2016 -0800

    Increasing default RocksDB write buffer and block cache size
    
    Summary:
    This diff increases RocksDB default write buffer size
    from 4MB to 64MB, and block cache size from 8MB to 512MB.
    Closes https://github.com/facebook/mysql-5.6/pull/442
```

Should this task be closed?
