### ISSUE TITLE
warning: variable length array is used [-Wvla]

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#457]
MyRocks uses deprecated vla in function format_string at https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/ha_rocksdb.cc#L2864

Suggest recoding to:
  else {
    std::unique_ptr<char[], decltype(&my_free)> buff(nullptr, &my_free);
    buff.reset(static_cast<char*>(my_malloc(len, MYF(0))));
    (void) vsnprintf(buff.get(), len, format, args_copy);
    res = buff.get();
  }

**Comment by jkedgar** [comment]
https://github.com/facebook/mysql-5.6/pull/458

Note: There appear to be other variable length arrays in MySQL outside of our managed code.  These should be addressed upstream by Oracle.
