### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by edo888** [facebook/mysql-5.6#459]
Hi,

Is it possible to build myrocks on FreeBSD 11?

Thanks!

**Comment by gunnarku** [comment]
We haven't tried building MyRocks on FreeBSD. Officially supported systems are listed at https://github.com/facebook/mysql-5.6/wiki/Build-Steps.

However, if you're willing to give it a try and see what happens then sharing the outcome will be highly appreciated by our team!

**Comment by gunnarku** [comment]
After a quick test I can confirm that building MyRocks on FreeBSD 11 does **not** work. At this point we're relying on community to help with various patches needed to support this particular OS.
