### ISSUE TITLE
 ha_rocksdb::records_in_range statistic method is not accurate.

### ISSUE THREAD

**Issue by justfortaste** [facebook/mysql-5.6#461]
```
ha_rocksdb::records_in_range:
 
 uint64_t sz=0;
 auto disk_size = kd.m_stats.m_actual_disk_size;
 if (disk_size == 0)
   disk_size = kd.m_stats.m_data_size;
 auto rows = kd.m_stats.m_rows;
 if (rows == 0 || disk_size == 0)
 {
   rows= 1;
   disk_size= ROCKSDB_ASSUMED_KEY_VALUE_DISK_SIZE;
 }
 // Getting statistics, including from Memtables
 rdb->GetApproximateSizes(
   kd.get_cf(),
   &r, 1,
   &sz, true);
 ret = rows*sz/disk_size;

```
"m_actual_disk_size" only include all sstable file size, not include memtable or imm size.
but "sz" include ssttable, memtable and imm size

So, ret = rows*sz/disk_size is not accurate.

Actually, we can get number of records in range from memtable and imm with "ApproximateNumEntries"  directly!

sstable records in range still use the old method.
```
 rdb->GetApproximateSizes(
   kd.get_cf(),
   &r, 1,
   &sz, false); // false menas not  include memtable
 ret = rows*sz/disk_size;
```

**Comment by hermanlee** [comment]
Thanks for filing the issue. Yes, we should be able to improve records_in_range by using the old method for sstable record numbers to generate the count and adding the return count from ApproximateNumEntries().

**Comment by alxyang** [comment]
this task is already completed via D4448878
