### ISSUE TITLE
myrocks uses 1/4 to 1/2 of a CPU core doing nothing

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#465]
server uses 4.0.9 kernel and MyRocks build is from Nov21:
git_date        2016-11-23T09:56:32-08:00
git_hash        e3d26b4d9e0317026d15f98695f4713a176d8c40
rocksdb_git_date        2016-11-21T21:24:11-08:00
rocksdb_git_hash        734e4acafbcea77934d5164c424b5084f0422c82

top shows mysqld CPU between 25% and 50%

Results from perf shows this is from the use of pthread_cond_timedwait. Not sure if it is from both uses or one as the one from void Rdb_drop_index_thread::run() has at least a 60 second timeout and the one from Rdb_background_thread::run() has a one second timeout

https://gist.github.com/mdcallag/05a020211058518530df20a4b3df1820

**Comment by mdcallag** [comment]
This has a bug..>
https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/ha_rocksdb.cc#L10624

The bug occurs when this is false -> "if (ts.tv_sec - ts_next_sync.tv_sec >= 1)"
In which case, ts_next_sync.tv_sec is not incremented
On the next loop that value is used as the next timeout, but it is likely that ts_next_sync current is equal to now() given it was used as the last value to the timed wait. So the next call to the timed wait returns immediately, and that repeats until 1 second has passed.

I added an fprint to dump the value of ts.tv_sec and ts.tv_nsec for each iteration of the loop and you can see how frequently this is called

```
ran at 1481056145 : 692638269
ran at 1481056145 : 692645459
ran at 1481056145 : 692652678
ran at 1481056145 : 692660250
ran at 1481056145 : 692667517
ran at 1481056145 : 692674978
ran at 1481056145 : 692682207
ran at 1481056145 : 692689620
ran at 1481056145 : 692696769
ran at 1481056145 : 692703698
ran at 1481056145 : 692710600
ran at 1481056145 : 692717602
ran at 1481056145 : 692724760
ran at 1481056145 : 692731881
ran at 1481056145 : 692741706
ran at 1481056145 : 692749132
ran at 1481056145 : 692756952
ran at 1481056145 : 692764361
ran at 1481056145 : 692771692
ran at 1481056145 : 692779052
ran at 1481056145 : 692786195
ran at 1481056145 : 692793363
ran at 1481056145 : 692800609
ran at 1481056145 : 692807780
ran at 1481056145 : 692815111
ran at 1481056145 : 692826838
ran at 1481056145 : 692835814
ran at 1481056145 : 692843367
ran at 1481056145 : 692851068
ran at 1481056145 : 692858396
```

**Comment by hermanlee** [comment]
Looking through the code, I think a fix for this would be to set tv_sync_next.tv_sec = ts.tv_sec + 1 whenever the loop wakes up and record the last time a syncWAL() was issued. If the time difference is greater than 1 second, then issue another syncWAL().

Gunnar mentioned looking at better mechanisms to support this type of event scheduling without resorting to polling though and that's definitely worth investigating.

**Comment by gunnarku** [comment]
After thinking about this a bit, I think that I understand what's currently happening and IMO the entire `if (ts.tv_sec - ts_next_sync.tv_sec >= 1)` part is unnecessary. Will describe the reasoning tomorrow.

**Comment by gunnarku** [comment]
Will send out an initial fix today afternoon.
