### ISSUE TITLE
Check consistency between frm and MyRocks data dictionary at startup

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#48]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Thursday Jul 16, 2015 at 01:00 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/91_

---

Optionally, check consistency between all frm files and all MyRocks data dictionary entries, and aborting if there is any mismatch.

**Comment by hermanlee** [comment]
<a href="https://github.com/jkedgar"><img src="https://avatars.githubusercontent.com/u/8951526?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jkedgar](https://github.com/jkedgar)**
_Thursday Sep 10, 2015 at 18:55 GMT_

---

I have this working to check the number of keys in the table.  I thought about attempting to compare the table names, but wondered if that would run into problems when aliases were used.  What other information do we store in the MyRocks data dictionary that you would like to see compared?

**Comment by hermanlee** [comment]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoshinorim](https://github.com/yoshinorim)**
_Thursday Sep 10, 2015 at 22:21 GMT_

---

We store database_name.table_name in MyRocks data dictionary idx_id=0x1 (https://github.com/MySQLOnRocksDB/mysql-5.6/wiki/MyRocks-data-dictionary-format). We don't store aliases in MyRocks data dictionary.

**Comment by hermanlee** [comment]
<a href="https://github.com/jkedgar"><img src="https://avatars.githubusercontent.com/u/8951526?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jkedgar](https://github.com/jkedgar)**
_Thursday Sep 10, 2015 at 22:23 GMT_

---

Okay.  I'll look into the table name further.  Besides these two things, what should we check the consistency of?

**Comment by hermanlee** [comment]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoshinorim](https://github.com/yoshinorim)**
_Thursday Sep 17, 2015 at 00:52 GMT_

---

Sorry I missed the last comment. I think checking database_name.table_name for all tables is fine. Checking indexes will need to parse frm file itself, which will make things more complex.

**Comment by hermanlee** [comment]
Is failing the system when there are tables with .frm files but not using the rocksdb storage engine too restrictive? It seems like there could be generic uses cases for creating tables with other storage engines.

**Comment by yoshinorim** [comment]
As far as it's configurable, I think failing the system at startup is ok. Creating tables with other storage engines may happen on temporary tables, but tmp tables can easily be filtered out.

**Comment by hermanlee** [comment]
There are also tables created using the blackhole engine though that persist across restarts. The current checks would always fail for them.

**Comment by jkedgar** [comment]
Fixed: https://reviews.facebook.net/D47619
