### ISSUE TITLE
slowdown when using rtti switch

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#51]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maykov](https://github.com/maykov)**
_Tuesday Jul 28, 2015 at 22:03 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/94_

---

We experienced 5% slowdown when started compiling withou -fno-rtti switch.

Oracle enabled rtti in 5.6.4: http://dev.mysql.com/worklog/task/?id=5825
commit: https://github.com/mysql/mysql-server/commit/a5ee7278a16a6a5e6e90c56c13fdda7f6f30ebad

They haven't started _using_ rtti until 5.7 though. 
Excerpt:
<<<A separate test of removing the -fno-exceptions and the -fno-rtti flags
shows that there is no significant difference in execution time between
having and not having these flags.>>>

**Comment by hermanlee** [comment]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maykov](https://github.com/maykov)**
_Tuesday Aug 04, 2015 at 01:14 GMT_

---

I ran linkbench tests with a 15m dataset provided by Yoshinori.
QPS for RTTI binary
![image](https://cloud.githubusercontent.com/assets/8107629/9051133/50438c36-3a0b-11e5-8b75-de1bd9bd5853.png)

QPS for the binary without RTTI:
![image](https://cloud.githubusercontent.com/assets/8107629/9051135/6b8c1c92-3a0b-11e5-964c-6b068f94a428.png)

Since the QPS was so spiky I cut all datapoints with < 30000 QPS:
RTTI:
![image](https://cloud.githubusercontent.com/assets/8107629/9051163/b277488e-3a0b-11e5-9e1a-6b80a4c81f1a.png)

no RTTI:
![image](https://cloud.githubusercontent.com/assets/8107629/9051167/b91be41a-3a0b-11e5-9af6-5324c07e1ed1.png)

The AVG QPS for RTTI was 36245 (stdev was 2044) with 37052 (stdev 2233) for no RTTI

This repesents 2% degradation, but it is within stddev. 

Another observation is that QPS dropped by about 10% during the run.

**Comment by hermanlee** [comment]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maykov](https://github.com/maykov)**
_Saturday Aug 22, 2015 at 06:39 GMT_

---

I found an easy way of enabling the RTTI just for RocksDB and disabling for everything else.
See:
https://reviews.facebook.net/differential/diff/220563/
and https://phabricator.fb.com/differential/diff/8899117/

The performance is not affected by disabling RTTI in this manner.

The reason, why we saw perf improvements above is that rocksdb code does quite a bit of string manipulations for logging. Disabling that improved QPS. See the internal t8101744 for details.

**Comment by gunnarku** [comment]
Determine if this is still an issue and if something needs to be done about it.

**Comment by gunnarku** [comment]
Obsolete.
