### ISSUE TITLE
How do I set delayed_write_rate?

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#517]
How do I set delayed_write_rate? 
https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L1273

I wasn't able to set it at the top level in my.cnf via rocksdb_delayed_write_rate.
I wasn't able to set it in rocksdb_default_cf_options.

**Comment by mdcallag** [comment]
Can you find an owner? Siying suggested the default for this was too small but that might be a RocksDB issue. I can't set this in my.cnf today.

**Comment by alxyang** [comment]
this is closed by #526.  closing for @xiaofeidu008
