### ISSUE TITLE
support universal compaction options in my.cnf

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#524]
The options parser in RocksDB doesn't parse universal compaction options.

For the options see https://github.com/facebook/rocksdb/blob/master/include/rocksdb/universal_compaction.h

**Comment by AustEcon** [comment]
Has anyone discovered a way to set MyRocks to universal compaction now in 2021? Any help much appreciated.

**Comment by yoshinorim** [comment]
You can enable Universal Compaction by adding "compaction_style=kCompactionStyleUniversal;" in rocksdb_default_cf_options my.cnf parameter.

**Comment by AustEcon** [comment]
Brilliant. Thanks.
