### ISSUE TITLE
make stat computations sane

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#53]
<a href="https://github.com/maykov"><img src="https://avatars.githubusercontent.com/u/8107629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maykov](https://github.com/maykov)**
_Wednesday Aug 19, 2015 at 17:01 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/97_

---

Right now, there is a delay of 1 hour between stat computes when using default options. This makes MyRocks fail (run slow) on standard tests such as Wisconsin. We need to fix this.

E.g.:  i.e. updating stats on table X (including Memstore) if all of the indexes of the table are less than Y bytes, whenever the table was accessed.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D48495 resolved this issue.
