### ISSUE TITLE
change default for rocksdb_write_sync to ON

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#530]
The default is off today. I prefer that MyRocks be crash-safe by default and the default for rocksdb_write_sync to be changed to ON. The default for innodb_flush_log_at_trx_commit=1 which is crash safe.

**Comment by yoshinorim** [comment]
The latest commit (https://github.com/facebook/mysql-5.6/commit/4e13a63be98ba78c369253d99d226ddf78ea37c6) already made MyRocks crash safe by default. It renamed rocksdb_write_sync to rocksdb_flush_log_at_trx_commit, and default is now 1. The diff also changed rocksdb_wal_recovery_mode from 2 to 1, which does not accept corrupted wal anymore.
