### ISSUE TITLE
MyRocks create table silently ignores DATA DIRECTORY option

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#532]
This directory does not exist ->  /var/storage/test
 
mysql> Create table test_table (
    -> id int primary key auto_increment,
    -> Message varchar(200)
    -> ) Engine = rocksdb DATA DIRECTORY = '/var/storage/test';
Query OK, 0 rows affected (0.00 sec)

MyISAM does raises an error when the dir doesn't exist:

mysql> create table t3 ( id int primary key ) engine=myisam DATA DIRECTORY = '/foo/var';
ERROR 1 (HY000): Can't create/write to file '/foo/var/t3.MYD' (Errcode: 2 - No such file or directory)

**Comment by gunnarku** [comment]
The fix will be to return an error if either `DATA DIRECTORY` or `INDEX DIRECTORY` are specified for `CREATE TABLE` in MyRocks because we ignore those parameters and should notify the user that this functionality isn't supported.

**Comment by ghost** [comment]
Is there a work around for this issue ? Like can I have different database directories ? Or tables in different directories ?

**Comment by alxyang** [comment]
I believe can still set the datadir via a system variable https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/storage/rocksdb/ha_rocksdb.cc#L1143.

**Comment by gunnarku** [comment]
For MyRocks you can use both`datadir` and `rocksdb_datadir` variables to configure the path to data directory, but you won't be able to do this for individual tables or partitions associated with a table.

**Comment by ghost** [comment]
both are not dynamic variables so they both are set before the system starts. So how does this substitute for seperate data directory for different databases ?

**Comment by mdcallag** [comment]
Separate data directory for different databases, tables, indexes isn't supported.
