### ISSUE TITLE
Default branch fb-mysql-5.6.35 initialize failed in Ubuntu 16.04

### ISSUE THREAD

**Issue by vrofze** [facebook/mysql-5.6#534]
I run `sudo scripts/mysql_install_db --basedir=/usr/local/mysql --datadir=/usr/local/mysql/data --user=mysql --defaults-file=/etc/mysql/my.cnf --log-bin=/usr/local/mysql/data/terark-1-bin` to initialize MyRocks after compiled and installed, but it fails and the output is

> Installing MySQL system tables...[Note] Global variable initial value (from config file) @@default-storage-engine = 'rocksdb'
>[Note] Global variable initial value (from config file) @@default-tmp-storage-engine = 'MyISAM'
>[Note] Global variable initial value (from config file) @@collation-server = 'latin1_bin'
>[Note] Global variable initial value (from config file) @@binlog_format = 'ROW'
>[Note] Global variable initial value (from cmd line) @@datadir = '/usr/local/mysql/data'
>[Note] Global variable initial value (from cmd line) @@log_warnings = 0
>[Note] Global variable initial value (from cmd line) @@max_allowed_packet = 8388608
>[Note] Global variable initial value (from cmd line) @@log-bin = '/usr/local/mysql/data/terark-1-bin'
>2017-02-20 18:44:21 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
>2017-02-20 18:44:21 0 [Note] Setting num_sharded_locks=1 as sharding is OFF
>2017-02-20 18:44:21 0 [Note] /usr/local/mysql/bin/mysqld (mysqld 5.6.27-log) starting as process 22280 ...
>2017-02-20 18:44:21 22280 [Note] Flashcache bypass: disabled
>2017-02-20 18:44:21 22280 [Note] Flashcache setup error is : ioctl failed
>
>2017-02-20 18:44:21 22280 [Warning] The option innodb (skip-innodb) is deprecated and will be removed in a future release
>2017-02-20 18:44:21 22280 [Note] RocksDB: 2 column families found
>2017-02-20 18:44:21 22280 [Note] RocksDB: Column Families at start:
>2017-02-20 18:44:21 22280 [Note]   cf=default
>2017-02-20 18:44:21 22280 [Note]     write_buffer_size=67108864
>2017-02-20 18:44:21 22280 [Note]     target_file_size_base=67108864
>2017-02-20 18:44:21 22280 [Note]   cf=__system__
>2017-02-20 18:44:21 22280 [Note]     write_buffer_size=67108864
>2017-02-20 18:44:21 22280 [Note]     target_file_size_base=67108864
>2017-02-20 18:44:21 22280 [Note] RocksDB: Table_store: loaded DDL data for 0 tables
>2017-02-20 18:44:21 22280 [ERROR] RocksDB: Couldn't start the background thread: (errno=13)
>2017-02-20 18:44:21 22280 [ERROR] Plugin 'ROCKSDB' init function returned error.
>2017-02-20 18:44:21 22280 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
>2017-02-20 18:44:21 22280 [ERROR] Unknown/unsupported storage engine: rocksdb
>2017-02-20 18:44:21 22280 [ERROR] Aborting

>2017-02-20 18:44:21 22280 [Note] Binlog end
>2017-02-20 18:44:21 22280 [Note] unregister_replicator OK
>2017-02-20 18:44:21 22280 [Note] /usr/local/mysql/bin/mysqld: Shutdown complete

While i switch to tag [5.6.27-20160411.prod](https://github.com/facebook/mysql-5.6/tree/5.6.27-20160411.prod) it works well. My os is Ubuntu 16.04 LTS, and this is my my.cnf:

> [mysqld]
>rocksdb
>default-storage-engine=rocksdb
>skip-innodb
>default-tmp-storage-engine=MyISAM
>collation-server=latin1_bin
>
>log-bin
>binlog-format=ROW

**Comment by jkedgar** [comment]
@vrofze, I don't have Ubuntu 16.04 LTS handy to try this on right now.  Are you willing to do bit of debugging with me?

I looked into that code and there are two internal functions that could be returning the error.  Would you be willing to add this code for debugging purposes to see which is at fault?

```
diff --git a/storage/rocksdb/rdb_threads.cc b/storage/rocksdb/rdb_threads.cc
index abae41b..b4d4233 100644
--- a/storage/rocksdb/rdb_threads.cc
+++ b/storage/rocksdb/rdb_threads.cc
@@ -70,6 +70,12 @@ int Rdb_thread::create_thread(const std::string &thread_name
       the name if thread was successfully created.
     */
     err = pthread_setname_np(m_handle, thread_name.c_str());
+    if (err) {
+      sql_print_error("DEBUGGING: pthread_setname_np failed: errno=%d", errno);
+    }
+  }
+  else {
+    sql_print_error("DEBUGGING: mysql_thread_create failed: errno=%d", errno);
   }

   return err;
```

Also, as I was looking around, I noticed that we are not supplying an attribute (parameter 3 of `mysql_thread_create()` - which is passed into `pthread_create()`).  I was theorizing that CentOS might allow a null attribute and just assume the defaults whereas Ubuntu might require that it be a valid attribute.  Try this change and see if it resolves the problem.

```
diff --git a/storage/rocksdb/rdb_threads.cc b/storage/rocksdb/rdb_threads.cc
index abae41b..0bac9df 100644
--- a/storage/rocksdb/rdb_threads.cc
+++ b/storage/rocksdb/rdb_threads.cc
@@ -58,9 +58,14 @@ int Rdb_thread::create_thread(const std::string &thread_name
                               ) {
   DBUG_ASSERT(!thread_name.empty());

-  int err = mysql_thread_create(background_psi_thread_key, &m_handle, nullptr,
+  pthread_attr_t attr;
+  pthread_attr_init(&attr);
+
+  int err = mysql_thread_create(background_psi_thread_key, &m_handle, &attr,
                                 thread_func, this);

+  pthread_attr_destroy(&attr);
+
   if (!err) {
     /*
       mysql_thread_create() ends up doing some work underneath and setting the
```

**Comment by vrofze** [comment]
@jkedgar , Of course.
I had attemped to make the two changes, but it fails again, and the outputs are the same:

```Installing MySQL system tables...[Note] Global variable initial value (from config file) @@default-storage-engine = 'rocksdb'
[Note] Global variable initial value (from config file) @@default-tmp-storage-engine = 'MyISAM'
[Note] Global variable initial value (from config file) @@binlog_format = 'ROW'
[Note] Global variable initial value (from config file) @@collation-server = 'latin1_bin'
[Note] Global variable initial value (from config file) @@transaction-isolation = 'READ-COMMITTED'
[Note] Global variable initial value (from cmd line) @@datadir = '/usr/local/mysql/data'
[Note] Global variable initial value (from cmd line) @@log_warnings = 0
[Note] Global variable initial value (from cmd line) @@max_allowed_packet = 8388608
[Note] Global variable initial value (from cmd line) @@log-bin = '/usr/local/mysql/data/terark-1-bin'
2017-02-21 17:22:27 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-02-21 17:22:27 0 [Note] Ignoring --secure-file-priv value as server is running with --bootstrap.
2017-02-21 17:22:27 0 [Note] Setting num_sharded_locks=1 as sharding is OFF
2017-02-21 17:22:27 0 [Note] /usr/local/mysql/bin/mysqld (mysqld 5.6.35-log) starting as process 16275 ...
2017-02-21 17:22:27 16275 [Note] Flashcache bypass: disabled
2017-02-21 17:22:27 16275 [Note] Flashcache setup error is : ioctl failed

2017-02-21 17:22:27 16275 [Warning] The option innodb (skip-innodb) is deprecated and will be removed in a future release
2017-02-21 17:22:27 16275 [Note] RocksDB: Got ENOENT when listing column families
2017-02-21 17:22:27 16275 [Note] RocksDB:   assuming that we're creating a new database
2017-02-21 17:22:27 16275 [Note] RocksDB: Column Families at start:
2017-02-21 17:22:27 16275 [Note]   cf=default
2017-02-21 17:22:27 16275 [Note]     write_buffer_size=134217728
2017-02-21 17:22:27 16275 [Note]     target_file_size_base=33554432
2017-02-21 17:22:27 16275 [ERROR] RocksDB: Error opening instance: Invalid argument: Compression type LZ4 is not linked with the binary.
2017-02-21 17:22:27 16275 [ERROR] Plugin 'ROCKSDB' init function returned error.
2017-02-21 17:22:27 16275 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
2017-02-21 17:22:27 16275 [ERROR] /usr/local/mysql/bin/mysqld: unknown variable 'rocksdb_rpl_lookup_rows=0'
2017-02-21 17:22:27 16275 [ERROR] Aborting

2017-02-21 17:22:27 16275 [Note] Binlog end
2017-02-21 17:22:27 16275 [Note] unregister_replicator OK
2017-02-21 17:22:27 16275 [Note] /usr/local/mysql/bin/mysqld: Shutdown complete
```
I run `export WITH_LZ4=/usr/lib/x86_64-linux-gnu` to config liblz4-dev and recompile it.  Um...it still initialize failed. the second change does no use, while the first change's output becomes:
```
Installing MySQL system tables...[Note] Global variable initial value (from config file) @@default-storage-engine = 'rocksdb'
[Note] Global variable initial value (from config file) @@default-tmp-storage-engine = 'MyISAM'
[Note] Global variable initial value (from config file) @@binlog_format = 'ROW'
[Note] Global variable initial value (from config file) @@collation-server = 'latin1_bin'
[Note] Global variable initial value (from config file) @@transaction-isolation = 'READ-COMMITTED'
[Note] Global variable initial value (from cmd line) @@datadir = '/usr/local/mysql/data'
[Note] Global variable initial value (from cmd line) @@log_warnings = 0
[Note] Global variable initial value (from cmd line) @@max_allowed_packet = 8388608
[Note] Global variable initial value (from cmd line) @@log-bin = '/usr/local/mysql/data/terark-1-bin'
2017-02-21 20:38:43 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-02-21 20:38:43 0 [Note] Ignoring --secure-file-priv value as server is running with --bootstrap.
2017-02-21 20:38:43 0 [Note] Setting num_sharded_locks=1 as sharding is OFF
2017-02-21 20:38:43 0 [Note] /usr/local/mysql/bin/mysqld (mysqld 5.6.35-log) starting as process 2027 ...
2017-02-21 20:38:43 2027 [Note] Flashcache bypass: disabled
2017-02-21 20:38:43 2027 [Note] Flashcache setup error is : ioctl failed

2017-02-21 20:38:43 2027 [Warning] The option innodb (skip-innodb) is deprecated and will be removed in a future release
2017-02-21 20:38:43 2027 [Note] RocksDB: 2 column families found
2017-02-21 20:38:43 2027 [Note] RocksDB: Column Families at start:
2017-02-21 20:38:43 2027 [Note]   cf=default
2017-02-21 20:38:43 2027 [Note]     write_buffer_size=134217728
2017-02-21 20:38:43 2027 [Note]     target_file_size_base=33554432
2017-02-21 20:38:43 2027 [Note]   cf=__system__
2017-02-21 20:38:43 2027 [Note]     write_buffer_size=134217728
2017-02-21 20:38:43 2027 [Note]     target_file_size_base=33554432
2017-02-21 20:38:43 2027 [Note] RocksDB: Table_store: loaded DDL data for 0 tables
2017-02-21 20:38:43 2027 [ERROR] DEBUGGING: pthread_setname_np failed: errno=13
2017-02-21 20:38:43 2027 [ERROR] RocksDB: Couldn't start the background thread: (errno=13)
2017-02-21 20:38:43 2027 [ERROR] Plugin 'ROCKSDB' init function returned error.
2017-02-21 20:38:43 2027 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
2017-02-21 20:38:43 2027 [ERROR] /usr/local/mysql/bin/mysqld: unknown variable 'rocksdb_rpl_lookup_rows=0'
2017-02-21 20:38:43 2027 [ERROR] Aborting

2017-02-21 20:38:43 2027 [Note] Binlog end
2017-02-21 20:38:43 2027 [Note] unregister_replicator OK
2017-02-21 20:38:43 2027 [Note] /usr/local/mysql/bin/mysqld: Shutdown complete
```

**Comment by jkedgar** [comment]
This is good.  This tells me that it was not the null attribute to the `mysql_thread_create()` call that caused the problem.  It isn't the `mysql_thread_create()` call at all.  It is the `pthread_setname_np()` that is causing the problem.

Technically, we could simply not check the return code from `pthread_setname_np()` since we don't really need to fail as the thread was created successfully.  Setting the name just helps us during debugging.  A simple fix would be to just ignore any failure here.  However, I'd like to understand why it failed.  I've been looking at the documentation and it seems that it is safer to have the newly created thread set its own name.  Try making these changes and see what happens.

```
diff --git a/storage/rocksdb/rdb_threads.cc b/storage/rocksdb/rdb_threads.cc
index abae41b..de38075 100644
--- a/storage/rocksdb/rdb_threads.cc
+++ b/storage/rocksdb/rdb_threads.cc
@@ -28,6 +28,7 @@ void *Rdb_thread::thread_func(void *const thread_ptr) {
   DBUG_ASSERT(thread_ptr != nullptr);
   Rdb_thread *const thread = static_cast<Rdb_thread *const>(thread_ptr);
   if (!thread->m_run_once.exchange(true)) {
+    thread->setname();
     thread->run();
     thread->uninit();
   }
@@ -58,6 +59,9 @@ int Rdb_thread::create_thread(const std::string &thread_name
                               ) {
   DBUG_ASSERT(!thread_name.empty());

+  m_name = thread_name.c_str();
+  m_name_set = false;
+
   int err = mysql_thread_create(background_psi_thread_key, &m_handle, nullptr,
                                 thread_func, this);

@@ -69,7 +73,12 @@ int Rdb_thread::create_thread(const std::string &thread_name
       debugger then they'll be more easily identifiable. Therefore we'll reset
       the name if thread was successfully created.
     */
-    err = pthread_setname_np(m_handle, thread_name.c_str());
+    while (!m_name_set) {
+      my_sleep(10000); // 10 milliseconds
+    }
+
+    err = m_name_set_err;
+    errno = m_name_set_errno;
   }
+
+  m_name = nullptr;

   return err;
diff --git a/storage/rocksdb/rdb_threads.h b/storage/rocksdb/rdb_threads.h
index 48cd8c9..adce957 100644
--- a/storage/rocksdb/rdb_threads.h
+++ b/storage/rocksdb/rdb_threads.h
@@ -39,6 +39,10 @@ private:
   std::atomic_bool m_run_once;

   pthread_t m_handle;
+  const char* m_name;
+  bool m_name_set;
+  int m_name_set_err;
+  int m_name_set_errno;

 protected:
   mysql_mutex_t m_signal_mutex;
@@ -64,6 +68,12 @@ public:

   int join() { return pthread_join(m_handle, nullptr); }

+  void setname() {
+    m_name_set_err = pthread_setname_np(m_handle, m_name);
+    m_name_set_errno = errno;
+    m_name_set = true;
+  }
+
   void uninit();

   virtual ~Rdb_thread() {}
```

Note that I might do this a bit differently in a real fix (i.e. use a condition instead of a loop with a sleep in it or simply not have the creating thread wait at all but have the created thread generate a warning in the log if it failed to set the name), but this will be sufficient to see if having the thread set its own name solves the problem.

**Comment by vrofze** [comment]
@jkedgar Great, these changes take affect, it initialize and start successfully. And it seems there no exception infomation in the output info.

**Comment by jkedgar** [comment]
Great!  I'll make a Pull Request with a version of this so we can get it officially resolved.  It may take a few days to get approved.

**Comment by jkedgar** [comment]
Pull Request: https://github.com/facebook/mysql-5.6/pull/541

**Comment by jkedgar** [comment]
The PR request has been committed.

**Comment by vrofze** [comment]
Thanks for your work :)

**Comment by hotjump** [comment]
@jkedgar 

+ If a thread is setting its own name, pthread_setname_np() uses ThreadCtl().
+ If a thread is setting another thread's name, pthread_setname_np() needs read/write access to the /proc/ pid /as entry for the process.

source code：
```
  // Changing our own name is an easy special case.
  if (thread == pthread_self()) {
    return prctl(PR_SET_NAME, thread_name) ? errno : 0;
  }
  // Have to change another thread's name.
  pthread_internal_t* t = reinterpret_cast<pthread_internal_t*>(thread);
  char comm_name[sizeof(TASK_COMM_FMT) + 8];
  snprintf(comm_name, sizeof(comm_name), TASK_COMM_FMT, t->tid);
  int fd = open(comm_name, O_WRONLY);
  if (fd == -1) {
    return errno;
  }
```

If we have created a user (maybe it is mysql) for mysqld，but the caller of mysqld (maybe it is root) is different from the user. The permission of /proc/ pid remain caller's. 
Finally, the open operation would fail due to permission.
