### ISSUE TITLE
Need to set sst_file_manager

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#560]
On flash devices, deleting many files too fast is causing problems. Options::sst_file_manager has a variable rate_bytes_per_sec to control how fast RocksDB deletes sst files. By utilizing this feature, we'll be able to prevent trim stalls.

**Comment by gunnarku** [comment]
RocksDB doesn't currently support dynamically updating this value. We'll need to introduce `SetDeleteRateBytesPerSecond()` and pass that through to `DeleteScheduler`.

**Comment by gunnarku** [comment]
RocksDB changes have been committed: https://github.com/facebook/rocksdb/commit/995618a821b39e6994128a43aa38761dda3505c9. We can start working on MyRocks part now.
