### ISSUE TITLE
Support dynamic CF option changes

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#561]
Currently, CF option changes need to restart mysqld. We need to find out how to change some variables dynamically.

**Comment by gunnarku** [comment]
Research about how to implement done. Changes will be most likely made tomorrow and will be pushed by early next week.

**Comment by gunnarku** [comment]
Landed as https://github.com/facebook/mysql-5.6/commit/9773f0ce456369a5b6ff2ebcde31410716727b01
