### ISSUE TITLE
multiclient_2pc-mater.opt incorrectly named and thus not used

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#581]
https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/mysql-test/suite/rocksdb_rpl/t/multiclient_2pc-mater.opt

Should be multiclient_2pc-master.opt not the missing 's' in 'master' unless it is intended to be called a slang for tomato :)

**Comment by george-lorch** [comment]
Test also appears to be incorrect here https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/mysql-test/suite/rocksdb_rpl/t/multiclient_2pc.test#L36 which temporarily disables 2pc but actually just enables it. Note that in 5.7+ disabling 2pc at SE is deprecated functionality as 2pc must be supported at all times.

**Comment by reidHoruff** [comment]
Hi George, some good catches here. This test is currently disabled on our end because it requires some tlc. This is a great place to start though. I will look into these.

**Comment by reidHoruff** [comment]
Also, can you elaborate on the change in 5.7+ for disabling 2pc? Setting rocksdb_enable_2pc=OFF is a MyRocks specific flag which disables 2pc semantics at a pretty low level. From MySQL's point of view the engine is still supporting 2pc semantics.

**Comment by george-lorch** [comment]
Actually, I conflated two ideas here, XA and 2pc, XA is built on 2pc. In 5.7, all transactional engines must support 2pc in order to play with the binlog group commit correctly. The ability to disable 2pc/XA via innodb_support_xa and tokudb_support_xa is being deprecated, and this intersects somewhat with the rocksdb_enable_2pc. 

From https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_support_xa

"innodb_support_xa is deprecated and will be removed in a future MySQL release. InnoDB support for two-phase commit in XA transactions is always enabled as of MySQL 5.7.10. Disabling innodb_support_xa is no longer permitted as it makes replication unsafe and prevents performance gains associated with binary log group commit."

So in Percona Server port we are following suite and just dropping the variable and assuming 2pc is always enabled.

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/e6e95717d5c01fde27b93fbdb039181dbd0f7712
