### ISSUE TITLE
rocksdb_background_sync should merge with rocksdb_flush_log_at_trx_commit

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#584]
The rocksdb_background_sync variable enables background syncing the WAL file every second. Since rocksdb_flush_log_at_trx_commit has been added to mimic the InnoDB behavior, rocksdb_background_sync should be removed and setting rocksdb_flush_log_at_trx_commit=2 should enabe the background sync behavior.

**Comment by alxyang** [comment]
done by https://github.com/facebook/mysql-5.6/commit/f2b12012bd31426071c960692b0c23c7a3cad7ae
