### ISSUE TITLE
Mysql-5.6+rocksdb direct i/o issue

### ISSUE THREAD

**Issue by hanseungsung** [facebook/mysql-5.6#585]
hi dear all,
I want to test direct i/o in mysql+rocksdb.
so i changed  "bool use_direct_reads = false;" to "bool use_direct_reads = true;" and "bool use_direct_writes = false;" to "bool use_direct_writes = true;"

![image](https://cloud.githubusercontent.com/assets/26833625/24577024/1989f084-1701-11e7-9c41-58e516a279f9.png)

and i did it same as below 

`cmake -DMYSQL_DATADIR=/home/rocksdata/data -DCMAKE_BUILD_TYPE= RelWithDebInfo -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DENABLE_DTRACE=0 -DCMAKE_CXX_FLAGS="-march=native" /home/team_system/mysql-5.6/build/ ..`
`make -j8`
`make install`

Then, i move to directory /usr/local/mysql. Next, i edit my.cnf file.

![image](https://cloud.githubusercontent.com/assets/26833625/24577139/4ef7d270-1703-11e7-8da2-a1e358e66803.png)

next, i installed mysql.

`scripts/mysql_install_db --defaults-file=my.cnf.rocksdb`
`su mysql -c 'bin/mysqld_safe --defaults-file=/usr/local/mysql/my.cnf.rocksdb'
`

but when i installed mysql-5.6 with rocksdb, it didn't work it. 
so, i checked error log and i got this messages .
 
![image](https://cloud.githubusercontent.com/assets/26833625/24577072/313a47b4-1702-11e7-9de6-7b91a8e0ac1b.png)

how can i fix it. i need your help.

**Comment by hermanlee** [comment]
You should be able to enable direct_io using the rocksdb_use_direct_reads and rocksdb_use_direct_writes variables instead of modifying the code directly. Add to your my.cnf file:

```
loose-rocksdb_use_direct_reads=1
loose-rocksdb_use_direct_writes=1
```

The DBOptions class is constructed and used in places where rocksdb needs to read from a file using buffered I/O (such as during initialization in listing the column families). It expects the default value to be false.

If you wanted to modify the code directly, change the following lines in storage/rocksdb/ha_rocksdb.cc

```
static MYSQL_SYSVAR_BOOL(
    use_direct_reads,
    *reinterpret_cast<my_bool *>(&rocksdb_db_options.use_direct_reads),
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "DBOptions::use_direct_reads for RocksDB", nullptr, nullptr,
    rocksdb_db_options.use_direct_reads);

static MYSQL_SYSVAR_BOOL(
    use_direct_writes,
    *reinterpret_cast<my_bool *>(&rocksdb_db_options.use_direct_writes),
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "DBOptions::use_direct_writes for RocksDB", nullptr, nullptr,
    rocksdb_db_options.use_direct_writes);
```
to
```
static MYSQL_SYSVAR_BOOL(
    use_direct_reads,
    *reinterpret_cast<my_bool *>(&rocksdb_db_options.use_direct_reads),
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "DBOptions::use_direct_reads for RocksDB", nullptr, nullptr,
    true);

static MYSQL_SYSVAR_BOOL(
    use_direct_writes,
    *reinterpret_cast<my_bool *>(&rocksdb_db_options.use_direct_writes),
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "DBOptions::use_direct_writes for RocksDB", nullptr, nullptr,
    true);
```

Around

https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/storage/rocksdb/ha_rocksdb.cc#L838.
