### ISSUE TITLE
LOCK IN SHARE MODE does not lock UPDATE

### ISSUE THREAD

**Issue by svetasmirnova** [facebook/mysql-5.6#587]
LOCK IN SHARE MODE does not lock UPDATE if "select ... lock in share mode;" selected same row in the same transaction.

How to repeat:

CREATE TABLE `t` (
`id` int(11) NOT NULL,
`f` varchar(100) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=ROCKSDB;
insert into t values(12345, 'value1'), (54321, 'value2');

Session 1:
session 1> insert into t values(12345, 'value1'), (54321, 'value2');
Query OK, 2 rows affected (0.05 sec)
Records: 2  Duplicates: 0  Warnings: 0

session 1> begin;
Query OK, 0 rows affected (0.00 sec)

session 1> select * from t where id=12345 lock in share mode;
+-------+--------+
| id    | f      |
+-------+--------+
| 12345 | value1 |
+-------+--------+
1 row in set (0.01 sec)

Session 2:
session 2> begin;
Query OK, 0 rows affected (0.00 sec)

session 2> select * from t where id=12345 lock in share mode;
+-------+--------+
| id    | f      |
+-------+--------+
| 12345 | value1 |
+-------+--------+
1 row in set (0.00 sec)

session 2> update t set f='value3' where id=12345;
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

I expect UPDATE will be blocked in session 2, but it does not.

However if I don't run select * from t where id=12345 lock in share mode; in "session 2" everything works as expected:

session 1> begin;
Query OK, 0 rows affected (0.00 sec)

session 1> select * from t where id=12345 lock in share mode;
+-------+--------+
| id    | f      |
+-------+--------+
| 12345 | value1 |
+-------+--------+
1 row in set (0.00 sec)

session 2> begin;
Query OK, 0 rows affected (0.00 sec)

session 2> update t set f='value3' where id=12345;
ERROR HY000: Lock wait timeout exceeded; try restarting transaction

MTR test case:

--source include/have_rocksdb.inc

CREATE TABLE `t` (
  `id` int(11) NOT NULL,
  `f` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=ROCKSDB;

insert into t values(12345, 'value1'), (54321, 'value2');

--connect(con1,localhost,root,,)
 
--connection default
begin;
select * from t where id=12345 lock in share mode;

--connection con1
begin;
select * from t where id=12345 lock in share mode;
--error 1205
update t set f='value3' where id=12345;

--connection default
commit;

--connection con1
commit;

drop table t;

**Comment by lth** [comment]
Fix is over here: https://github.com/facebook/rocksdb/pull/2099
