### ISSUE TITLE
MyRocks doesn't store and expose table creation time

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#592]
mysql> create table t (id int primary key) engine=rocksdb;
Query OK, 0 rows affected (0.09 sec)

mysql> show table status like 't'\G
*************************** 1. row ***************************
           Name: t
         Engine: ROCKSDB
        Version: 10
     Row_format: Fixed
           Rows: 0
 Avg_row_length: 0
    Data_length: 0
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: NULL
    Update_time: NULL
     Check_time: NULL
      Collation: latin1_bin
       Checksum: NULL
 Create_options:
        Comment:
1 row in set (0.00 sec)

**Comment by gunnarku** [comment]
AFAICS `stats.create_time` needs to be set in `ha_rocksdb::info` which implies that table creation time need to be stored in the data dictionary with all the other table related meta data. Which in turn implies that table definition DDL entry code (`Rdb_tbl_def::put_dict`?) needs to be modified.

**Comment by yoshinorim** [comment]
We're planning to store all table metadata, including table creation time, into MyRocks data dictionary (#609).

**Comment by gunnarku** [comment]
This issue has then become a subset of #609. Closing this one.

**Comment by alxyang** [comment]
re-opening since we may want this in the near future, and Transactional DDL won't be supported for awhile. cc @yoshinorim

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/57ec81595dc877f3f5494acec5d3bc24527d9656
