### ISSUE TITLE
alter table drop key cause mysqld crash

### ISSUE THREAD

**Issue by chuckcai** [facebook/mysql-5.6#602]
**Description:**
./bin/mysqld(my_print_stacktrace+0x47)[0x13c145b]
./bin/mysqld(handle_fatal_signal+0x727)[0xcfac4f]
/lib64/libpthread.so.0(+0xf500)[0x7f95efd0a500]
/lib64/libc.so.6(gsignal+0x35)[0x310b0328a5]
/lib64/libc.so.6(abort+0x175)[0x310b034085]
./bin/mysqld(_ZN7myrocks16Rdb_dict_manager20log_start_drop_indexENS_14_gl_index_id_sEPKc+0xe9)[0x14931c7]
./bin/mysqld(_ZN7myrocks16Rdb_dict_manager14add_drop_indexERKSt13unordered_setINS_14_gl_index_id_sESt4hashIS2_ESt8equal_toIS2_ESaIS2_EEPN7rocksdb10WriteBatchE+0xc3)[0x149242f]
./bin/mysqld(_ZN7myrocks10ha_rocksdb26commit_inplace_alter_tableEP5TABLEP18Alter_inplace_infob+0x68a)[0x14148c0]
./bin/mysqld(_ZN7handler29ha_commit_inplace_alter_tableEP5TABLEP18Alter_inplace_infob+0x115)[0xb058a7]
./bin/mysqld[0xf42087]
./bin/mysqld(_Z17mysql_alter_tableP3THDPcS1_P24st_ha_create_informationP10TABLE_LISTP10Alter_infojP8st_orderb+0x2e53)[0xf4a766]
./bin/mysqld(_ZN19Sql_cmd_alter_table7executeEP3THD+0x8e3)[0x119dbd3]
./bin/mysqld(_Z21mysql_execute_commandP3THD+0x10338)[0xe70511]
./bin/mysqld(_Z11mysql_parseP3THDPcjP12Parser_state+0x99d)[0xe77c7d]
./bin/mysqld(_Z16dispatch_command19enum_server_commandP3THDPcj+0x1aa3)[0xe5abd7]
./bin/mysqld(_Z10do_commandP3THD+0x773)[0xe57856]
./bin/mysqld(_Z24do_handle_one_connectionP3THD+0x4e8)[0xde8f56]
./bin/mysqld(handle_one_connection+0x57)[0xde852a]
/lib64/libpthread.so.0(+0x7851)[0x7f95efd02851]
/lib64/libc.so.6(clone+0x6d)[0x310b0e767d]
 
Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (7f9574005280): alter table `dim_ae_city_natural_condition` drop key `idx_key`
Connection ID (thread ID): 1
Status: NOT_KILLED

altert日志：
2017-04-10 13:23:20 27645 [Note] RocksDB: Begin index creation (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Begin filtering dropped index (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Finished index creation (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Finished filtering dropped index (0,263)

**How to repeat:**
CREATE TABLE `dim_city_natural_condition` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `gmt_create` datetime DEFAULT NULL ,
  `gmt_modified` datetime DEFAULT NULL,
  `country_id` varchar(50) DEFAULT NULL,
  `city_id` varchar(100) DEFAULT NULL,
  `month` date DEFAULT NULL,
  `type` varchar(100) NOT NULL,
  `value` decimal(20,4) NOT NULL,
  `unit` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  unique KEY `idx_key` (`country_id`,`city_id`,`month`)
) ENGINE=ROCKSDB DEFAULT CHARSET=utf8; 
 
alter table `dim_city_natural_condition` drop key `idx_key`, add key `idx_key` ( country_id , city_id , month );
 
alter table `dim_city_natural_condition` drop key `idx_key`;

**Cause && Suggested fix:**
With alert log, we can see:
2017-04-10 13:23:20 27645 [Note] RocksDB: Begin index creation (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Begin filtering dropped index (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Finished index creation (0,263)
2017-04-10 13:23:20 27645 [Note] RocksDB: Finished filtering dropped index (0,263)

In this situation, Rocksdb create new key with same index_id as old key, When  Rdb_drop_index_thread clear old key,  the new key's data dictionary will be dropped. After that, we execute  SQL to drop key, it makes mysqld crash. 
Rocksdb can not reuse index_id in the situation, then it will run OK!

**Comment by alxyang** [comment]
Thanks for the report. I will take a look
