### ISSUE TITLE
Build failure with GCC 6.2.0 and -Werror=nonnull-compare

### ISSUE THREAD

**Issue by gl-sergei** [facebook/mysql-5.6#605]
Build fails with error:

```
21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/ha_rocksdb.cc: In member function ‘void myrocks::ha_rocksdb::convert_record_to_storage_format(const rocksdb::Slice&, myrocks::Rdb_string_writer*, rocksdb::Slice*)’:
21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/./././rdb_utils.h:97:48: error: nonnull argument ‘pk_unpack_info’ compared to NULL [-Werror=nonnull-compare]
21:12:43  #define DBUG_ASSERT_IMP(a, b) DBUG_ASSERT(!(a) || (b))
21:12:43                                                  
21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/./././rdb_utils.h:97:31: note: in expansion of macro ‘DBUG_ASSERT’
21:12:43  #define DBUG_ASSERT_IMP(a, b) DBUG_ASSERT(!(a) || (b))
21:12:43                                ^~~~~~~~~~~
21:12:43 /mnt/workspace/mysql-5.7-param/BUILD_TYPE/debug/Host/ubuntu-yakkety-64bit/storage/rocksdb/ha_rocksdb.cc:3667:3: note: in expansion of macro ‘DBUG_ASSERT_IMP’
21:12:43    DBUG_ASSERT_IMP(m_maybe_unpack_info, pk_unpack_info);
21:12:43    ^~~~~~~~~~~~~~~
```

Here we have method `convert_record_to_storage_format` declared with `__attribute__((__nonnull__))`. Which means that it's parameters cannot be NULL.

And then it's parameter `pk_unpack_info` compared to NULL in assert
```
DBUG_ASSERT_IMP(m_maybe_unpack_info, pk_unpack_info);
```

This assert should mean that if `m_maybe_unpack_info` is not null then `pk_unpack_info` should be not null. Assert cannot be violated, because `pk_unpack_info` cannot be null according to method declaration. Either attribute nonnull should be removed, or assert should be removed.

**Comment by jkedgar** [comment]
The attribute is incorrect.  I'll get it fixed soon.

**Comment by jkedgar** [comment]
Never mind.  It looks like this was fixed as a side-effect of https://github.com/facebook/mysql-5.6/commit/5107b14404f76617756cd4c0f04cb95e41f82e2c.  I'll close this, but if you have additional problems with this, re-open it.
