### ISSUE TITLE
Enable specifying per column family options without a separate config file

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#61]
<a href="https://github.com/hermanlee"><img src="https://avatars.githubusercontent.com/u/6656176?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hermanlee](https://github.com/hermanlee)**
_Wednesday Sep 16, 2015 at 00:39 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/112_

---

The current mechanism to specify per column family options require an extra cf_options file that is read in by MyRocks/RocksDB. It would be better if the per column family options can be specified as a rocksdb variable.

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D48627

**Comment by 3manuek** [comment]
Hi @jkedgar, I tried to access the link above but is not reachable from my end. I couldn't find in the wiki the way to set the CF options at DDL. Should I set CF options by changing the `rocksdb_default_cf_options` before new CFs?

**Comment by jkedgar** [comment]
Yeah - the reviews.facebook.net site has been taken down and will no longer be available.

Prior to my change any overriding column family options had to be read from a file (specified via --rocksdb-cf-options=<filename>).  After this change you can override the column family options using a new option (--rocksdb-override-cf-options=<options>).

You can see the changes on Github here: https://github.com/facebook/mysql-5.6/commit/478d322ea865662e0f2bdf13f3093dedbf6b31c4
