### ISSUE TITLE
inserts hang in slowdown

### ISSUE THREAD

**Issue by zkong** [facebook/mysql-5.6#610]
the inserts are all stalled for a long time(3000+ seconds)
the stacks are:
311 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Prepare,myrocks::Rdb_transaction::prepare,myrocks::rocksdb_prepare,ha_prepare_low,ha_commit_trans,trans_commit,mysql_execute_command,mysql_parse,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
     34 pthread_cond_timedwait,inline_mysql_cond_timedwait,get_event,worker_main,pfs_spawn_thread,start_thread,clone
     32 pthread_cond_wait,ConditionWait,rocksdb::ThreadPool::BGThread,rocksdb::BGThreadWrapper,start_thread,clone
     32 epoll_wait,io_poll_wait,listener,get_event,worker_main,pfs_spawn_thread,start_thread,clone
     24 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Prepare,myrocks::Rdb_transaction::prepare,myrocks::rocksdb_prepare,ha_prepare_low,ha_commit_trans,trans_commit_stmt,mysql_execute_command,Prepared_statement::execute,Prepared_statement::execute_loop,mysqld_stmt_execute,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
     16 pthread_cond_wait,inline_mysql_cond_wait,pop_jobs_item,slave_worker_exec_job,handle_slave_worker,pfs_spawn_thread,start_thread,clone
      8 poll,vio_io_wait,vio_socket_io_wait,vio_read,net_read_raw_loop,net_read_packet_header,net_read_packet,my_net_read,do_command,do_handle_one_connection,handle_one_connection,pfs_spawn_thread,start_thread,clone
      7 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Prepare,myrocks::Rdb_transaction::prepare,myrocks::rocksdb_prepare,ha_prepare_low,ha_commit_trans,trans_commit_stmt,mysql_execute_command,mysql_parse,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
      5 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Commit,commit_no_binlog,myrocks::Rdb_transaction::commit,myrocks::rocksdb_commit,ha_commit_low,MYSQL_BIN_LOG::finish_commit,MYSQL_BIN_LOG::ordered_commit,MYSQL_BIN_LOG::commit,ha_commit_trans,trans_commit_stmt,mysql_execute_command,Prepared_statement::execute,Prepared_statement::execute_loop,mysqld_stmt_execute,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
      5 pthread_cond_wait,inline_mysql_cond_wait,block_until_new_connection,one_thread_per_connection_end,do_handle_one_connection,handle_one_connection,pfs_spawn_thread,start_thread,clone
      2 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Commit,commit_no_binlog,myrocks::Rdb_transaction::commit,myrocks::rocksdb_commit,ha_commit_low,MYSQL_BIN_LOG::finish_commit,MYSQL_BIN_LOG::ordered_commit,MYSQL_BIN_LOG::commit,ha_commit_trans,trans_commit_stmt,mysql_execute_command,mysql_parse,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
      2 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Commit,commit_no_binlog,myrocks::Rdb_transaction::commit,myrocks::rocksdb_commit,ha_commit_low,MYSQL_BIN_LOG::finish_commit,MYSQL_BIN_LOG::ordered_commit,MYSQL_BIN_LOG::commit,ha_commit_trans,trans_commit,mysql_execute_command,mysql_parse,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone
      1 sigwait,signal_hand,pfs_spawn_thread,start_thread,clone
      1 sigwaitinfo,timer_notify_thread,start_thread,clone
      1 select,my_sleep,sql_log_worker,pfs_spawn_thread,start_thread,clone
      1 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::JoinBatchGroup,rocksdb::DBImpl::WriteImpl,rocksdb::DBImpl::Write,myrocks::Rdb_dict_manager::commit,myrocks::Rdb_ddl_manager::persist_stats,myrocks::Rdb_background_thread::run,myrocks::Rdb_thread::thread_func,pfs_spawn_thread,start_thread,clone
      1 pthread_cond_wait,std::condition_variable::wait,wait<rocksdb::WriteThread::BlockingAwaitState::<lambda>>,rocksdb::WriteThread::BlockingAwaitState,rocksdb::WriteThread::AwaitState,rocksdb::WriteThread::EnterUnbatched,rocksdb::DBImpl::FlushMemTable,rocksdb::DBImpl::CompactRange,rocksdb::StackableDB::CompactRange,myrocks::Rdb_drop_index_thread::run,myrocks::Rdb_thread::thread_func,pfs_spawn_thread,start_thread,clone
      1 pthread_cond_timedwait,inline_mysql_cond_timedwait,timer_thread,pfs_spawn_thread,start_thread,clone
      1 pthread_cond_timedwait,inline_mysql_cond_timedwait,MYSQL_BIN_LOG::wait_for_update_relay_log,next_event,exec_relay_log_event,handle_slave_sql,pfs_spawn_thread,start_thread,clone
      1 poll,vio_io_wait,vio_socket_io_wait,vio_read,vio_read_buff,net_read_raw_loop,net_read_packet_header,net_read_packet,my_net_read,cli_safe_read,read_event,handle_slave_io,pfs_spawn_thread,start_thread,clone
      1 poll,handle_connections_sockets,mysqld_main,__libc_start_main,_start
      1 nanosleep,usleep,rocksdb::DBImpl::DelayWrite,rocksdb::DBImpl::WriteImpl,rocksdb::TransactionImpl::Prepare,myrocks::Rdb_transaction::prepare,myrocks::rocksdb_prepare,ha_prepare_low,ha_commit_trans,trans_commit_stmt,mysql_execute_command,Prepared_statement::execute,Prepared_statement::execute_loop,mysqld_stmt_execute,dispatch_command,do_command,threadpool_process_request,handle_event,worker_main,pfs_spawn_thread,start_thread,clone

**Comment by mdcallag** [comment]
Can you share:
1) my.cnf for MyRocks
2) some description of your storage -- flash, disk, etc
3) git hashes for your build -> output from mysql -e 'show global status' | grep -i hash

**Comment by gunnarku** [comment]
Closing this issue because there hasn't been any new actionable information to continue with the investigation. Please use the guidance from https://github.com/facebook/mysql-5.6/wiki/Reporting-bugs-and-asking-for-help to add any new data if it becomes available.
