### ISSUE TITLE
rocksdb.ttl_primary is unstable

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#611]
```
CURRENT_TEST: rocksdb.ttl_primary
--- /mnt/workspace/fb-mysql-5.6/mysql-test/suite/rocksdb/r/ttl_primary.result	2017-04-21 05:11:02.353689731 +0300
+++ /mnt/workspace/fb-mysql-5.6/Debug/mysql-test/var/4/log/ttl_primary.reject	2017-04-21 05:50:27.990767572 +0300
@@ -377,8 +377,6 @@
 set global rocksdb_compact_cf='default';
 SELECT * FROM t1;
 a
-10
-8
 DROP TABLE t1;
 CREATE TABLE t1 (
 a INT,
```

From the test:
```                                                                      
426 # Test to make sure that TTL retains original timestamp during update
427 CREATE TABLE t1 (                                            
428   a bigint(20) NOT NULL,                      
429   PRIMARY KEY (a)                       
430 ) ENGINE=rocksdb            
431 COMMENT='ttl_duration=5;';                    
432                                         
433 INSERT INTO t1 values (1);           
434 INSERT INTO t1 values (3);                                                  
435 INSERT INTO t1 values (5);                                   
436 --sleep 5                                                    
437 INSERT INTO t1 values (7);
438 INSERT INTO t1 values (9);  
439                             
440 UPDATE t1 SET a=a+1;                          
441 --sorted_result                         
442 SELECT * FROM t1;
```

Using sleep like this in mtr tests is not good practice. This test fails because more than the 5 second ttl_duration elapses on a slow running machine after the INSERT/UPDATE and before the SELECT. Debug sync points or specific debug engine variables should be used instead to prevent the compaction filter from running and aging out the data before it can be validated by the SELECT.

**Comment by alxyang** [comment]
We already have the debug variables in place you mention.  We use `set global rocksdb_compact_cf='default'` to manually compact column families and turn auto compaction off.

So we are controlling the compaction filter from running until we want it to.  The issue is how to properly control the time elapsed before the compaction filter starts running.  Need to think of some ways to approach this.

**Comment by george-lorch** [comment]
Then maybe just turning off auto compaction right after the --sleep 5 and before inserting the new data would be enough to create a deterministic result.

**Comment by alxyang** [comment]
auto-compaction is already disabled for the entirety of the test.  See https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/mysql-test/suite/rocksdb/t/ttl_primary.test#L7.  

> This test fails because more than the 5 second ttl_duration elapses on a slow running machine after the INSERT/UPDATE and before the SELECT. 

This isn't quite accurate.  The situation is more like below:
```
# Test to make sure that TTL retains original timestamp during update
CREATE TABLE t1 (
  a bigint(20) NOT NULL,
  PRIMARY KEY (a)
) ENGINE=rocksdb
COMMENT='ttl_duration=5;';

# inserts.... 

UPDATE t1 SET a=a+1;
--sorted_result
SELECT * FROM t1; <-- results are fine

set global rocksdb_force_flush_memtable_now=1;
set global rocksdb_compact_cf='default';

--sorted_result
SELECT * FROM t1; <--- for some reason 5 seconds elapsed before this select
DROP TABLE t1;
```

It looks like in this case, for some reason either manually flushing the memtable or compaction stalled for too long,  and the records expired. 
Can you reproduce this consistently?

**Comment by george-lorch** [comment]
OK, I thought the records expired and were removed by compaction, thus the difference in result.

This appeared this morning in our jenkins farm on the Facebook MySQL tree builds. It is the first time I have seen it in the week or two that we have this running. I haven't merged TTL into our Percona Server tree yet so it will not show there until I do.

**Comment by alxyang** [comment]
ok please let me know if it shows up more often, on our side in daily/nightly runs we haven't seen this test fail yet

**Comment by george-lorch** [comment]
Sure, if you have any ideas or want to inject any diagnostic into a branch, we can get it run until we see the failure again.

**Comment by alxyang** [comment]
one more instance of failure from percona: http://jenkins.percona.com/job/fb-mysql-5.6/93/testReport/junit/(root)/rocksdb/ttl_primary/.  I'm going to increase the sleeps by a little bit in the test to reduce flakiness.

**Comment by lth** [comment]
I think flakiness should be gone with the addition of debug ts variables.
