### ISSUE TITLE
how are indexed document path in rocksdb

### ISSUE THREAD

**Issue by benoitc** [facebook/mysql-5.6#613]
I'm wondering how the path is indexed in the database; are you storing the full path?

**Comment by hermanlee** [comment]
I'm not sure I understand your question. Can you clarify what the indexed document path is? MyRocks current does not support DocStore. Or is this a RocksDB specific issue and not MyRocks related one? Then question might be better should be forwarded to the rocksdb page at https://github.com/facebook/rocksdb/issues?

**Comment by benoitc** [comment]
I thought it was. Let's close the issue then :). Thanks for your answer!
