### ISSUE TITLE
Truncate table with partitions is inefficient

### ISSUE THREAD

**Issue by alxyang** [facebook/mysql-5.6#619]
When truncating tables without partitions the SQL layer optimizes by dropping the table, then re-creating.  This means in MyRocks the keys are removed via CompactRange in the drop index thread in the background, which is good behaviour.

However, when truncating tables with partitions the flow goes into `ha_rocksdb::truncate`, and the implementation is currently not very efficient. It seeks to the key and loops through the keys calling `delete/singledelete()` on each one.  This causes problems e.g. lots of delete markers/tombstones in RocksDB.

**Comment by yoshinorim** [comment]
Fixed in https://github.com/facebook/mysql-5.6/commit/8cc282bc1a294237aa614eae60d057f62c625bf1
