### ISSUE TITLE
Refine checkpoint logic in MyRocks

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#63]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Wednesday Sep 16, 2015 at 23:27 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/114_

---

I'd like checkpoint logic to be refactored as follows.
1. Rename variable name from rocksdb_snapshot_dir to something like rocksdb_create_checkpoint.
   The command creates checkpoint. Something like "create" "checkpoint" sounds better to me.
2. Return errors to the client if failing to create checkpoint.
   Currently the command does not return any error is failing to create checkpoint. This makes debugging hard.
3. Make it more robust
   Currently 'set global rocksdb_snapshot_dir="/data/mysql/backup/snapshot/"; ' command fails but 'set global rocksdb_snapshot_dir="/data/mysql/backup/snapshot"; ' succeeds. The former fails because "Invalid argument: Directory exists". This is a bit confusing and should accept both.
4. Add more test cases covering the above in rocksdb.checkpoint

**Comment by yoshinorim** [comment]
Patch is here, but not complete yet: https://reviews.facebook.net/D47577
