### ISSUE TITLE
unable to start mysql

### ISSUE THREAD

**Issue by EktaAgrawal1567** [facebook/mysql-5.6#638]
successfully integrated mysql with rocksdb but unable to start mysql terminal.

**Comment by gunnarku** [comment]
It would be helpful to have more information about what happened here. Can you please follow the guidance at https://github.com/facebook/mysql-5.6/wiki/Reporting-bugs-and-asking-for-help to add more details?

**Comment by EktaAgrawal1567** [comment]
Implemented MariaDB with RocksDB and it got successfully compiled.
Thanks.
