### ISSUE TITLE
Using SingleDelete() in MyRocks

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#64]
<a href="https://github.com/yoshinorim"><img src="https://avatars.githubusercontent.com/u/253614?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoshinorim](https://github.com/yoshinorim)**
_Thursday Sep 17, 2015 at 18:49 GMT_
_Originally opened as https://github.com/MySQLOnRocksDB/mysql-5.6/issues/115_

---

RocksDB added SingleDelete() support (https://reviews.facebook.net/D43179). This is very useful feature to reduce the number of tombstones, but it has to be used carefully.

In MyRocks, SingleDelete() can be used in the following conditions.
- All secondary indexes
- Primary indexes if tables have primary key columns only
- Read-Modify-Write has to be done (blind write is not allowed)

I'll start working on this task after https://reviews.facebook.net/D45873 is committed.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D48015
