### ISSUE TITLE
Support multiple prefix bloom filter size per CF

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#641]
This will be addressed in RocksDB (https://github.com/facebook/rocksdb/pull/2474). Need to make sure if it does not break in MyRocks.

**Comment by alxyang** [comment]
@lth  updated the submodule already here. https://github.com/facebook/mysql-5.6/commit/e8989c6ab4d1a539d67f751ec597db24d9e1f39c.  I'll add a test.
