### ISSUE TITLE
Unlimited index length may break MyRocks -> InnoDB replication

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#665]
InnoDB has a limitation that index length can not be bigger than 767 or 3072 bytes (https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html). MyRocks does not have that limitation. This may break replication if MyRocks is master and InnoDB is slave. Accepting keys longer than InnoDB limit also means you can't restore from MyRocks to InnoDB instances anymore.

**Comment by alxyang** [comment]
@pbjc take a look and see if you would be interested in taking this one on

**Comment by alxyang** [comment]
Looking at the documentation closer (https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html), it seems that the index length is default limited 3072, unless `innodb_large_prefix` is turned off (then its 767).   In 5.6 `innodb_large_prefix` is default OFF, in 5.7 is default ON.  

We should  introduce a similar variable, or just have a hard limit at 3072 which should work for everything. cc @yoshinorim
