### ISSUE TITLE
CREATE INDEX on large table takes very long time

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#68]
After https://reviews.facebook.net/D45873 (Transaction support) was committed, rocksdb.cardinality test started taking very long time at "create index t1_1 on t1 (id, i1);". It tried to create an index on a table t1 that had 100,000 rows, and it never finished (and reached 900 seconds timeout on my mtr).

Here is a stack trace. One CPU core used 100% CPU time.
std::__detail::_Hash_code_base<std::string,,std::_Hashtable<std::string,,std::_Hashtable<std::string,,std::unordered_map<std::string,,std::pair<unsigned,std::__detail::_Hash_node<std::pair<unsigned,__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned,std::_Hashtable<unsigned,std::_Hashtable<unsigned,std::unordered_map<unsigned,rocksdb::TransactionImpl::TryLock,rocksdb::TransactionBaseImpl::Put,Rdb_transaction::Put,ha_rocksdb::update_write_row,ha_rocksdb::write_row,handler::ha_write_row,copy_data_between_tables,mysql_alter_table,mysql_execute_command,mysql_parse,dispatch_command

**Comment by jkedgar** [comment]
I just created Issue #69 which may be the same problem.

**Comment by yoshinorim** [comment]
Yes, it's the same problem. Could you please close #69? 

The problem was many inserts within the same transaction slows down performance a lot (looks like O(n^2) order). Here is an easy way to reproduce.

```
#!/usr/bin/perl

print "BEGIN;\n";
for(my $i= 1; $i<= $ARGV[0]; $i++) {
  print "INSERT INTO r1 VALUES ($i, $i, $i, $i, $i);\n";
}
print "COMMIT;\n";


CREATE TABLE `r1` (
  `id` bigint(20) NOT NULL,
  `i1` bigint(20) DEFAULT NULL,
  `i2` bigint(20) DEFAULT NULL,
  `c1` varchar(20) DEFAULT NULL,
  `c2` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=ROCKSDB DEFAULT CHARSET=latin1 
```

INSERTs within the same transaction:
1000:  0m0.151s
10000: 0m6.752s
20000: 0m25.508s

CREATE INDEX in rocksdb.cardinality test is equivalent to 100,000 inserts within the same transaction, so it will easily take 900~ seconds.

**Comment by yoshinorim** [comment]
Anthony is looking at the issue.

**Comment by agiardullo** [comment]
https://reviews.facebook.net/D47787

**Comment by yoshinorim** [comment]
Fix committed -- https://reviews.facebook.net/D47799
