### ISSUE TITLE
With many indexes, INSERT (bulk loading) takes much longer time with Transaction API

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#70]
How to repeat:

```
* Create a table
create table r1(
       id bigint not null primary key,
       i1 bigint, #unique
       i2 bigint, #repeating
       c1 varchar(20), #unique
       c2 varchar(20) #repeating
) engine=rocksdb collate latin1_bin;

* Insert 100,000 rows
#!/usr/bin/perl

print "BEGIN;\n";
for(my $i= 1; $i<= 100000; $i++) {
  print "INSERT INTO r1 VALUES ($i, $i, $i, $i, $i);\n";
}
print "COMMIT;\n";

* Run CREATE INDEX / DELETE
create index r1_1 on r1 (id, i1);
create index r1_2 on r1 (i1, i2);
create index r1_3 on r1 (i2, i1);
create index r1_4 on r1 (c1, c2);
create index r1_5 on r1 (c2, c1);
delete from r1 where i1%2 =0;
```

Result:
Without Transaction API

```
mysql> create index r1_1 on r1 (id, i1);
Query OK, 100000 rows affected (1.75 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_2 on r1 (i1, i2);
Query OK, 100000 rows affected (1.68 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_3 on r1 (i2, i1);
Query OK, 100000 rows affected (1.92 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_4 on r1 (c1, c2);
Query OK, 100000 rows affected (2.20 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_5 on r1 (c2, c1);
Query OK, 100000 rows affected (2.62 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> delete from r1 where i1%2 =0;
Query OK, 50000 rows affected (1.25 sec)
```

With Transaction API

```
mysql> create index r1_1 on r1 (id, i1);
Query OK, 100000 rows affected (6.70 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_2 on r1 (i1, i2);
Query OK, 100000 rows affected (7.85 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_3 on r1 (i2, i1);
Query OK, 100000 rows affected (10.38 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_4 on r1 (c1, c2);
Query OK, 100000 rows affected (13.62 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_5 on r1 (c2, c1);
Query OK, 100000 rows affected (14.88 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> delete from r1 where i1%2 =0;
Query OK, 50000 rows affected (7.22 sec)
```

With Transaction API, rocksdb::ReadRecordFromWriteBatch(), rocksdb::WriteBatchEntryComparator::CompareKey(), rocksdb::WriteBatchEntryComparator::operator() and rocksdb::ReadableWriteBatch::GetEntryFromDataOffset() used ~60% CPU time in total.

**Comment by yoshinorim** [comment]
"BEGIN; INSERT (100,000 rows in total); COMMIT;" time was not much different -- 9.3s with Transaction API, 7.8s without Transaction API.

**Comment by yoshinorim** [comment]
With Transaction API, USER_KEY_COMPARISON_COUNT was 87x larger than without Transaction API. Other status counters did not show major differences.

**Comment by yoshinorim** [comment]
after 10M rows insert:
| USER_KEY_COMPARISON_COUNT       |  100011 |

create index r1_1 on r1 (id, i1);
| USER_KEY_COMPARISON_COUNT       | 17982708 | (+17882697)

create index r1_2 on r1 (i1, i2);
| USER_KEY_COMPARISON_COUNT       | 44478271 | (+26495563)

create index r1_3 on r1 (i2, i1);
| USER_KEY_COMPARISON_COUNT       | 81287050 | (+36808779)

create index r1_4 on r1 (c1, c2);
| USER_KEY_COMPARISON_COUNT       | 133380896 | (+52093846)

create index r1_5 on r1 (c2, c1);
| USER_KEY_COMPARISON_COUNT       | 193423783 | (+60042887)

**Comment by yoshinorim** [comment]
When inserting rows into a table with many indexes, USER_KEY_COMPARISON_COUNT increased a lot during inserts.

```
create table r1(
       id bigint not null primary key,
       i1 bigint,
       i2 bigint,
       c1 varchar(20),
       c2 varchar(20),
       index r1_1 (id, i1),
       index r1_2 (i1, i2),
       index r1_3 (i2, i1),
       index r1_4 (c1, c2),
       index r1_5 (c2, c1)
) engine=rocksdb collate latin1_bin;
```

Inserting 100,000 rows via single transaction:
- With TX API:
  0m23.498s
  | USER_KEY_COMPARISON_COUNT       | 60042914 |
- NO TX API:
  0m9.452s
  | USER_KEY_COMPARISON_COUNT       |   600018 |

**Comment by yoshinorim** [comment]
On auto-committed insert:
INSERT INTO r1 VALUES (1, 1, 1, 1, 1);
26  (+26)
INSERT INTO r1 VALUES (2, 2, 2, 2, 2);
181 (+155)
INSERT INTO r1 VALUES (3, 3, 3, 3, 3);
378 (+197)
INSERT INTO r1 VALUES (4, 4, 4, 4, 4);
600 (+222)
INSERT INTO r1 VALUES (5, 5, 5, 5, 5);
870 (+270)

**Comment by spetrunia** [comment]
I've tried running INSERTs, starting from an empty table. I've counted
USER_KEY_COMPARISON_COUNT values.
The statements were:

``` sql
INSERT INTO r1 VALUES (1, 1, 1, 1, 1);
INSERT INTO r1 VALUES (2, 2, 2, 2, 2);
...
INSERT INTO r1 VALUES (10, 10, 10, 10, 10);
```

Table with primary key only:

```
0   0
6   6
18  12
36  18
60  24
90  30
126 36
168 42
216 48
228 12

AVG=    22.8
```

Table with PK and 5 secondary indexes:

```
0   0
61  61
141 80
239 98
364 125
504 140
659 155
821 162
987 166
1195    208

AVG()=  119.5
```

120 = 6 \* 20,  if we have 6x indexes, we get 6x comparisons...
(All of the above is about running with the Transaction API )

**Comment by spetrunia** [comment]
Following yesterday's discussion: here's a patch that makes secondary index
writes bypass Transaction API's locking system:
https://gist.github.com/spetrunia/3fd87cdf0f09cbed115b

With this patch and table with PK + 5 secondary indexes, I get:

```
0   0
8   8
22  14
44  22
72  28
106 34
146 40
160 14
178 18
202 24
AVG()=  20.2
```

That is, the number of comparisons is way down. I'll now check whether the patch removes the slowdown.

**Comment by spetrunia** [comment]
Alas, the above patch doesn't make any difference in performance of `CREATE INDEX` statements.

Without the patch:

```
mysql> create index r1_1 on r1 (id, i1);
Query OK, 100000 rows affected (4,73 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_2 on r1 (i1, i2);
Query OK, 100000 rows affected (6,05 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_3 on r1 (i2, i1);
Query OK, 100000 rows affected (7,69 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_4 on r1 (c1, c2);
Query OK, 100000 rows affected (10,06 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_5 on r1 (c2, c1);
Query OK, 100000 rows affected (11,51 sec)
Records: 100000  Duplicates: 0  Warnings: 0
```

With the patch:

```
mysql> create index r1_1 on r1 (id, i1);
Query OK, 100000 rows affected (4,47 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_2 on r1 (i1, i2);
Query OK, 100000 rows affected (5,42 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_3 on r1 (i2, i1);
Query OK, 100000 rows affected (7,08 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_4 on r1 (c1, c2);
Query OK, 100000 rows affected (9,10 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_5 on r1 (c2, c1);
Query OK, 100000 rows affected (10,28 sec)
Records: 100000  Duplicates: 0  Warnings: 0
```

On the same machine, a tree from before the transaction API:

```
mysql> create index r1_1 on r1 (id, i1);
Query OK, 100000 rows affected (1,24 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_2 on r1 (i1, i2);
Query OK, 100000 rows affected (1,23 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_3 on r1 (i2, i1);
Query OK, 100000 rows affected (1,48 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_4 on r1 (c1, c2);
Query OK, 100000 rows affected (1,48 sec)
Records: 100000  Duplicates: 0  Warnings: 0

mysql> create index r1_5 on r1 (c2, c1);
Query OK, 100000 rows affected (1,94 sec)
Records: 100000  Duplicates: 0  Warnings: 0
```

**Comment by spetrunia** [comment]
trying to investigate where the slowdown comes from

**Comment by agiardullo** [comment]
Based on the stack Yoshinori gave, this could be a perf issue with WriteBatchWithIndex in Rocksdb.  I will investigate this further.

One optimization could be to have an option to have write-optimized transactions where we do not index the keys if we do not expect to do any Get/GetForUpdate.  Would that make sense for index builds?

**Comment by spetrunia** [comment]
Write-optimized transactions would make sense, although taking advantage of them might require some efforts in MyRocks.

(Currently, MyRocks relies on SQL layer's "fall-back" ALTER TABLE implementation. As a consequence, it doesn't care/know whether the current statement is ALTER TABLE or some other statement. If we want ALTER TABLE to use write-optimized transactions, MyRocks will need to implement certain APIs for the SQL layer. In-place ALTER TABLE looks like the first candidate)

**Comment by yoshinorim** [comment]
Note that auto-committed INSERT performance was not degraded with Sergey's patch.

many index, with tx api (with Sergey's patch):
1m15.382s for inserting 100k with auto committed

many index, without tx api:
1m22.594s for inserting 100k with auto committed

About bulk-loading optimizations in MyRocks, being aware of rocksdb_bulk_load session variable can be good start I think. Auto-detecting ALTER TABLE / LOAD DATA INFILE is nice to have, definitely.

**Comment by agiardullo** [comment]
Write-optimized transactions would only make sense if we didn't do any (or very few) gets.  From the stack Yoshinori showed me, it looks like ha_rocksdb::update_write_row() still calls transaction::Get() during the alter table.

**Comment by yoshinorim** [comment]
MyRocks calls Get() for uniqueness checking on primary key. It doesn't call Get for all the rest keys (secondary keys), so I assume write optimized transactions will help here.

**Comment by spetrunia** [comment]
@agiardullo , what do you think about the patch pasted above (https://gist.github.com/spetrunia/3fd87cdf0f09cbed115b )?  Is it ok to call txn->GetWriteBatch() and then inject writes directly into the WriteBatchWithIndex ?  (This is assuming that injected writes will not cause any conflicts)

**Comment by agiardullo** [comment]
@spetrunia , Do you also fetch the key using GetForUpdate to make sure the it is locked and there are no write conflicts?

Maybe I should create a simple api to do this called something like PutUnindexed() which will do the Put, check for conflicts, but not index this record?  (In addition to improving the perf of indexing, which is still likely beneficial).

**Comment by spetrunia** [comment]
No, MyRocks doesn't use GetForUpdate for regular updates or inserts. (the exception is unique secondary indexes. These need to maintain uniqueness, and uniqueness from SQL point of view is different from uniqueness from RocksDB's point of view).

I'm hesitant about committing to adding a new API. I think we should first explore, what takes the time and what we will want this API to do or not do.

**Comment by spetrunia** [comment]
(will soon have a variant of bulk insert mode done that uses Transaction API.. we'll see which part of the work took the time)

**Comment by yoshinorim** [comment]
I tested https://reviews.facebook.net/D48471 as below, and verified bulk load time was as good as without transaction api.

```
--- a/storage/rocksdb/ha_rocksdb.cc
+++ b/storage/rocksdb/ha_rocksdb.cc

@@ -1279,6 +1279,11 @@ public:
     read_opts= rocksdb::ReadOptions();
     read_opts.snapshot= txn->GetSnapshot();
     register_snapshot(read_opts.snapshot, thd);
+    if (THDVAR(thd, bulk_load))
+      txn->DisableIndexing();
+    else
+      txn->EnableIndexing();
+
```

**Comment by agiardullo** [comment]
Fyi, indexing is enabled by default so you don't need to call EnableIndexing() unless you previously may have called DisableIndexing().

**Comment by yoshinorim** [comment]
At a meeting yesterday, I think we agreed to skip using Transaction API for bulk loading. I think that if bulk loading path should be used or not can be checked as follows.

```
    if (THDVAR(thd, bulk_load)
        || thd->lex->sql_command == SQLCOM_CREATE_INDEX
        || thd->lex->sql_command == SQLCOM_DROP_INDEX
        || thd->lex->sql_command == SQLCOM_ALTER_TABLE)
```

**Comment by maykov** [comment]
How about statements like delete from r1 where i1%2 =0; Will they remain slow?

**Comment by yoshinorim** [comment]
@maykov Long-running updates such as your example will continue to be slow. But they won't be executed often, since slaves will lag a lot, regardless of bulk-load optimization.

**Comment by maykov** [comment]
It would be nice to get them fixed though eventually. Working on rocksdb.cardinality and rocksdb.statistics tests is much harder now.

**Comment by yoshinorim** [comment]
@maykov I think making tests faster (reducing the number of rows, updating/deleting less number of rows) is better workaround.

**Comment by maykov** [comment]
sounds good

**Comment by spetrunia** [comment]
Applied my patch over the current tree. For some reason, it is making ALTER TABLE statements slower. I'm investigating why

**Comment by spetrunia** [comment]
Ok, the problem was that the patch ended up writing into transaction's. WriteBatchWithIndex. 

Here is a way to bypass indexing: https://gist.github.com/spetrunia/850075934c368d957376   This patch works without modifying the RocksDB API, but
1. It doesn't look pretty 
2. the patch doesn't yet have tests, checks etc.
I'll continue to improve it.

**Comment by spetrunia** [comment]
# 1. Put() Variants

There are multiple variants of Put():
1. PutUntracked()
   - Acquires row lock on the record
   - Does not do the version check
     (don't need to call GetLatestSequenceForKeyFromMemtable($key) to check whether $key was modified since our snapshot)
     (Q: why does ha_rocksdb.cc have calls to PutUntracked() but not to  DeleteUntracked()?)
2. SingleDelete()
   - Regular transactional semantics, but Delete is compacted away
     when it meets its preceding Put.
3. txn->DisableIndexing()
   - Disables updates to the WBWI (the transaction has CANT-SEE-OWN-CHANGES as 
     result).
   - doesn't affect locking
4. Bypass both the locking and snapshot checking.
   Done by calling  GetWriteBatch() and injecting rows into the write batch.
   (with DisableIndexing() there are two variants: either we inject 
   rows into the WriteBatchWithIndex, or to the underlying WriteBatch).

# 2. Writes by DML statements

## 2.1 Primary Key

Primary key updates should use Put() and either Delete() or SingleDelete().
To support transactions, both locking and version checking are necessary.

Current status: Works as necessary.

## 2.2 Non-unique secondary key

Updates to non-unique secondary keys can proceeed without locking or version  checking.
A column $col from a secondary key is also present in the (primary_key, row)  key-value pair. Any concurrent update to $col will be caught by lock on the primary key.

Current status:
- the writes use PutUntracked call (no version checking)
- they dont use DeleteUntracked call, though.
- they use SingleDelete().
- locks are still taken for writes. This is redundant.

## 2.3 Unique secondary key

It is not possible to use regular locking to guarantee uniqueness for such  keys.
MyRocks uses a GetForUpdate() call to acquire a lock, and then does a range  scan with snapshot=NULL to check for duplicates.

Writes should be handled in the same way as for other secondary indexes.

## 2.4 SingleDelete support

SingleDelete-able indexes should use SingleDelete().

There is a problem with secondary indexes since there is no SingleDeleteUntracked call.
(On the other hand we don't need locks, either. Why not just inject into the WBWI ?)

## 2.5 DisableIndexing support

CAN-SEE-OWN-CHANGES is required inside a multi-statement transactions.

For single-statement transactions (ie. AUTOCOMMIT=1):
- SQL layer doesn't require CAN-SEE-OWN-CHANGES property within a statement
- However, we must make sure we are not constructing unique secondary key violations.

This means that CAN-SEE-OWN-CHANGES is required when writing into unique index.
Statements that write rows are INSERT, INSERT ... SELECT, UPDATE, etc.

DELETE never needs CAN-SEE-OWN-CHANGES.
(one must still be cautious about using DisableIndexing() globally, because DELETE statement may invoke an SP or a Trigger that writes rows to another table).

*\* conclusion: DisableIndexing() in DML statements seems not to be worth it **

# 3. Writes by CREATE/DROP INDEX

DDL commands can skip locking and version checking, because SQL layer uses 
MetaDataLock to make sure there are no concurrent modifications to the table.

Delete() for SingleDelete-able indexes should be SingleDelete().

Can use DisableIndexing(), except for the cases when we construct a unique key violation. See #88 for examples. Unique key violation can happen on a new PRIMARY key, or on a secondary unique index.

# 4. Writes done in @@rocksdb_bulk_load=1 mode

This mode should bypass
- locking 
- version checking 
- CAN-SEE-OWN-CHANGES

# 5. Writes that update Binlog position

These are likely to cause version check errors.
A transaction T gets its snapshot, makes some changes and tries to commit them.  When committing, it includes new binlog position.
There can easily be concurrent transactions that have updated binlog position since T got its snapshot.
Hence, version check MUST be disabled (i.e PutUntracked should be used).

**Comment by hermanlee** [comment]
I added the initial calls for PutUntracked() only for the bulk loading case to prevent mysql restores from tripping the sequence number issue.

**Comment by spetrunia** [comment]
https://reviews.facebook.net/D49659

**Comment by spetrunia** [comment]
I have investigated cardinality.test failure.

The findings are:
Statistics calculation code in MyRocksTablePropertiesCollector::IndexStats::merge 
simply sums up the put operations.
If somebody makes writes a table into file #1 on L0, 
then makes updates that go to file #2 on L0,
then makes updates that go to file #3 on L0,
then statistics will display all these updates as if they were distinct rows.

Example:

```
create table ten(a int primary key);
insert into ten values (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
create table one_k(a int primary key);
insert into one_k select A.a + B.a* 10 + C.a * 100 from ten A, ten B, ten C;

create table t1 (pk int primary key, col1 int);
insert into t1 select A.a + 1000* B.a, 123456 from ten B, one_k A; 
```

```
show engine rocksdb status\G
  Type: CF_COMPACTION
  Name: default
Status: 
** Compaction Stats [default] **
Level    Files   Size(MB) Score Read(GB) 
-----------------------------------------
 Sum      0/0       0.00   0.0      0.0  
 Int      0/0       0.00   0.0      0.0   ...

set global rocksdb_force_flush_memtable_now=1;
show table status; -- shows rows=10000 for t1. Ok.
```

```
update t1 set  col1=col1+1;
Query OK, 10000 rows affected (0.69 sec)
Rows matched: 10000  Changed: 10000  Warnings: 0
```

Force memtable flush:

```
set global rocksdb_force_flush_memtable_now=1;
```

```
update t1 set  col1=col1+1;
Query OK, 10000 rows affected (0.69 sec)
Rows matched: 10000  Changed: 10000  Warnings: 0
```

Force memtable flush:

```
set global rocksdb_force_flush_memtable_now=1;
```

Now:

```
MySQL [test]>  show engine rocksdb status\G
  Type: CF_COMPACTION
  Name: default
Status: 
** Compaction Stats [default] **
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(cnt)  KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0       0.53   0.8      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.1         6         3    1.843          0       0      0
 Sum      3/0       0.53   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0      0.1         6         3    1.843          0       0      0
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0      1.1         0         1    0.155          0       0      0
```

Ok we have 3 files in L0

```
MySQL [test]> SELECT table_name, table_rows FROM information_schema.tables WHERE table_schema = DATABASE();
+------------+------------+
| table_name | table_rows |
+------------+------------+
| one_k      |       1000 |
| t1         |      30000 |
| ten        |         10 |
+------------+------------+
```

table t1 has 10K rows but the statistics shows 30K  rows are present.

**Comment by spetrunia** [comment]
What I don't understand is why cardinality.test sometimes fails but sometimes doesn't.  I run the test alone, so it starts with a clean data directory.  Increasing MemTable size didn't help - the test still fails roughly 50% of the time.

**Comment by hermanlee** [comment]
In working on the stats diff, I've added a call to flush out the memtables before each test. Since the statistics are calculated during memtable flushes/compactions, the tests were producing different optimizer query plans depending on when memtables get full and are flushed.
