### ISSUE TITLE
rocksdb_rpl.multiclient_2pc is still racy

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#716]
#It occasionally can crash on the 
> set debug_sync='now SIGNAL go';

which is on con2 and not where expected on con1.

Simply run the test in heavy parallel and repeat, you'll see it : 
`./mtr --force --retry=0 --retry-failure=0 --max-test-fail=0 --no-warnings --testcase-timeout=600 --mysqld=--rocksdb --mysqld=--default-storage-engine=rocksdb --mysqld=--skip-innodb --mysqld=--default-tmp-storage-engine=MyISAM --suite=rocksdb_rpl --big-test --parallel=8 --repeat=10 multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc multiclient_2pc`

This is of course a bit extreme, but, this test fails nearly 100% of the time for me when running the full set of suites.

**Comment by lth** [comment]
I think you can run set the debug_sync variable on whichever connection you want. It seems like the server crash could happen before the set command has had a chance to return to client. Most likely it's just missing a `--error 0,2013` before that line.

I can't reproduce the problem on my machine but maybe you could try if that fixes the problem?
