### ISSUE TITLE
[question] weekly/monthly partitioning

### ISSUE THREAD

**Issue by inkrement** [facebook/mysql-5.6#717]
Does MyRocks support something like weekly/monthly partitioning? I was not able to find it in the documentation, but it would be really nice.

**Comment by yoshinorim** [comment]
MyRocks supports MySQL partitioning syntax (https://dev.mysql.com/doc/refman/5.7/en/partitioning.html). You can do weekly/monthly partitioning by range partitioning, same as InnoDB. Note that partitioning support in MyRocks is logical (not a native partition), so files are not stored separately, but dropping partitions can be done very fast.

**Comment by inkrement** [comment]
ok, thanks!
