### ISSUE TITLE
Transaction errors during bulk loading and restoring of mysql tables

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#72]
I'm encountering issues with the new Transaction engine when trying to bulk load and restore a mysql dump. Is this caused by a long running transaction that lasts through multiple memtable flushes of the same column family?

ERROR 1815 (HY000) at line 47890: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 13609984517 as the MemTable only contains changes newer than SequenceNumber 13610005598.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f
ERROR 1815 (HY000) at line 47952: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 13653628007 as the MemTable only contains changes newer than SequenceNumber 13653786517.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f
ERROR 1815 (HY000) at line 48407: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 13694271309 as the MemTable only contains changes newer than SequenceNumber 13694471349.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f
ERROR 1815 (HY000) at line 64224: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 17931416836 as the MemTable only contains changes newer than SequenceNumber 17932516994.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f
ERROR 1815 (HY000) at line 60940: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 18014967180 as the MemTable only contains changes newer than SequenceNumber 18014977181.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f
ERROR 1815 (HY000) at line 61392: Internal error: Operation failed. Try again.: Transaction could not check for conflicts for opearation at SequenceNumber 18030790288 as the MemTable only contains changes newer than SequenceNumber 18030840293.  Increasing the value of the max_write_buffer_number_to_maintain option could reduce the f

**Comment by hermanlee** [comment]
@yoshinorim @spetrunia

**Comment by spetrunia** [comment]
> Is this caused by a long running transaction that lasts through multiple memtable flushes of the same column family?

Yes. 

I guess also  `@@rocksdb_bulk_load` is not doing as much as it could be doing with TransactionAPI. We could make it bypass any Transaction API locking/checks.

**Comment by spetrunia** [comment]
I'm also wondering whether this limitation of the Transaction API is an inherent limitation.   I recall that all RocksDB on-disk files store trx numbers together with the row, except the files at the last level.   This means, Transaction API can check the row version for on-disk records, too, as long as these records are not in the last level.

**Comment by hermanlee** [comment]
I'm rerunning with a smaller bulk_load value to see if it'll behave better.

Yes. Maybe it'll also be sufficient to check the L0 files for the transaction ID since they will likely still be in memory and effectively gives us more "memtables" to check without increasing max_write_buffer_number_to_maintain.
