### ISSUE TITLE
Assertion `ikey_.type != kTypeDeletion && ikey_.type != kTypeSingleDeletion' failed.

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#74]
After restoring a large database into rocksdb and having it run for a short time, I'm hitting an assertion in the rocksdb compaction iterator.

2015-10-05 00:58:57 683994 [Note] LibRocksDB:[cf_fbobj_pk] [JOB 5] Generated table #346829: 81031 keys, 33719400 bytes
2015-10-05 00:58:57 683994 [Note] LibRocksDB:EVENT_LOG_v1 {"time_micros": 1444031937677896, "cf_name": "cf_fbobj_pk", "job": 5, "event": "table_file_creation", "file_number": 346829, "file_size": 33719400, "table_properties": {"data_size": 33557162, "index_size": 67292, "filter_size": 101317, "raw_key_size": 1620620, "raw_average_key_size": 20, "raw_value_size": 32237971, "raw_average_value_size": 397.847, "num_data_blocks": 1817, "num_entries": 81031, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "**indexstats**": "[...6  records...]", "kDeletedKeys": "0"}}
mysqld: /data/users/herman/rpmbuild/BUILD/fb-mysql-5.6.24/rocksdb/db/compaction_iterator.cc:311: void rocksdb::CompactionIterator::PrepareOutput(): Assertion `ikey_.type != kTypeDeletion && ikey_.type != kTypeSingleDeletion' failed.
07:58:57 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

key_buffer_size=16777216
read_buffer_size=1048576
max_used_connections=0
max_threads=5000
thread_count=0
connection_count=0
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 15466227 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0 thread_stack 0x30000
/usr/libexec/mysqld(my_print_stacktrace+0x2c)[0x9c0c0c]
/usr/libexec/mysqld(handle_fatal_signal+0x4a1)[0x746591]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libpthread.so.0(+0x10550)[0x7f04392d6550]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libc.so.6(gsignal+0x39)[0x7f0437585499]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libc.so.6(abort+0x14f)[0x7f0437586ccf]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libc.so.6(+0x30113)[0x7f043757e113]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libc.so.6(+0x301c3)[0x7f043757e1c3]
/usr/libexec/mysqld(_ZN7rocksdb18CompactionIterator13PrepareOutputEv+0x79)[0xb35929]
/usr/libexec/mysqld(_ZN7rocksdb13CompactionJob25ProcessKeyValueCompactionEPNS0_18SubcompactionStateE+0xa2f)[0xb3b44f]
/usr/libexec/mysqld(_ZN7rocksdb13CompactionJob3RunEv+0x358)[0xb3bd48]
/usr/libexec/mysqld(_ZN7rocksdb6DBImpl20BackgroundCompactionEPbPNS_10JobContextEPNS_9LogBufferE+0xa91)[0xa17a81]
/usr/libexec/mysqld(_ZN7rocksdb6DBImpl24BackgroundCallCompactionEv+0x222)[0xa247a2]
/usr/libexec/mysqld(_ZN7rocksdb6DBImpl16BGWorkCompactionEPv+0x67)[0xa24bc7]
/usr/libexec/mysqld[0xad8834]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libpthread.so.0(+0x7fa8)[0x7f04392cdfa8]
/usr/local/fbcode/gcc-4.8.1-glibc-2.17/lib/libc.so.6(clone+0x6d)[0x7f04376515bd]
[0x0]
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
Writing a core file

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D48207 fixed the issue.
