### ISSUE TITLE
MyRocks and Cassandra

### ISSUE THREAD

**Issue by aravind-siva-3905** [facebook/mysql-5.6#760]
This is going to be a discussion.
Both MyRocks and Cassandra uses same LSM architecture. But why they differ in their data size ? 
I did a small analysis on this. 
Table Strucuture :
<img width="659" alt="screen shot 2017-11-07 at 3 06 54 pm" src="https://user-images.githubusercontent.com/11576085/32492806-8cce2816-c3e1-11e7-8a70-b33ee9b843e1.png">
 have created the above table in both MySql (MyRocks as storage engine) and Cassandra. I have populated 5 lakhs rows in both mysql and cassandra.
The data size are as follows.
MyRocks - 879 MB.
Cassandra 86 MB.

How can cassandra store the same data but takes only 86 MB? Am I missing something ?

My my.cnf

```
rocksdb
skip-innodb
default-storage-engine=rocksdb
character-set-server=utf8
default-tmp-storage-engine=MyISAM
collation-server=utf8_bin
rocksdb_block_cache_size=4G
rocksdb_max_total_wal_size=2G
transaction-isolation=READ-COMMITTED
log-bin
binlog-format=ROW
rocksdb_default_cf_options=write_buffer_size=128m;target_file_size_base=100m;max_bytes_for_level_base=1G;level0_file_num_compaction_trigger=4;level0_slowdown_writes_trigger=10;level0_stop_writes_trigger=15;max_write_buffer_number=4;compression_per_level=kZlibCompression;bottommost_compression=kZSTD;compression_opts=-14:6:0;block_based_table_factory={cache_index_and_filter_blocks=1;filter_policy=bloomfilter:10:false;whole_key_filtering=1};level_compaction_dynamic_level_bytes=true;optimize_filters_for_hits=true;compaction_pri=kMinOverlappingRatio
```

I just want to know the reason behind this.

**Comment by mdcallag** [comment]
Discussion in progress at https://groups.google.com/forum/#!topic/myrocks-dev/N95FCR2UGoA
