### ISSUE TITLE
HHVM stops at segmentation fault.

### ISSUE THREAD

**Issue by safe-net9** [facebook/mysql-5.6#769]
I ran Wordpress on HHVM.
When Wordpress accesses MySQL, HHVM stops.

Is there any good solution?

> /var/home/ap/hhvm/bin/hhvm-gdb /var/home/ap/hhvm/bin/hhvm -c /tmp/core.11098
> Debugging with hhvm: /var/home/ap/hhvm/bin/hhvm ...
> GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-redhat-linux-gnu".
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>...
> Reading symbols from /var/home/ap/hhvm/bin/hhvm...done.
> [New LWP 11101]
> [New LWP 11100]
> [New LWP 11098]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> Core was generated by `/var/home/ap/hhvm/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode da'.
> Program terminated with signal 11, Segmentation fault.
> #0  net_field_length (packet=packet@entry=0x7f6171bf9428)
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/pack.c:25
> 25        if (*pos < 251)
> warning: File "/var/home/lib/gcc494/lib64/libstdc++.so.6.0.20-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
> To enable execution of this file add
>         add-auto-load-safe-path /var/home/lib/gcc494/lib64/libstdc++.so.6.0.20-gdb.py
> line to your configuration file "/root/.gdbinit".
> To completely disable this security protection add
>         set auto-load safe-path /
> line to your configuration file "/root/.gdbinit".
> Missing separate debuginfos, use: debuginfo-install ImageMagick-6.7.8.9-15.el7_2.x86_64 audit-libs-2.7.6-3.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-21.el7.x86_64 double-conversion-2.0.1-3.el7.x86_64 elfutils-libelf-0.168-8.el7.x86_64 expat-2.1.0-10.el7_3.x86_64 fastlz-0.1.0-0.1.20070619svnrev12.el7.x86_64 fontconfig-2.10.95-11.el7.x86_64 freetype-2.4.11-15.el7.x86_64 fribidi-0.19.4-6.el7.x86_64 gflags-2.1.1-6.el7.x86_64 glibc-2.17-196.el7.x86_64 glog-0.3.3-8.el7.x86_64 gmp-6.0.0-15.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 jemalloc-3.6.0-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.5-1.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXt-1.1.5-3.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libc-client-2007f-16.el7.x86_64 libcap-2.22-9.el7.x86_64 libcap-ng-0.7.5-4.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libcurl-7.29.0-42.el7.x86_64 libdwarf-20130207-4.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libmemcached-1.0.16-5.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libselinux-2.5-11.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libtiff-4.0.3-27.el7_3.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libuuid-2.23.2-43.el7.x86_64 libvpx-1.3.0-5.el7_0.x86_64 libxcb-1.12-1.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 libxslt-1.1.28-5.el7.x86_64 libyaml-0.1.4-11.el7_0.x86_64 lz4-1.7.3-1.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nss-3.28.4-15.el7_4.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 nss-util-3.28.4-3.el7.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 oniguruma-5.9.5-3.el7.x86_64 openldap-2.4.44-5.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pam-1.1.8-18.el7.x86_64 pcre-8.32-17.el7.x86_64 re2-20160401-2.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 sssd-client-1.15.2-50.el7_4.6.x86_64 tbb-4.1-9.20130314.el7.x86_64 unixODBC-2.3.1-11.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
> ---Type <return> to continue, or q <return> to quit---
> For more information about this security protection see the
> "Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
>         info "(gdb)Auto-loading safe path"
> Traceback (most recent call last):
>   File "/var/home/ap/hhvm/lib64/hhvm/gdb/hhvm.py", line 24, in <module>
>     import stack
>   File "/var/home/ap/hhvm/lib64/hhvm/gdb/stack.py", line 11, in <module>
>     import unwind
>   File "/var/home/ap/hhvm/lib64/hhvm/gdb/unwind.py", line 8, in <module>
>     from gdb.unwinder import Unwinder, register_unwinder
> ImportError: No module named unwinder
> (gdb) bt
> #0  net_field_length (packet=packet@entry=0x7f6171bf9428)
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/pack.c:25
> #1  0x0000000003033999 in read_ok_ex (mysql=mysql@entry=0x7f6184cb0800,
>     length=length@entry=107)
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/client.c:723
> #2  0x00000000036b8fb3 in cli_read_query_result (mysql=0x7f6184cb0800)
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/client.c:6328
> #3  0x00000000036fd36a in mysql_real_query (length=<optimized out>,
>     query=0x7f6171bf94d0 "SET NAMES utf8mb4", mysql=0x7f6184cb0800)
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/client.c:6508
> #4  mysql_set_character_set (mysql=0x7f6184cb0800,
>     cs_name=0x7f617ddb35b8 "utf8mb4")
>     at /var/home/src/hhvm-3.23.1/third-party/webscalesqlclient/src/sql-common/client.c:7424
> #5  0x00000000036fd1d1 in HPHP::f_mysql_set_charset(HPHP::String const&, HPHP::Variant const&) ()
> #6  0x00000000019ffda9 in HPHP::Variant HPHP::Native::callFuncIndirectImpl<HPHP::Variant>(HPHP::TypedValue* (*)(HPHP::ActRec*), long*, int, double*, int) ()
> #7  0x0000000001a0571a in void HPHP::Native::callFunc<false>(HPHP::Func const*, ---Type <return> to continue, or q <return> to quit---
> void*, HPHP::TypedValue*, int, HPHP::TypedValue&) ()
> #8  0x0000000001a05abb in HPHP::TypedValue* HPHP::Native::functionWrapper<false>(HPHP::ActRec*) ()
> #9  0x00000000018c48e9 in unsigned char* HPHP::dispatchImpl<false>() ()
> #10 0x00000000036855ad in HPHP::enterVMAtFunc(HPHP::ActRec*, HPHP::StackArgsState, HPHP::VarEnv*) ()
> #11 0x0000000003683f77 in HPHP::ExecutionContext::invokeFunc(HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool) ()
> #12 0x00000000037a02d1 in HPHP::ExecutionContext::invokeUnit(HPHP::Unit const*)
>     ()
> #13 0x00000000037a0111 in HPHP::invoke_file(HPHP::String const&, bool, char const*) ()
> #14 0x000000000379fed1 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
> #15 0x000000000144add4 in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
> #16 0x000000000378e387 in HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&) ()
> #17 0x00000000037866e7 in HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) ()
> #18 0x000000000174981f in HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, ---Type <return> to continue, or q <return> to quit---
> HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) ()
> #19 0x000000000174a3ff in HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() ()
> #20 0x0000000000d47b87 in HPHP::AsyncFuncImpl::ThreadFunc(void*) ()
> #21 0x0000000001528557 in HPHP::start_routine_wrapper(void*) ()
> #22 0x00007f6193c36e25 in start_thread () from /lib64/libpthread.so.0
> #23 0x00007f618d22534d in clone () from /lib64/libc.so.6

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/b4ae418dbbd4913cbf0d523569a3d4ec9ba85343
