### ISSUE TITLE
Memory leak with only SELECT statements

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#774]
This problem was first reported from MariaDB: https://jira.mariadb.org/browse/MDEV-14460

When a transaction is opened, SELECT/read-only statements also create a new savepoint with in the writebatch, even though it is not necessary. Hence, a test case such as:

BEGIN;
SELECT * FROM t1 limit 1;
SELECT * FROM t1 limit 1;
...

Will eventually cause mysqld to run out of memory. The fix would be to only create a savepoint for statements that insert data into the writebatch.

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/6ddedd8f1e0ddcbc24e8f9a005636c5463799ab7
