### ISSUE TITLE
Use SetSnapshotOnNextOperation() in MyRocks

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#79]
Currently LinkBench returns lots of kBusy errors.
Let's use this feature once it's committed in RocksDB -- https://reviews.facebook.net/D48099

**Comment by yoshinorim** [comment]
Jay found an issue that RR may break if using non-locking Get() first. For example,
1. SELECT \* FROM t
2. SELECT \* FROM t FOR UPDATE
3. UPDATE...

Then SetSnapshotOnNextOperation() creates snapshot at 2, not 1.

Jay's comments:
I looked through the RocksDB code and calling SetSnapshotOnNextOperation() does _not_ create a snapshot when Get() is called.
In order for READ_REPEATABLE mode to work I think we either need to continue to use SetSnapshot() or we need SetSnapshotOnNextOperation() to create a snapshot on Get() as well as the other operations.

**Comment by jkedgar** [comment]
Fixed in https://reviews.facebook.net/D48669
