### ISSUE TITLE
Table based rocksdb_strict_collation_check

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#81]
Currently, by default, MyRocks does not allow CHAR/VARCHAR indexes with other than utf8_bin, latin1_bin or binary collation. This is implemented at https://reviews.facebook.net/D45753, and by setting rocksdb_strict_collation_check=0, any other collation can be accepted.

We may need more fine-grained settings. Some of our existing tables are not easy to move to case sensitive, and they are not frequently accessed. For such tables, it is fine to use case insensitive collation. 

For example, the following new options can be helpful.
rocksdb_strict_collation_check=2
rocksdb_strict_collation_tables='tbl.*'
 Then any table name starting with "tbl" are ok to use case insensitive collation.

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D49035
