### ISSUE TITLE
mysql.slave_master_info and mysql.slave_relay_log_info tables cannot be opened

### ISSUE THREAD

**Issue by ovaistariq** [facebook/mysql-5.6#815]
To enable RocksDB storage engine `InnoDB` has to be disabled as explained here https://github.com/facebook/mysql-5.6/wiki/Getting-Started-with-MyRocks#set-up-mycnf

However, that means the tables `mysql.slave_master_info` and `mysql.slave_relay_log_info` cannot be used since they have the storage engine defined to be InnoDB. The storage engines for these tables should be switched to RocksDB instead so that InnoDB can continue to be disabled.

**Comment by ovaistariq** [comment]
Excerpt from log

```
2018-04-19 16:49:53 80985 [Warning] Info table is not ready to be used. Table 'mysql.slave_master_info' cannot be opened.
2018-04-19 16:49:53 80985 [Warning] Info table is not ready to be used. Table 'mysql.slave_relay_log_info' cannot be opened.
```

```
root@schemadock2188-sjc1 mysql> show create table slave_master_info\G
ERROR 1286 (42000): Unknown storage engine 'InnoDB'
```

**Comment by yoshinorim** [comment]
How did you initialize your mysql database? mysql_install_db should create slave_*info tables with RocksDB engines, if you pass my.cnf with --default-storage-engine=RocksDB.

**Comment by ovaistariq** [comment]
My bad then, I did not pass `--default-storage-engine=RocksDB` when running `mysql_install_db`
