### ISSUE TITLE
Unable to compile mysql-5.6

### ISSUE THREAD

**Issue by divgwd** [facebook/mysql-5.6#817]
Hi,
I have follow all the steps mentioned in the link below to install myrocks.
````http://myrocks.io/docs/getting-started/````
the compilation seems to  be failing with the below error 
````CMake Error at cmake/zstd.cmake:28 (MESSAGE):
  Cannot find system zstd libraries.
Call Stack (most recent call first):
  CMakeLists.txt:480 (MYSQL_CHECK_ZSTD) 
````

I  have installed zstd lib on my system.yet it doesn't seem to compile.
````
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
````
Is there something am missing ?
Thanks in advance.

**Comment by dcadevil** [comment]
You should configure the parameter -DWITH_ZSTD=........ for cmake.

**Comment by rehanazher** [comment]
I am facing same issue , i have tried with both commands : 

`cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DENABLE_DTRACE=0 -DWITH_ZSTD=1 -DCMAKE_CXX_FLAGS="-march=native"`

and 

`cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DENABLE_DTRACE=0 -DWITH_ZSTD=0 -DCMAKE_CXX_FLAGS="-march=native"`

but same error : 

```
-- HAVE_VISIBILITY_HIDDEN
CMake Error at cmake/zstd.cmake:58 (MESSAGE):
  Cannot find appropriate libraries for zstd.
Call Stack (most recent call first):
  CMakeLists.txt:480 (MYSQL_CHECK_ZSTD)


-- Configuring incomplete, errors occurred!
See also "/home/huawei/mysql-5.6/CMakeFiles/CMakeOutput.log".
See also "/home/huawei/mysql-5.6/CMakeFiles/CMakeError.log".
```

**Comment by mdcallag** [comment]
This fixed it for me on Ubuntu 16.04 with zstd.h in /usr/include and libzstd in /usr/lib/x86_64-linux-gnu

```
diff --git a/cmake/zstd.cmake b/cmake/zstd.cmake
index d4b5947..8159f31 100644
--- a/cmake/zstd.cmake
+++ b/cmake/zstd.cmake
@@ -1,5 +1,5 @@
 MACRO (FIND_SYSTEM_ZSTD)
-  FIND_PATH(PATH_TO_ZSTD NAMES zstd/zstd.h)
+  FIND_PATH(PATH_TO_ZSTD NAMES zstd.h)
   FIND_LIBRARY(ZSTD_SYSTEM_LIBRARY NAMES zstd)
   IF (PATH_TO_ZSTD AND ZSTD_SYSTEM_LIBRARY)
     SET(SYSTEM_ZSTD_FOUND 1)
```

My cmake command line is:
```
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system -DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 -DENABLE_DTRACE=0  -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_INSTALL_PREFIX=$1 \
-DWITH_SNAPPY=/usr/lib/x86_64-linux-gnu \
-DWITH_LZ4=/usr/lib/x86_64-linux-gnu \
-DWITH_ZSTD=system
```

This is from the fix for https://github.com/facebook/mysql-5.6/issues/808

**Comment by lth** [comment]
I've made the suggested change: https://github.com/facebook/mysql-5.6/commit/aff4780f45bba6d2864735bed7181a571612a37a

**Comment by lei-houjyu** [comment]
This works for me installing `libzstd-dev` instead of `zstd`

```
$ sudo apt-get install libzstd-dev
```
