### ISSUE TITLE
rocksdb_read_free_rpl_tables is not working as expected

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#822]
rocksdb_read_free_rpl_tables is used to manage what kinds of tables are read-free replicated. m_use_read_free_rpl is a member variable of ha_rocksdb to control that. m_use_read_free_rpl is initialized at ha_rocksdb::open(), and is referenced on update/delete paths. However, there is a possibility that the handler object is closed after open() before update/delete (e.g. table cache overflown), and if that happens m_use_read_free_rpl is set back to default (false), so read free replication is no longer working.

How to repeat:
- Set rocksdb_read_free_rpl_tables='.*'
- Create many tables and sessions that exceed table_cache
- Run updates to all tables. Some of tables are executed with m_use_read_free_rpl=false.

Suggested Fix:
- Similar fix like what we did in rocksdb_bulk_load
- We may deprecate rocksdb_read_free_rpl_tables and just have one global variable to turn on/off for slaves.

**Comment by george-lorch** [comment]
I have been considering making RFR a table option of some kind, then if on a slave, RFR is enabled AND the table event being handled was on a table that had the RFR option enabled, allow RFR, otherwise, follow the traditional path. I'm not sure if this would be useful enough to anyone though to make it worth the effort.

**Comment by abhinav04sharma** [comment]
@georgelorchpercona I have a patch ready to convert the variable from table regex to enum (OFF, ON, PK_ONLY). Will that work for you? I don't see any reason to have both the regex and the enum.

**Comment by lth** [comment]
https://github.com/facebook/mysql-5.6/commit/da9bd74f8d5752cf83a84a655a6d3eb38152180c
