### ISSUE TITLE
Is it okey to use Mariadb with rocksdb or your version?

### ISSUE THREAD

**Issue by ksaltik** [facebook/mysql-5.6#823]
Is it okey to use Mariadb with rocksdb module. Do you think there is performance difference between them or is it okey. Does your version support other DB Engines?

**Comment by mdcallag** [comment]
I don't think anyone on the team knows whether this is possible. My preference is for people to use the release as is. But you are welcome to figure this out and discuss what you learn on the maria-discuss mail list - http://smalldatum.blogspot.com/2018/05/where-to-ask-questions-about-myrocks.html
