### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by 474420502** [facebook/mysql-5.6#828]
I try to build myrocks with gcc-5,6,7 clang in the ubuntu 18.04.

/home/myrocks/mysql-5.6/sql/field.cc:10015:18: error: use of undeclared
      identifier 'OVERFLOW'
    if (error == OVERFLOW)

**Comment by mdcallag** [comment]
what git hash did you use?

**Comment by 474420502** [comment]
commit bb8d4ce4fa20612dec9cc3c6b27b4240a2deddf9 (HEAD -> fb-mysql-5.6.35, origin/fb-mysql-5.6.35, origin/HEAD)
@mdcallag

**Comment by mdcallag** [comment]
Looking at code in strings/dtoa.c that implements my_strtod I see that it can return EOVERFLOW in the error variable, not OVERFLOW. So this is a bug in our stuff.

Code is https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/sql/field.cc#L10015
This is JSON support we added to FB MySQL.

Nothing is special about the git hash https://github.com/facebook/mysql-5.6/commit/bb8d4ce4fa20612dec9cc3c6b27b4240a2deddf9

On Ubuntu 16.04 with gcc 5.4.0 I have compiled FB MySQL using HEAD as of 8 May 2018.

**Comment by george-lorch** [comment]
FYI, I just started seeing this as well on 18.04 on the 5.6.35 HEAD (ee761fc7a7d95af943a97aada5d453d441741b3c)

`/home/glorch/dev/MYR/facebook-mysql/sql/field.cc: In member function ‘uint Field_document::get_key_image_double(uchar*, fbson::FbsonValue*)’:
/home/glorch/dev/MYR/facebook-mysql/sql/field.cc:10015:18: error: ‘OVERFLOW’ was not declared in this scope
     if (error == OVERFLOW)
                  ^~~~~~~~
/home/glorch/dev/MYR/facebook-mysql/sql/field.cc:10015:18: note: suggested alternative: ‘EOVERFLOW’
     if (error == OVERFLOW)
                  ^~~~~~~~
                  EOVERFLOW
`

**Comment by hermanlee** [comment]
https://github.com/facebook/mysql-5.6/pull/836
