### ISSUE TITLE
rocksdb_db_write_buffer_size is meaningless

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#83]
The variable @@rocksdb_db_write_buffer_size exposed by MyRocks is not connected to any setting inside RocksDB.

Grepping for db_write_buffer_size, I find only this

```
storage/rocksdb/ha_rocksdb.cc|492| static MYSQL_SYSVAR_ULONG(db_write_buffer_size,
storage/rocksdb/ha_rocksdb.cc|493| db_options.db_write_buffer_size,
storage/rocksdb/ha_rocksdb.cc|495| "DBOptions::db_write_buffer_size for RocksDB",
storage/rocksdb/ha_rocksdb.cc|496| NULL, NULL, db_options.db_write_buffer_size,
storage/rocksdb/ha_rocksdb.cc|759| MYSQL_SYSVAR(db_write_buffer_size),
```

That is, the variable is defined but not used.

**Comment by hermanlee** [comment]
I think the option is passed to the WriteBuffer() constructor in rocksdb/db/writebuffer.h, where it is accessed in the ShouldFlush() routine. The comment in the header file states:

  // Amount of data to build up in memtables across all column
  // families before writing to disk.
  //
  // This is distinct from write_buffer_size, which enforces a limit
  // for a single memtable.
  //
  // This feature is disabled by default. Specify a non-zero value
  // to enable it.
  //
  // Default: 0 (disabled)
  size_t db_write_buffer_size;

**Comment by spetrunia** [comment]
Indeed.  Missed this line:

```
storage/rocksdb/ha_rocksdb.cc|496| NULL, NULL, db_options.db_write_buffer_size,
```

Sorry for the false alarm
