### ISSUE TITLE
@@rocksdb_force_flush_memtable_now flushes only default column family

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#84]
It calls:

```
    rdb->Flush(rocksdb::FlushOptions());
```

which calls

```
  virtual Status Flush(const FlushOptions& options) {
    return Flush(options, DefaultColumnFamily());
  }
```

One can also observe that
INFORMATION_SCHEMA.ROCKSDB_CFSTATS.CUR_SIZE_ACTIVE_MEM_TABLE is
not decreasing for non-default column families.

**Comment by maykov** [comment]
Yes, I also found this issue. Actually, It took me a day of debugging to figure it out. I will fix this in my next commit. Should be easy fix.
