### ISSUE TITLE
MyRocks: Incorrect behavior when multiple statements fail inside a transaction

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#857]
This is originally coming from https://jira.mariadb.org/browse/MDEV-16710  (that bug was reported for replication but it has nothing to do with replication. The issue is in statement rollback inside a transaction)

Run this MTR test:
```
--source include/have_rocksdb.inc

CREATE TABLE t1 (a INT PRIMARY KEY) ENGINE=RocksDB;
INSERT INTO t1 VALUES (1);
 CREATE TABLE t2 (b INT PRIMARY KEY) ENGINE=RocksDB;
 CREATE TRIGGER tr AFTER INSERT ON t2 FOR EACH ROW INSERT INTO non_existing_table VALUES (NULL);
 
BEGIN;
DELETE FROM t1;
--error 0,ER_NO_SUCH_TABLE
INSERT INTO t2 VALUES (1);
--error 0,ER_NO_SUCH_TABLE
INSERT INTO t2 VALUES (2);
SELECT * FROM t1;
COMMIT;

drop table t1,t2;
```
and observe:
```
...
BEGIN;
DELETE FROM t1;
INSERT INTO t2 VALUES (1);
INSERT INTO t2 VALUES (2);
SELECT * FROM t1;
a
1
COMMIT;
```
Note that `SELECT * FROM t` produces a row, despite the `DELETE FROM t1` a few lines above it.

**Comment by spetrunia** [comment]
This issue is related to Issue #802 . Issue #802 was about rollback for nested statements. The fix for it also covered MDEV-14460 (excessive memory usage for transactions with many statements).  It tried to redice the number of SetSavepoint/RollbackToSavepoint calls, and there's a bug in that code.

**Comment by yoshinorim** [comment]
Verified as described.

**Comment by spetrunia** [comment]
(I have a patch for this, will file a PR shortly)

**Comment by spetrunia** [comment]
Pull request https://github.com/facebook/mysql-5.6/pull/858

**Comment by spetrunia** [comment]
Closing as pull request is closed.
