### ISSUE TITLE
Add WDT support for myrockshotbackup

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#86]
Current streaming backup supports basic features only. The following features are very nice to have.
- sync_file_range() on remote host
- retrying on transmitting errors
- throttling
- parallelism

I talked with Laurent and WDT may fill the gaps.

**Comment by yoshinorim** [comment]
Burst write was addressed by --stream=xbstream.

**Comment by gunnarku** [comment]
Already completed.
