### ISSUE TITLE
Creating unique index over column with duplicate values succeeds 

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#88]
```
create table t10 (pk int primary key, a int) engine=rocksdb;

insert into t10 values 
(1, 1),
(2, 2),
(3, 3),
(4, 1),
(5, 5);
```

Now, let's add a unique index:

```
alter table t10 add unique(a);
Query OK, 5 rows affected (0.34 sec)
Records: 5  Duplicates: 0  Warnings: 0
```

It succeeds. It should fail.  Here is how it looks with a MyISAM table:

```
MySQL [test]> alter table t10m add unique(a);
ERROR 1062 (23000): Duplicate entry '1' for key 'a'
```

**Comment by spetrunia** [comment]
This is related to how issue #70 should be fixed.

If I comment out these lines in ha_rocksdb.cc 

``` C++
    if (THDVAR(thd, bulk_load)
        || thd->lex->sql_command == SQLCOM_CREATE_INDEX
        || thd->lex->sql_command == SQLCOM_DROP_INDEX
        || thd->lex->sql_command == SQLCOM_ALTER_TABLE)
      txn->DisableIndexing();
```

I get the "Duplicate entry '1' for key 'a'" error, as it should be.

**Comment by hermanlee** [comment]
This is a good test case to add to rocksdb.unique_sec.

**Comment by spetrunia** [comment]
At first, it looks like there is an easy solution: Don't call DisableIndexing() if the new table definition has a unique secondary key.

This is insufficient.
One can do this:

```
MySQL [test]> alter table t10 drop primary key, add primary key(a);
Query OK, 5 rows affected (0.28 sec)
Records: 5  Duplicates: 0  Warnings: 0

MySQL [test]> select * from t10;
+----+---+
| pk | a |
+----+---+
|  4 | 1 |
|  2 | 2 |
|  3 | 3 |
|  5 | 5 |
+----+---+
4 rows in set (0.00 sec)
```

Note that one row is silently gone.

**Comment by spetrunia** [comment]
There are two possible soutions:

# Complex solution

Analyze DDLs of the new table and of the old table and check if the old set of unique keys guarantees that uniqueness requirement of the new set of keys is satisfied. 

# Simpler solution

Call DisableIndexing().  When writing data into a unique index (either primary or secondary),  call 

```
EnableIndexing();  
txn->Put(); 
DisableIndexing(); 
```

This will cause 2 \* n_rows \* n_unique_indexes extra virtual calls.  Should be still better than checking the memtable too many times ?
