### ISSUE TITLE
Update statement returns ERROR 1815 (HY000): Internal error: NotFound:

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#90]
In trying to restore a large instance, replication fails on an update statement. The error returned is ERROR 1815: NotFound. 

Select for the row using the exact parameters returns the row. For example:

UPDATE t1 SET t = 12345, v=1 WHERE s = 1 AND r = 2 and a = 10 and type='action' and v=0;
ERROR 1815 (HY000): Internal error: NotFound:

SELECT \* FROM t1 WHERE s = 1 AND r = 2 and a = 10 and type='action' and v=0;
<row data is returned>

**Comment by santoshbanda** [comment]
Does the update succeed if you run that manually outside the replication thread?

**Comment by hermanlee** [comment]
It fails both within replication and manually running it from a mysql client.

**Comment by yoshinorim** [comment]
Fixed by https://reviews.facebook.net/D50247
