### ISSUE TITLE
Assertion  int myrocks::Rdb_key_def::unpack_simple_varchar_space_pad(myrocks::Rdb_field_packing*, Field*, uchar*, myrocks::Rdb_string_reader*, myrocks::Rdb_string_reader*) const: Assertion `unp_reader != nullptr' failed.

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#903]
Reproduced on commit 04491dbffb51146ab63eea76ba2eb1dab840115f

Somewhat simple test case, surely a bit unconventional:
> CREATE DATABASE test;
> USE test;
> SET SESSION SQL_MODE=ONLY_FULL_GROUP_BY;
> CREATE TABLE t1(a CHAR(1)) ENGINE=RocksDB CHARACTER SET utf8;
> INSERT INTO t1 VALUES(0xA7C9);
> INSERT INTO t1 VALUES(0xAAE9);
> alter table t1 change a a varchar(1)character set cp1251;
> alter TABLE t1 add b int auto_increment key;
> CREATE UNIQUE INDEX i2 ON t1(a);

The backtrace

> Thread 10 "my-oneconnectio" received signal SIGABRT, Aborted.
> [Switching to Thread 0x7fffe87f8700 (LWP 23390)]
> __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
> 51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> (gdb) bt
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
> #1  0x00007ffff5915801 in __GI_abort () at abort.c:79
> #2  0x00007ffff590539a in __assert_fail_base (fmt=0x7ffff5a8c7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555573e2414 "unp_reader != nullptr",
>     file=file@entry=0x5555573e1b30 "/home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_datadic.cc", line=line@entry=2733,
>     function=function@entry=0x5555573e5d60 <myrocks::Rdb_key_def::unpack_simple_varchar_space_pad(myrocks::Rdb_field_packing*, Field*, unsigned char*, myrocks::Rdb_string_reader*, myrocks::Rdb_string_reader*) const::__PRETTY_FUNCTION__> "int myrocks::Rdb_key_def::unpack_simple_varchar_space_pad(myrocks::Rdb_field_packing*, Field*, uchar*, myrocks::Rdb_string_reader*, myrocks::Rdb_string_reader*) const") at assert.c:92
> #3  0x00007ffff5905412 in __GI___assert_fail (assertion=0x5555573e2414 "unp_reader != nullptr", file=0x5555573e1b30 "/home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_datadic.cc", line=2733,
>     function=0x5555573e5d60 <myrocks::Rdb_key_def::unpack_simple_varchar_space_pad(myrocks::Rdb_field_packing*, Field*, unsigned char*, myrocks::Rdb_string_reader*, myrocks::Rdb_string_reader*) const::__PRETTY_FUNCTION__> "int myrocks::Rdb_key_def::unpack_simple_varchar_space_pad(myrocks::Rdb_field_packing*, Field*, uchar*, myrocks::Rdb_string_reader*, myrocks::Rdb_string_reader*) const") at assert.c:101
> #4  0x0000555556c2d5fe in myrocks::Rdb_key_def::unpack_simple_varchar_space_pad (this=0x7fffc4820740, fpi=0x7fffc4820500, field=0x7fffc401b0c0, dst=0x7fffc401b0a2 "", reader=0x7fffe87f39a0, unp_reader=0x0)
>     at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_datadic.cc:2733
> #5  0x0000555556c2a6e4 in myrocks::Rdb_key_def::unpack_field (this=0x7fffc4820740, fpi=0x7fffc4820500, field=0x7fffc401b0c0, reader=0x7fffe87f39a0, default_value=0x7fffc4016f49 "", unp_reader=0x0)
>     at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_datadic.cc:1382
> #6  0x0000555556c2aca1 in myrocks::Rdb_key_def::unpack_record (this=0x7fffc4820740, table=0x7fffc401bf80, buf=0x7fffc401b0a0 "\376", packed_key=0x7fffe87f3aa0, unpack_info=0x0, verify_row_debug_checksums=@0x7fffc4018a59: false)
>     at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_datadic.cc:1487
> #7  0x0000555556bcef73 in myrocks::ha_rocksdb::inplace_populate_sk (this=0x7fffc4018400, new_table_arg=0x7fffc401bf80, indexes=std::unordered_set with 1 element = {...}) at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/ha_rocksdb.cc:12053
> #8  0x0000555556bce60e in myrocks::ha_rocksdb::inplace_alter_table (this=0x7fffc4018400, altered_table=0x7fffc401bf80, ha_alter_info=0x7fffe87f3ee0) at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/ha_rocksdb.cc:11878
> #9  0x0000555556523dd1 in handler::ha_inplace_alter_table (this=0x7fffc4018400, altered_table=0x7fffc401bf80, ha_alter_info=0x7fffe87f3ee0) at /home/glorch/dev/ps/facebook-mysql/sql/handler.h:3122
> #10 0x000055555651af74 in mysql_inplace_alter_table (thd=0x5555583ecf40, table_list=0x7fffc4005c68, table=0x7fffc4017aa0, altered_table=0x7fffc401bf80, ha_alter_info=0x7fffe87f3ee0, inplace_supported=HA_ALTER_INPLACE_SHARED_LOCK_AFTER_PREPARE,
>     target_mdl_request=0x7fffe87f3f50, alter_ctx=0x7fffe87f4670) at /home/glorch/dev/ps/facebook-mysql/sql/sql_table.cc:6810
> #11 0x0000555556520755 in mysql_alter_table (thd=0x5555583ecf40, new_db=0x7fffc40061d0 "test", new_name=0x7fffc4005c30 "t1", create_info=0x7fffe87f58e0, table_list=0x7fffc4005c68, alter_info=0x7fffe87f5800, order_num=0, order=0x0, ignore=false)
>     at /home/glorch/dev/ps/facebook-mysql/sql/sql_table.cc:8957
> #12 0x0000555556487a16 in mysql_execute_command (thd=0x5555583ecf40, statement_start_time=0x7fffe87f6718, post_parse=0x7fffe87f6878) at /home/glorch/dev/ps/facebook-mysql/sql/sql_parse.cc:4228
> #13 0x0000555556491d54 in mysql_parse (thd=0x5555583ecf40, rawbuf=0x7fffc4005b70 "CREATE UNIQUE INDEX i2 ON t1(a)", length=31, parser_state=0x7fffe87f7170, last_timer=0x7fffe87f6878, async_commit=0x7fffe87f6843 "")
>     at /home/glorch/dev/ps/facebook-mysql/sql/sql_parse.cc:7896
> #14 0x00005555564818ce in dispatch_command (command=COM_QUERY, thd=0x5555583ecf40, packet=0x5555584a2941 "CREATE UNIQUE INDEX i2 ON t1(a)", packet_length=31) at /home/glorch/dev/ps/facebook-mysql/sql/sql_parse.cc:1919
> #15 0x000055555647f758 in do_command (thd=0x5555583ecf40) at /home/glorch/dev/ps/facebook-mysql/sql/sql_parse.cc:1193
> #16 0x0000555556439a38 in do_handle_one_connection (thd_arg=0x5555583ecf40) at /home/glorch/dev/ps/facebook-mysql/sql/sql_connect.cc:1148
> #17 0x000055555643942d in handle_one_connection (arg=0x5555583ecf40) at /home/glorch/dev/ps/facebook-mysql/sql/sql_connect.cc:969
> #18 0x0000555556ba051c in pfs_spawn_thread (arg=0x55555838fcd0) at /home/glorch/dev/ps/facebook-mysql/storage/perfschema/pfs.cc:1860
> #19 0x00007ffff660c6db in start_thread (arg=0x7fffe87f8700) at pthread_create.c:463
> #20 0x00007ffff59f688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

I have not spent any time diagnosing, will add it to my queue.

**Comment by lth** [comment]
This is the same root cause as https://github.com/facebook/mysql-5.6/issues/900
