### ISSUE TITLE
I try  to use variable "rocksdb_write_disable_wal=true" to skip write wal. But it seems wrong.

### ISSUE THREAD

**Issue by chinyajie** [facebook/mysql-5.6#906]
I try  to use variable "rocksdb_write_disable_wal=true" to skip write wal. But it seems wrong.
I still find new *.log file in .rocksdb folder. Is there some misunderstand about rocksdb_write_disable_wal. How could I totally close wal, I need to do it for stress testing.
Thank you.

![image](https://user-images.githubusercontent.com/9836595/48849531-80da1300-ede1-11e8-9545-e5b9f7fa63fb.png)
![image](https://user-images.githubusercontent.com/9836595/48849664-cf87ad00-ede1-11e8-9f08-9748882cf20b.png)
![image](https://user-images.githubusercontent.com/9836595/48849744-f2b25c80-ede1-11e8-8212-886421936990.png)

**Comment by hermanlee** [comment]
rocksdb_write_disable_wal skips writing the transaction to the WAL file. However, it does not prevent rocksdb from creating/managing WAL files. I'm not aware of an option in MyRocks to indicate to RocksDB to disable creating WAL files. For your stress test, if rocksdb_write_disable_wal is set, then your transactions will not be logged to the WAL file. The WAL file size will likely stay the same as more transactions are committed.

**Comment by chinyajie** [comment]
> rocksdb_write_disable_wal skips writing the transaction to the WAL file. However, it does not prevent rocksdb from creating/managing WAL files. I'm not aware of an option in MyRocks to indicate to RocksDB to disable creating WAL files. For your stress test, if rocksdb_write_disable_wal is set, then your transactions will not be logged to the WAL file. The WAL file size will likely stay the same as more transactions are committed.

But my log file inflate as fast as before.
![image](https://user-images.githubusercontent.com/9836595/48879719-fe386e80-ee47-11e8-97cf-aad414fcfceb.png)

![image](https://user-images.githubusercontent.com/9836595/48879702-ec56cb80-ee47-11e8-97c1-83758f46fc2e.png)

**Comment by hermanlee** [comment]
Sorry for the late reply.

It looks like disabling WAL also requires a rocksdb_enable_2pc=0 and rocksdb_flush_log_at_trx_commit=0 to be set. Otherwise, 2pc forces writes to the WAL file during the prepare phase.

**Comment by chinyajie** [comment]
> Sorry for the late reply.
> 
> It looks like disabling WAL also requires a rocksdb_enable_2pc=0 and rocksdb_flush_log_at_trx_commit=0 to be set. Otherwise, 2pc forces writes to the WAL file during the prepare phase.

> Sorry for the late reply.
> 
> It looks like disabling WAL also requires a rocksdb_enable_2pc=0 and rocksdb_flush_log_at_trx_commit=0 to be set. Otherwise, 2pc forces writes to the WAL file during the prepare phase.

Thank you.
So do I. At first I try to change the code, and then it throw coredump from  rocksdb::PessimisticTransaction::Prepare  where I changed the code. Then I realize if I really disable wal, the transaction would be a problem. So rocksdb don't permit it.

After I ad rocksdb_enable_2pc=0 to my.cnf. I got what I want.
Happy new year!
