### ISSUE TITLE
Log messages if RocksDB is disabled

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#91]
If RocksDB is disabled (InnoDB is enabled), log better messages so that users can easily figure out what is needed to enabled RocksDB.

The minimum feature required is a message in *.err. Otherwise we will make many early adopters waste time.

**Comment by gunnarku** [comment]
Fixed with https://github.com/facebook/mysql-5.6/commit/8c8c2b55008242da5066f24226510812327cdfdf
