### ISSUE TITLE
Fast table migration between instances

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#92]
We often migrate tables between instances. This has to be lightweight (not consuming lots of CPU / IO resources) and fast enough. We discussed couple of solutions and design plans. Currently there are the following solutions.
- Supporting transportable tablespace (binary copy) -- #85 . This is to develop a new feature to allow binary copy between instances.
- Making dump and data loading a lot faster. Dump is already optimized. Currently most of the CPU usage comes from uncompressing blocks. This is hard to optimize. On the other hand, data loading can be optimized further. Creating secondary indexes has to be faster too (#26 ). On table migration, it is safe to guess that:

*\* Nobody is accessing the table until loading is successful. No need to write to Memstore/L0 actually, just writing to Lmax is fine.
*\* No need to write to WAL / binary logs. If failing to load, just restarting from the beginning.
*\* Uniqueness constraint is guaranteed by user
*\* Caller can sort the original data

**Comment by jkedgar** [comment]
I doesn't sound like we have identified which way is better.  Do we want to make a decision on one or the other or work on both in parallel and see which works better in the end?

**Comment by yoshinorim** [comment]
Correct, we have not identified yet which is better. My impression is binary copy is much more difficult to implement than fast data loading, and fast data loading covers a lot more use cases (i.e. migrating from InnoDB to MyRocks, disaster recovery from backups), but we have no idea if fast data loading is fast enough. So yes, I'd like you to lead this task, researching with RocksDB team to see which is more feasible.

**Comment by gunnarku** [comment]
This is essentially a bulk load feature.
