### ISSUE TITLE
Manual does not clarify how to activate RocksDB with mysqld

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#96]
If you want to enable RocksDB in fb-mysql, you need to use something like;

[--no-defaults] --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB

This did not seem to be mentioned anywhere in the manual/rocksdb.org. Was only by researching that I found --rocksdb, then testing that found --skip-innodb --default-tmp-storage-engine=MyISAM and finally found http://serverfault.com/questions/379714/unknown-unsupported-storage-engine-innodb-mysql-ubuntu as a fix for '[ERROR] Unknown/unsupported storage engine: InnoDB'. 

Would thus be good to have a clear public manual/doc page showing how to enable RocksDB for mysql. On the same page one could add "mysql> SHOW ENGINES" as a check that activation worked.

**Comment by yoshinorim** [comment]
@RoelVdP  Thanks for pointing out. Yes, currently we require to set "--default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB" to enable RocksDB storage engine. We don't allow mixed engines across InnoDB and RocksDB right now, because it doesn't work (not transactional, not crash-safe). The manual / error messages are not helpful right now and we have plans to address it.

**Comment by mdcallag** [comment]
Responding here to share my opinion with the public:

With respect to doesn't not work, you are being too vague:
1) single-engine transactions work just fine when mysqld instance has 2+
transactional engines
2) previous transactional engines (TokuDB, PBXT) did not force this
decision on users (only one engine can be initialized)
3) this makes it much harder to try the RocksDB engine on an existing
deployment. Dump & reload is the only way to try it now. In the past we
have given Oracle/MySQL a lot of grief for new features that are not easy
to try/enable in production. Yet we have done the same here.

So if this about avoiding "not working" cases, then make cross-engine
transactions fail.

On Sat, Nov 7, 2015 at 9:06 AM, Yoshinori Matsunobu <
notifications@github.com> wrote:

> @RoelVdP https://github.com/RoelVdP Thanks for pointing out. Yes,
> currently we require to set "--default-tmp-storage-engine=MyISAM --rocksdb
> --skip-innodb --default-storage-engine=RocksDB" to enable RocksDB storage
> engine. We don't allow mixed engines across InnoDB and RocksDB right now,
> because it doesn't work (not transactional, not crash-safe). The manual /
> error messages are not helpful right now and we have plans to address it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/96#issuecomment-154723784.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by laurynas-biveinis** [comment]
Merging the already-available and rather small fixes for https://bugs.mysql.com/bug.php?id=47134, http://bugs.mysql.com/bug.php?id=70854, (and maybe even http://bugs.mysql.com/bug.php?id=70860 if desired) would reduce the entry barrier to trying a second SE, and even cross-engine transactions quite a lot. You would probably still want to avoid TC_LOG_MMAP coordinator in production (i.e. --skip-innodb whenever binlog is disabled)

**Comment by yoshinorim** [comment]
This is a "Getting Started" wiki -- https://github.com/MySQLOnRocksDB/mysql-5.6/wiki/Getting-Started-with-MyRocks . The docs are stored in old MyRocks repo and will be moved to proper location once we decide.

I'll file an issue to discuss whether to allow mixed storage engine or not.

**Comment by RoelVdP** [comment]
Thanks @yoshinorim

**Comment by gunnarku** [comment]
Documented in the wiki.
