### ISSUE TITLE
Is branch fb-mysql-8.0.13 ready for production?

### ISSUE THREAD

**Issue by louishust** [facebook/mysql-5.6#978]
Hi,

I see the branch fb-mysql-8.0.13 is in develop, when will it be ready for production?

I also see the fb-mysql-8.0.13 not contains myrocks, when will myrocks combined with 8.0?

**Comment by bratao** [comment]
I'm also VERY excited about using the 8.x branch. But is a bummer that it do not contains MyRocks =(

**Comment by lth** [comment]
If you want to try MyRocks on 8.0, you can check out Percona Server which has MyRocks on 8.0: https://github.com/percona/percona-server
