### ISSUE TITLE
mysqld fails to print any crash related information to error log for most crashes (semi-QA blocker)

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#98]
Server fails to write crash info to mysqld error log.

Use a crashing statement like: `SELECT JSON_VALID(REPEAT('{"a":',100000));`,

Then check the error log. It will not contain any crash related information, last line will be:

Version: '5.6.24-debug'  socket: '/sda/FB-mysql-5.6.24-linux-x86_64-dbg/socket.sock'  port: 18994  MySQL Community Server (GPL)

Even though a core file was written and mysqld process is gone.

This does not happen for all crashes (many print a nice stack trace of all threads), but it does for the majority of them. It _seems_ that some code paths are not covered to connect with the new full-crash-info code.

What is challenging in this case is that it avoids classifying crashing bugs based on the info available in the error log, as there is none. This is a semi-QA blocking bug.

**Comment by pengtfb** [comment]
Thanks for reporting the issue. This is expected. In some cases when mysqld commits suicide by calling abort(), it will print out the stack trace of all active threads first. But when mysqld crashes due to other causes, say, SIGBUS, SIGSEGV, etc, it will be handled by the fatal signal handler in mysqld, it will print out some stack backtrace when it is available, but in many cases the stack backtrace information is not available at all. In this particular case, the killer query causes SIGSEGV and no stack trace is available. We have been looking into the killer query and  it will be fixed soon.

**Comment by RoelVdP** [comment]
@pengtfb Thanks. I have a question; upstream mysqld always prints a stack trace in the error log, including for SIGSEGV (sig=11) crashes?

**Comment by pengtfb** [comment]
@RoelVdP You are welcome! I don't think upstream MySQL always prints out stack traces in error log for crashes.

**Comment by RoelVdP** [comment]
@pengtfb It does. In my entire QA life, I've only seen 1 or 2 times where mysqld just terminates. That's out of hundreds, if not thousands of bugs. I think this needs a review.

**Comment by RoelVdP** [comment]
It would be really great if this can be added. That way we can classify & filter issues during the ongoing testing (assume you're aware of the ongoing project)

**Comment by mdcallag** [comment]
Some code in upstream MySQL has been doing this recently, see
https://bugs.mysql.com/bug.php?id=77738

On Tue, Nov 10, 2015 at 6:31 PM, Roel Van de Paar notifications@github.com
wrote:

> It would be really great if this can be added. That way we can classify &
> filter issues during the ongoing testing (assume you're aware of the
> ongoing project)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/98#issuecomment-155638563.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by RoelVdP** [comment]
@mdcallag yes thanks - good example of the "1 or 2 times" :)

**Comment by pengtfb** [comment]
@mdcallag Thanks Mark for the info and it is good that fix will be available in 5.6.28. @RoelVdP I will look into more for that issue to see if stack trace can be printed out before crash.

**Comment by RoelVdP** [comment]
@pengtfb Thanks!

From a testing perspective, as issue #95 (which triggered the no-error-log problem) is now fixed, it would make sense for me to do another run and see if this was the only issue which caused this problem. I will do so.

**Comment by RoelVdP** [comment]
I did another testrun with a fresh build (code cloned today), and the issue seems no longer present. Will do more testing, but for the moment this issue can be closed. Thank you
